### ISSUE TITLE
Failed building wheel for cupy

### ISSUE THREAD

**Issue by Yue-Rain** [cupy/cupy#1643] opened 2018-09-13 03:39 UTC
Running setup.py install for cupy ... error
![cupy](https://user-images.githubusercontent.com/35569373/45465786-50bf2580-b749-11e8-9c0c-1f99447dd9ed.png)
any advice?
Thank you very much!!

**Comment by kmaehashi** [comment] 2018-11-15 04:18
As this is not a bug but an environment problem, I'll close this issue. Please use the Forum ([en](https://groups.google.com/forum/#!forum/cupy), [ja](https://groups.google.com/forum/#!forum/cupy-ja)) if you need further assistance.

**Closed by kmaehashi** 2018-11-15 04:18 UTC
Labels: st:awaiting-response
