### ISSUE TITLE
CUDA 11 Test: `cupy_tests.fft_tests.test_fft.TestMultiGpu`

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#3757] opened 2020-08-11 04:56 UTC
```
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuFft_param_2_{n=None, norm=None, shape=(64,)}::test_fft - AssertionError: Parameterized test failed.
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuFft_param_2_{n=None, norm=None, shape=(64,)}::test_ifft - AssertionError: Parameterized test failed.
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuFft_param_6_{n=None, norm='ortho', shape=(64,)}::test_fft - AssertionError: Parameterized test failed.
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuFft_param_6_{n=None, norm='ortho', shape=(64,)}::test_ifft - AssertionError: Parameterized test failed.
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuFft_param_24_{n=64, norm=None, shape=(0,)}::test_fft - AssertionError: Parameterized test failed.
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuFft_param_24_{n=64, norm=None, shape=(0,)}::test_ifft - AssertionError: Parameterized test failed.
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuFft_param_26_{n=64, norm=None, shape=(64,)}::test_fft - AssertionError: Parameterized test failed.
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuFft_param_26_{n=64, norm=None, shape=(64,)}::test_ifft - AssertionError: Parameterized test failed.
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuFft_param_28_{n=64, norm='ortho', shape=(0,)}::test_fft - AssertionError: Parameterized test failed.
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuFft_param_28_{n=64, norm='ortho', shape=(0,)}::test_ifft - AssertionError: Parameterized test failed.
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuFft_param_30_{n=64, norm='ortho', shape=(64,)}::test_fft - AssertionError: Parameterized test failed.
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuFft_param_30_{n=64, norm='ortho', shape=(64,)}::test_ifft - AssertionError: Parameterized test failed.
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuPlanCtxManagerFft_param_0_{n=None, norm=None, shape=(64,)}::test_fft - AssertionError: Parameterized test f...
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuPlanCtxManagerFft_param_0_{n=None, norm=None, shape=(64,)}::test_ifft - AssertionError: Parameterized test ...
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuPlanCtxManagerFft_param_1_{n=None, norm=None, shape=(128,)}::test_fft - AssertionError: Parameterized test ...
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuPlanCtxManagerFft_param_1_{n=None, norm=None, shape=(128,)}::test_ifft - AssertionError: Parameterized test...
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuPlanCtxManagerFft_param_2_{n=None, norm='ortho', shape=(64,)}::test_fft - AssertionError: Parameterized tes...
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuPlanCtxManagerFft_param_2_{n=None, norm='ortho', shape=(64,)}::test_ifft - AssertionError: Parameterized te...
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuPlanCtxManagerFft_param_3_{n=None, norm='ortho', shape=(128,)}::test_fft - AssertionError: Parameterized te...
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuPlanCtxManagerFft_param_3_{n=None, norm='ortho', shape=(128,)}::test_ifft - AssertionError: Parameterized t...
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuPlanCtxManagerFft_param_4_{n=64, norm=None, shape=(64,)}::test_fft - AssertionError: Parameterized test fai...
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuPlanCtxManagerFft_param_4_{n=64, norm=None, shape=(64,)}::test_ifft - AssertionError: Parameterized test fa...
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuPlanCtxManagerFft_param_5_{n=64, norm=None, shape=(128,)}::test_fft - AssertionError: Parameterized test fa...
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuPlanCtxManagerFft_param_5_{n=64, norm=None, shape=(128,)}::test_ifft - AssertionError: Parameterized test f...
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuPlanCtxManagerFft_param_6_{n=64, norm='ortho', shape=(64,)}::test_fft - AssertionError: Parameterized test ...
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuPlanCtxManagerFft_param_6_{n=64, norm='ortho', shape=(64,)}::test_ifft - AssertionError: Parameterized test...
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuPlanCtxManagerFft_param_7_{n=64, norm='ortho', shape=(128,)}::test_fft - AssertionError: Parameterized test...
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestMultiGpuPlanCtxManagerFft_param_7_{n=64, norm='ortho', shape=(128,)}::test_ifft - AssertionError: Parameterized tes...
```

**Comment by kmaehashi** [comment] 2020-08-11 16:22
Multi-gpu cuFFT failing with `CUFFT_EXEC_FAILED` for complex64.

cc/ @pentschev

**Comment by leofang** [comment] 2020-08-11 16:27
We should suggest the cuFFT team to include CuPy's extensive FFT tests as part of their CI...It seems to me they keep breaking the behaviors/performance/precision/etc in every release...A better documentation is the minimal requirement.

**Comment by leofang** [comment] 2020-08-12 17:25
I don't have access to any machine with CUDA 11 yet, but tend to think CUDA 11 messed up multi-GPU FFT. In one of the failing cases, the parameter is clearly supported in all previous versions:
- batch = 1
- nx = 128 
- fft type = CUFFT_C2C

See https://docs.nvidia.com/cuda/cufft/index.html#multiple-GPU-cufft-supported-functionality

If we don't get prompt replies from the cuFFT team, how about just skipping the tests and/or raising a warning if CUDA 11 + multi-GPU is in use?

**Comment by pentschev** [comment] 2020-08-12 19:45
I've been looking at this today and I noticed the failing tests are only those running on devices `1,0`, those running on `0,1` all pass for me. I tried to hack the `7_CUDALibraries/simpleCUFFT_MGPU` sample a bit to try multiple combinations of GPUs and I can't get it to fail based solely on that. Does anyone have an idea why it would only fail for devices `1,0`? Is there something in CuPy that may make the device ordering relevant for this case here?

**Comment by leofang** [comment] 2020-08-12 20:07
@pentschev That narrows down the search quite a bit! What you found reminds me a bug I discovered when working on the multi-GPU support:
https://github.com/cupy/cupy/blob/99a0214073f372263b28b49acabcaa55a290b6fc/cupy/cuda/cufft.pyx#L427-L431
I have a wild theory that they fixed the bug by requiring that when a multi-GPU plan is launched, the present device context must be the same as the first one on the list. So, we fails because when we launch a plan on `1, 0`, we're still on device 0. Peter, could you check if it's the case?

**Comment by leofang** [comment] 2020-08-12 23:18
My wild guess is wrong (I got a CUDA 11 env set up). Will try to look into that today or tomorrow. Could be that they updated how `cudaXtDesc`/`cudaLibXtDesc` is handled, which we manage ourselves.

**Comment by leofang** [comment] 2020-08-13 00:53
With the tests added in #3766 I am able to further narrow it down. The condition to trigger the error is 
- batch = 1
- C2C (complex64 to complex64; complex128 is fine)
- GPU = 1, 0
- Any legitimate nx (tried 64 & 128)

Will report back if I find out more.

**Comment by leofang** [comment] 2020-08-13 01:08
@pentschev You need to try my test case above. It's easy to tweak the example code `simpleCUFFT_MGPU.cu` (change `SIGNAL_SIZE` to `122`, which will be padded to `128`, and then `whichGPUs` to  `1, 0`). It's a regression on the cuFFT side:
```
$ ./simpleCUFFT_MGPU 

[simpleCUFFT_MGPU] is starting...

GPU Device 0: "GeForce RTX 2080 Ti" with compute capability 7.5
GPU Device 1: "GeForce RTX 2080 Ti" with compute capability 7.5
new size: 128

Running on GPUs
GPU Device 1: "GeForce RTX 2080 Ti" with compute capability 7.5
GPU Device 0: "GeForce RTX 2080 Ti" with compute capability 7.5
CUDA error at simpleCUFFT_MGPU.cu:194 code=6(CUFFT_EXEC_FAILED) "cufftXtExecDescriptorC2C(plan_input, d_signal, d_signal, CUFFT_FORWARD)"
```

**Comment by leofang** [comment] 2020-08-13 01:10
cc: @anaruse

**Comment by leofang** [comment] 2020-08-13 03:28
> * C2C (complex64 to complex64; Z2Z is fine)

Sorry, Z2Z is not fine. It's also buggy.

**Comment by leofang** [comment] 2020-08-13 03:50
PR in #3775.

**Comment by pentschev** [comment] 2020-08-13 09:00
Sorry @leofang for the delay and thanks for checking everything further and filing #3775 . I've now realized I was running `simpleCUFFT_MGPU` against CUDA 10.2 runtime, that's why I couldn't reproduce the bug. I can now reproduce it just by changing `whichGPUs` in that sample to `1,0` and nothing else. I'll raise this issue with cuFFT developers.

**Comment by leofang** [comment] 2020-08-13 15:05
Yeah! Glad to hear you can reproduce the bug, Peter. It's always a relief to know the problem is not on us 😂 By the way, this only happens with batch=1 (which is set in the simpleCUFFT_MGPU sample); for multi-batch FFT it seems fine. I suspect  putting `gpus=[3,2,1,0]` will also make it fail, but I need to first get access to a 4-GPU machine to test this. Maybe the cuFFT team have more resources than I do...

**Comment by pentschev** [comment] 2020-08-13 15:22
Yeah, I can also reproduce with 4 and 8 GPUs, using `3,2,1,0` and `7,6,5,4,3,2,1,0`, respectively. The sample is really batch=1, but since it seems that this is not a problem for larger batches I think it's safe if we leave it at that, let me know if you think otherwise.

**Comment by leofang** [comment] 2020-08-13 15:37
Yeah it's good!

**Comment by pentschev** [comment] 2020-08-13 19:26
For completeness here, this should be fixed by CUDA 11.2, as per https://github.com/cupy/cupy/pull/3775#pullrequestreview-467064724 .

**Comment by leofang** [comment] 2020-08-14 01:07
Just an aside, I am testing multi-GPU D2Z, Z2D, etc, which are not yet supported in CuPy but I plan to submit a PR, and I think they're also buggy: the output of a single-GPU plan (correct) is different from that of a multi-GPU plan (wrong). A simple reproducer is:
- batch = 4
- nx = 16 (so input is `(4, 16)` and output is `(4, 9)`)
- gpu = 0, 1
- FFT type: D2Z (float64 to complex128)

@pentschev Should I open a PR first for you to try locally? I can also push to a local branch.

**Comment by pentschev** [comment] 2020-08-14 13:15
> @pentschev Should I open a PR first for you to try locally? I can also push to a local branch.

As long as it's reproducible, either one is fine by me.

**Closed** 2020-08-14 16:53 UTC
Labels: blocking, cat:bug, prio:high

**Comment by pentschev** [comment] 2020-10-27 09:56
For future reference: I was provided with a preview build of cuFFT 11.2 and was able to verify that the issue is indeed fixed in that version, the condition in https://github.com/cupy/cupy/pull/3775/files#diff-ccb51faf00a37e7d1236eefcdef3d78aaba921baeca21e7405169a4c43d9398bR169 should then be fine and no other action should be needed on CuPy's end. Thanks everyone!

**Comment by leofang** [comment] 2020-11-13 04:53
Thank you for the update, @pentschev!!
