### ISSUE TITLE
cutensor crash in the second run

### ISSUE THREAD

**Issue by wxj6000** [cupy/cupy#7812] opened 2023-08-20 05:41 UTC
### Description

The first run of cutensor.contraction gives the identical result with cupy.einsum. However, the second run gives the incorrect result. If I comment out the first run and run the second contraction, it gives the identical result with cupy.einsum

### To Reproduce

```py
import cupy
from cupyx import cutensor

def contract(pattern, a, b):
    pattern = pattern.replace(" ", "")
    str_a, rest = pattern.split(',')
    str_b, str_c = rest.split('->')
    key = str_a + str_b
    val = list(a.shape) + list(b.shape)
    shape = {k:v for k, v in zip(key, val)}
    c = cupy.zeros([shape[k] for k in str_c], order='C')

    mode_a = list(str_a)
    mode_b = list(str_b)
    mode_c = list(str_c)

    desc_a = cutensor.create_tensor_descriptor(a)
    desc_b = cutensor.create_tensor_descriptor(b)
    desc_c = cutensor.create_tensor_descriptor(c)
    
    mode_a = cutensor.create_mode(*mode_a)
    mode_b = cutensor.create_mode(*mode_b)
    mode_c = cutensor.create_mode(*mode_c)
    alpha = 1.0
    beta = 0.0
    
    cutensor.contraction(alpha, a, desc_a, mode_a, b, desc_b, mode_b, beta, c, desc_c, mode_c)
    return c

a = cupy.random.rand(20,20,20,20)
b = cupy.random.rand(20,20)

c = contract('ijkl,ik->jl', a, b)
c_einsum = cupy.einsum('ijkl,ik->jl', a, b)
print(cupy.linalg.norm(c - c_einsum))

c = contract('ijkl,jl->ik', a, b)
c_einsum = cupy.einsum('ijkl,jl->ik', a, b)
print(cupy.linalg.norm(c - c_einsum))
```

### Installation

Wheel (`pip install cupy-***`)

### Environment

```
OS                           : Linux-5.4.143.bsk.8-amd64-x86_64-with-glibc2.31
Python Version               : 3.9.2
CuPy Version                 : 12.2.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.24.2
SciPy Version                : 1.10.0
Cython Build Version         : 0.29.36
Cython Runtime Version       : 0.29.33
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 11080
CUDA Driver Version          : 11070
CUDA Runtime Version         : 11070
cuBLAS Version               : (available)
cuFFT Version                : 10702
cuRAND Version               : 10210
cuSOLVER Version             : (11, 4, 0)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 7)
Thrust Version               : 101501
CUB Build Version            : 101501
Jitify Build Version         : <unknown>
cuDNN Build Version          : 8801
cuDNN Version                : 8500
NCCL Build Version           : 21602
NCCL Runtime Version         : 21304
cuTENSOR Version             : 10602
cuSPARSELt Build Version     : None
Device 0 Name                : Tesla V100-SXM2-32GB
Device 0 Compute Capability  : 70
Device 0 PCI Bus ID          : 0000:1B:00.0
```

**Comment by takagi** [comment] 2023-08-21 05:00
I reproduced the case, and the second `c_einsum` seems to have the wrong value.

**Comment by kmaehashi** [comment] 2023-08-21 05:21
cc/ @leofang

**Comment by leofang** [comment] 2023-08-21 05:46
I noticed that in the 2nd call `cutensorInitContractionDescriptor` is not called, which is wrong because the two contractions are distinct and should not reuse the same descriptor created/cached from the first call. Will look into the cache issue later today or tomorrow.

**Comment by leofang** [comment] 2023-08-21 12:40
OK I figured out. It has to do with the interplay with garbage collection. Consider this code:
https://github.com/cupy/cupy/blob/db0be4f6be5f849dcba0a9ca2cb5f840d8028923/cupyx/cutensor.pyx#L425-L431
`mode_A` & co are created, their pointers cached, and then destroyed due to out of scope after the 1st call is done. Then, in the 2nd call `mode_B` and `mode_C` are swapped, but they are still created in order, and the pointer address are _identical_, leading to a *cache hit* (but should have been a *miss*):
```
$ CUTENSOR_LOG_LEVEL=0 python ../cupy_cutensor.py 
['i', 'j', 'k', 'l'] ['i', 'k'] ['j', 'l']
mode(105, 106, 107, 108) 94562718015312
mode(105, 107) 94562634127728
mode(106, 108) 94562633847120
key (94562711502672, 16, 94562718497632, 94562718015312, 16, 94562706419168, 94562634127728, 16, 94562706419168, 94562633847120, 16) is not found
3.410605131648481e-13

['i', 'j', 'k', 'l'] ['j', 'l'] ['i', 'k']
mode(105, 106, 107, 108) 94562718015312
mode(106, 108) 94562634127728
mode(105, 107) 94562633847120
key (94562711502672, 16, 94562718497632, 94562718015312, 16, 94562706419168, 94562634127728, 16, 94562706419168, 94562633847120, 16) is found
99.923464935204
```  
@kmaehashi @takagi feel free to assign to me if you'd like to to send a patch 🙂

**Comment by leofang** [comment] 2023-08-21 12:43
@asi1024 I suspect #7318 has the same root cause (I didn't check carefully, but it's plausible).

**Comment by leofang** [comment] 2023-08-21 13:08
(permission tested)

**Comment by leofang** [comment] 2023-08-21 13:35
> I suspect https://github.com/cupy/cupy/issues/7318 has the same root cause (I didn't check carefully, but it's plausible).

Confirmed.

**Comment by wxj6000** [comment] 2023-08-21 16:17
Fantastic! @leofang Thank you for the prompt response.

**Closed** 2023-08-23 06:59 UTC
Labels: cat:bug
