### ISSUE TITLE
fftshift numpy 2.0 support on v13

### ISSUE THREAD

**Issue by mikaelkuisma1** [cupy/cupy#8456] opened 2024-08-06 10:47 UTC
### Description

I see that there are numpy 2.0 compatibility issues tracked under tag [np2-v13](https://github.com/cupy/cupy/labels/np2-v13)
here https://github.com/cupy/cupy/issues/8306#issuecomment-2199275967 so here is one of them, as fftshift calls numpy.compat which is no longer supported.

So far, this was the only error produced with GPAW's GPU test suite when running with numpy 2.0.1 and cupy 13.2.

### To Reproduce

```py
import cupy
cupy.fft.fftshift(cupy.zeros((3,3,3)), axes=[0,1,2])
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kuisma/gpaw-numpy2/lib/python3.10/site-packages/cupy/fft/_fft.py", line 1101, in fftshift
    elif isinstance(axes, np.compat.integer_types):
  File "/home/kuisma/gpaw-numpy2/lib/python3.10/site-packages/numpy/__init__.py", line 397, in __getattr__
    raise AttributeError(
AttributeError: `np.compat` was removed in the NumPy 2.0 release. There's no replacement, as Python 2 is no longer supported.. Did you mean: 'concat'?
```

### Installation

Source (`pip install cupy`)

### Environment

```
(gpaw-numpy2) kuisma@ampere:~/gpaw-numpy2/gpaw$ python -c "import cupy; cupy.show_config()"
OS                           : Linux-6.5.0-44-generic-x86_64-with-glibc2.35
Python Version               : 3.10.12
CuPy Version                 : 13.2.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 2.0.1
SciPy Version                : 1.14.0
Cython Build Version         : 0.29.37
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda-12.1
nvcc PATH                    : /usr/local/cuda-12.1/bin/nvcc
CUDA Build Version           : 12010
CUDA Driver Version          : 12040
CUDA Runtime Version         : 12010 (linked to CuPy) / 12010 (locally installed)
cuBLAS Version               : (available)
cuFFT Version                : 11002
cuRAND Version               : 10302
cuSOLVER Version             : (11, 4, 5)
cuSPARSE Version             : (available)
NVRTC Version                : (12, 1)
Thrust Version               : 200200
CUB Build Version            : 200200
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA RTX A4000
Device 0 Compute Capability  : 86
Device 0 PCI Bus ID          : 0000:21:00.0

```

### Additional Information

```
>>> import numpy
>>> numpy.__version__
'2.0.1'
```

**Comment by kmaehashi** [comment] 2024-08-07 10:47
Thanks for reporting @mikaelkuisma1.
This is a duplicate of #8393 and the fix will be shipped in the release this month.

**Closed by kmaehashi** 2024-08-07 10:47 UTC
Labels: cat:bug, to-be-backported, prio:high, np2-v13
