### ISSUE TITLE
Error when including `mma.h`: instance of overloaded function "__half::__half" matches the specified type

### ISSUE THREAD

**Issue by mrakgr** [cupy/cupy#8146] opened 2024-01-30 13:22 UTC
### Description

I am trying to figure out why I am getting the following error when I try to include `mma.h`.

```
PS D:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests>  & 'C:\Users\mrakg\AppData\Local\Programs\Python\Python311\python.exe' 'c:\Users\mrakg\.vscode\extensions\ms-python.python-2023.22.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '54774' '--' 'D:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cuda_experiments\tensor1\bug_mma.py' 
Traceback (most recent call last):
  File "C:\Users\mrakg\AppData\Local\Programs\Python\Python311\Lib\site-packages\cupy\cuda\compiler.py", line 64, in _run_cc
    log = subprocess.check_output(cmd, cwd=cwd, env=env,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrakg\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrakg\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program', 'Files\\NVIDIA', 'GPU', 'Computing', 'Toolkit\\CUDA\\v12.3\\bin\\nvcc.EXE', '-gencode=arch=compute_89,code=sm_89', '--cubin', '-IC:\\Users\\mrakg\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\cupy\\_core\\include', '-IC:\\Users\\mrakg\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\cupy\\_core\\include\\cupy\\_cuda\\cuda-12', '-IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.3\\include', '-ftz=true', 'C:\\Users\\mrakg\\AppData\\Local\\Temp\\tmpoagos1yu\\acc767be8a23880dc02bbd7d5dbfb4c5d918a909.cu']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mrakg\AppData\Local\Programs\Python\Python311\Lib\site-packages\cupy\cuda\compiler.py", line 366, in compile_using_nvcc
    _run_cc(cmd, root_dir, 'nvcc', log_stream)
  File "C:\Users\mrakg\AppData\Local\Programs\Python\Python311\Lib\site-packages\cupy\cuda\compiler.py", line 80, in _run_cc
    raise NVCCException(msg)
cupy.cuda.compiler.NVCCException: `nvcc` command returns non-zero exit status.
command: ['C:\\Program', 'Files\\NVIDIA', 'GPU', 'Computing', 'Toolkit\\CUDA\\v12.3\\bin\\nvcc.EXE', '-gencode=arch=compute_89,code=sm_89', '--cubin', '-IC:\\Users\\mrakg\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\cupy\\_core\\include', '-IC:\\Users\\mrakg\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\cupy\\_core\\include\\cupy\\_cuda\\cuda-12', '-IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.3\\include', '-ftz=true', 'C:\\Users\\mrakg\\AppData\\Local\\Temp\\tmpoagos1yu\\acc767be8a23880dc02bbd7d5dbfb4c5d918a909.cu']
return-code: 1
stdout/stderr:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\include\cuda_bf16.hpp(260): error: no instance of overloaded function "__half::__half" matches the specified type
  __declspec(__host__) __declspec(__device__) __forceinline __half::__half(const __nv_bfloat16 f)
                                                                    ^

1 error detected in the compilation of "C:/Users/mrakg/AppData/Local/Temp/tmpoagos1yu/acc767be8a23880dc02bbd7d5dbfb4c5d918a909.cu".
acc767be8a23880dc02bbd7d5dbfb4c5d918a909.cu


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cuda_experiments\tensor1\bug_mma.py", line 10, in <module>
    kernel = module.get_function('mykernel')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cupy\_core\raw.pyx", line 485, in cupy._core.raw.RawModule.get_function
  File "cupy\_core\raw.pyx", line 96, in cupy._core.raw.RawKernel.kernel.__get__
  File "cupy\_core\raw.pyx", line 113, in cupy._core.raw.RawKernel._kernel
  File "cupy\_util.pyx", line 64, in cupy._util.memoize.decorator.ret
  File "cupy\_core\raw.pyx", line 536, in cupy._core.raw._get_raw_module
  File "cupy\_core\core.pyx", line 2188, in cupy._core.core.compile_with_cache
  File "cupy\_core\core.pyx", line 2251, in cupy._core.core.compile_with_cache
  File "C:\Users\mrakg\AppData\Local\Programs\Python\Python311\Lib\site-packages\cupy\cuda\compiler.py", line 496, in _compile_module_with_cache
    return _compile_with_cache_cuda(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrakg\AppData\Local\Programs\Python\Python311\Lib\site-packages\cupy\cuda\compiler.py", line 589, in _compile_with_cache_cuda
    cubin = compile_using_nvcc(source, options, arch,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrakg\AppData\Local\Programs\Python\Python311\Lib\site-packages\cupy\cuda\compiler.py", line 376, in compile_using_nvcc
    raise cex
cupy.cuda.compiler.CompileException: `nvcc` command returns non-zero exit status.
command: ['C:\\Program', 'Files\\NVIDIA', 'GPU', 'Computing', 'Toolkit\\CUDA\\v12.3\\bin\\nvcc.EXE', '-gencode=arch=compute_89,code=sm_89', '--cubin', '-IC:\\Users\\mrakg\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\cupy\\_core\\include', '-IC:\\Users\\mrakg\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\cupy\\_core\\include\\cupy\\_cuda\\cuda-12', '-IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.3\\include', '-ftz=true', 'C:\\Users\\mrakg\\AppData\\Local\\Temp\\tmpoagos1yu\\acc767be8a23880dc02bbd7d5dbfb4c5d918a909.cu']
return-code: 1
stdout/stderr:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\include\cuda_bf16.hpp(260): error: no instance of overloaded function "__half::__half" matches the specified type
  __declspec(__host__) __declspec(__device__) __forceinline __half::__half(const __nv_bfloat16 f)
                                                                    ^

1 error detected in the compilation of "C:/Users/mrakg/AppData/Local/Temp/tmpoagos1yu/acc767be8a23880dc02bbd7d5dbfb4c5d918a909.cu".
acc767be8a23880dc02bbd7d5dbfb4c5d918a909.cu
```

### To Reproduce

```py
import cupy as cp

kernel_code = '''
#include <mma.h>
extern "C" __global__ void mykernel() {
}
'''
module = cp.RawModule(code=kernel_code, backend='nvcc')
kernel = module.get_function('mykernel')
```

### Installation

Wheel (`pip install cupy-***`)

### Environment

```
PS D:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cuda_experiments\tensor1> python -c "import cupy; cupy.show_config()"
OS                           : Windows-10-10.0.22631-SP0
Python Version               : 3.11.6
CuPy Version                 : 12.2.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.26.1
SciPy Version                : None
Cython Build Version         : 0.29.36
Cython Runtime Version       : None
CUDA Root                    : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3
nvcc PATH                    : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\bin\nvcc.EXE
CUDA Build Version           : 12020
CUDA Driver Version          : 12030
CUDA Runtime Version         : 12030
cuBLAS Version               : (available)
cuFFT Version                : 11012
cuRAND Version               : 10304
cuSOLVER Version             : (11, 5, 4)
cuSPARSE Version             : (available)
NVRTC Version                : (12, 3)
Thrust Version               : 200101
CUB Build Version            : 200101
Jitify Build Version         : 4a37de0
cuDNN Build Version          : (not loaded; try `import cupy.cuda.cudnn` first)
cuDNN Version                : (not loaded; try `import cupy.cuda.cudnn` first)
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 4060
Device 0 Compute Capability  : 89
Device 0 PCI Bus ID          : 0000:01:00.0
```

### Additional Information

A week ago, I did a fresh WSL install, and it was happening there as well, so I don't think this error has anything to do with the MSVC host compiler that NVCC is using under the hood.

**Comment by mrakgr** [comment] 2024-01-30 13:34
Note that a similar version of the above program works with a Cuda C++ sample project so I am sure this problem is CuPy related now. Do those includes being passed before the main library include have something to do with it, or is some compiler flag missing?

**Comment by mrakgr** [comment] 2024-01-30 14:13
```py
import cupy as cp

kernel_code = '''
#include <mma.h>
extern "C" __global__ void mykernel() {
    printf("Hello.\\n");
}
'''
module = cp.RawModule(code=kernel_code, backend='nvrtc')
module.get_function('mykernel')((1,),(1,),())
```

A work around for this is to use the NVRTC backend.

**Comment by mrakgr** [comment] 2024-01-30 14:17
I'll do that from here on out then. The reason why I went with NVCC is because NVRTC doesn't have good library support (or it didn't when I used it back in 2018) but there isn't anything I need from other libs at the moment, so it is fine.

**Comment by kmaehashi** [comment] 2024-01-31 04:42
Could you try with CuPy v13? I think relevant fixes are added (e.g. #7776)
cc/ @leofang

**Comment by leofang** [comment] 2024-01-31 04:52
I was actually puzzled when I read this issue. I would think NVRTC should fail too, but this is the first time I hear NVRTC is working while NVCC isn't, usually it's the other way around 😂 

Yeah, it'd be nice if @mrakgr you could try CuPy v13.0.0 and let us know.

**Comment by mrakgr** [comment] 2024-01-31 09:01
No, even after the upgrade the error still happens for me. Note, that this is not a Windows only error. I ran into it on WSL, in the [context of trying out the cuBLASDx library](https://forums.developer.nvidia.com/t/cublasdx-no-instance-of-overloaded-function-half-half-matches-the-specified-type/). It was a fresh install.

```
PowerShell 7.4.1
PS D:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests>  & 'C:\Users\mrakg\AppData\Local\Programs\Python\Python311\python.exe' 'c:\Users\mrakg\.vscode\extensions\ms-python.python-2023.22.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '50519' '--' 'D:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cuda_experiments\tensor1\bug_mma.py' 
Traceback (most recent call last):
  File "C:\Users\mrakg\AppData\Local\Programs\Python\Python311\Lib\site-packages\cupy\cuda\compiler.py", line 62, in _run_cc
    log = subprocess.check_output(cmd, cwd=cwd, env=env,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrakg\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrakg\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program', 'Files\\NVIDIA', 'GPU', 'Computing', 'Toolkit\\CUDA\\v12.3\\bin\\nvcc.EXE', '-gencode=arch=compute_89,code=sm_89', '--cubin', '-IC:\\Users\\mrakg\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\cupy\\_core\\include/cupy/_cccl/cub', '-IC:\\Users\\mrakg\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\cupy\\_core\\include/cupy/_cccl/thrust', '-IC:\\Users\\mrakg\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\cupy\\_core\\include/cupy/_cccl/libcudacxx', '--std=c++11', '-IC:\\Users\\mrakg\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\cupy\\_core\\include', '-IC:\\Users\\mrakg\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\cupy\\_core\\include\\cupy\\_cuda\\cuda-12', '-IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.3\\include', '-ftz=true', 'C:\\Users\\mrakg\\AppData\\Local\\Temp\\tmpjfexj258\\30f657ba69f45ef40c27faa24896d8ef25928800.cu']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mrakg\AppData\Local\Programs\Python\Python311\Lib\site-packages\cupy\cuda\compiler.py", line 363, in compile_using_nvcc
    _run_cc(cmd, root_dir, 'nvcc', log_stream)
  File "C:\Users\mrakg\AppData\Local\Programs\Python\Python311\Lib\site-packages\cupy\cuda\compiler.py", line 78, in _run_cc
    raise NVCCException(msg)
cupy.cuda.compiler.NVCCException: `nvcc` command returns non-zero exit status.
command: ['C:\\Program', 'Files\\NVIDIA', 'GPU', 'Computing', 'Toolkit\\CUDA\\v12.3\\bin\\nvcc.EXE', '-gencode=arch=compute_89,code=sm_89', '--cubin', '-IC:\\Users\\mrakg\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\cupy\\_core\\include/cupy/_cccl/cub', '-IC:\\Users\\mrakg\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\cupy\\_core\\include/cupy/_cccl/thrust', '-IC:\\Users\\mrakg\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\cupy\\_core\\include/cupy/_cccl/libcudacxx', '--std=c++11', '-IC:\\Users\\mrakg\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\cupy\\_core\\include', '-IC:\\Users\\mrakg\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\cupy\\_core\\include\\cupy\\_cuda\\cuda-12', '-IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.3\\include', '-ftz=true', 'C:\\Users\\mrakg\\AppData\\Local\\Temp\\tmpjfexj258\\30f657ba69f45ef40c27faa24896d8ef25928800.cu']
return-code: 1
stdout/stderr:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\include\cuda_bf16.hpp(260): error: no instance of overloaded function "__half::__half" matches the specified type
  __declspec(__host__) __declspec(__device__) __forceinline __half::__half(const __nv_bfloat16 f)
                                                                    ^

1 error detected in the compilation of "C:/Users/mrakg/AppData/Local/Temp/tmpjfexj258/30f657ba69f45ef40c27faa24896d8ef25928800.cu".
nvcc warning : The -std=c++11 flag is not supported with the configured host compiler. Flag will be ignored.
30f657ba69f45ef40c27faa24896d8ef25928800.cu


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cuda_experiments\tensor1\bug_mma.py", line 10, in <module>
    module.get_function('mykernel')((1,),(1,),())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cupy\_core\raw.pyx", line 487, in cupy._core.raw.RawModule.get_function
  File "cupy\_core\raw.pyx", line 100, in cupy._core.raw.RawKernel.kernel.__get__
  File "cupy\_core\raw.pyx", line 117, in cupy._core.raw.RawKernel._kernel
  File "cupy\_util.pyx", line 64, in cupy._util.memoize.decorator.ret
  File "cupy\_core\raw.pyx", line 538, in cupy._core.raw._get_raw_module
  File "cupy\_core\core.pyx", line 2236, in cupy._core.core.compile_with_cache
  File "cupy\_core\core.pyx", line 2254, in cupy._core.core.compile_with_cache
  File "C:\Users\mrakg\AppData\Local\Programs\Python\Python311\Lib\site-packages\cupy\cuda\compiler.py", line 484, in _compile_module_with_cache
    return _compile_with_cache_cuda(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrakg\AppData\Local\Programs\Python\Python311\Lib\site-packages\cupy\cuda\compiler.py", line 577, in _compile_with_cache_cuda
    cubin = compile_using_nvcc(source, options, arch,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrakg\AppData\Local\Programs\Python\Python311\Lib\site-packages\cupy\cuda\compiler.py", line 373, in compile_using_nvcc
    raise cex
cupy.cuda.compiler.CompileException: `nvcc` command returns non-zero exit status.
command: ['C:\\Program', 'Files\\NVIDIA', 'GPU', 'Computing', 'Toolkit\\CUDA\\v12.3\\bin\\nvcc.EXE', '-gencode=arch=compute_89,code=sm_89', '--cubin', '-IC:\\Users\\mrakg\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\cupy\\_core\\include/cupy/_cccl/cub', '-IC:\\Users\\mrakg\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\cupy\\_core\\include/cupy/_cccl/thrust', '-IC:\\Users\\mrakg\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\cupy\\_core\\include/cupy/_cccl/libcudacxx', '--std=c++11', '-IC:\\Users\\mrakg\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\cupy\\_core\\include', '-IC:\\Users\\mrakg\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\cupy\\_core\\include\\cupy\\_cuda\\cuda-12', '-IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.3\\include', '-ftz=true', 'C:\\Users\\mrakg\\AppData\\Local\\Temp\\tmpjfexj258\\30f657ba69f45ef40c27faa24896d8ef25928800.cu']
return-code: 1
stdout/stderr:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\include\cuda_bf16.hpp(260): error: no instance of overloaded function "__half::__half" matches the specified type
  __declspec(__host__) __declspec(__device__) __forceinline __half::__half(const __nv_bfloat16 f)
                                                                    ^

1 error detected in the compilation of "C:/Users/mrakg/AppData/Local/Temp/tmpjfexj258/30f657ba69f45ef40c27faa24896d8ef25928800.cu".
nvcc warning : The -std=c++11 flag is not supported with the configured host compiler. Flag will be ignored.
30f657ba69f45ef40c27faa24896d8ef25928800.cu

PS D:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests> python -c "import cupy; cupy.show_config()"
OS                           : Windows-10-10.0.22631-SP0
Python Version               : 3.11.6
CuPy Version                 : 13.0.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.26.1
SciPy Version                : None
Cython Build Version         : 0.29.36
Cython Runtime Version       : None
CUDA Root                    : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3
nvcc PATH                    : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\bin\nvcc.EXE
CUDA Build Version           : 12020
CUDA Driver Version          : 12030
CUDA Runtime Version         : 12020 (linked to CuPy) / 12030 (locally installed)
cuBLAS Version               : (available)
cuFFT Version                : 11012
cuRAND Version               : 10304
cuSOLVER Version             : (11, 5, 4)
cuSPARSE Version             : (available)
NVRTC Version                : (12, 3)
Thrust Version               : 200200
CUB Build Version            : 200200
Jitify Build Version         : b0269c8
cuDNN Build Version          : (not loaded; try `import cupy.cuda.cudnn` first)
cuDNN Version                : (not loaded; try `import cupy.cuda.cudnn` first)
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 4060
Device 0 Compute Capability  : 89
Device 0 PCI Bus ID          : 0000:01:00.0
```

**Comment by mrakgr** [comment] 2024-01-31 12:25
For the WSL issue, I can verify that I used CuPy 13.

```
mrakgr@Lain:~$ python3 -c "import cupy; cupy.show_config()"
OS                           : Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python Version               : 3.10.12
CuPy Version                 : 13.0.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.26.3
SciPy Version                : None
Cython Build Version         : 0.29.36
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 12020
CUDA Driver Version          : 12030
CUDA Runtime Version         : 12020 (linked to CuPy) / 12030 (locally installed)
cuBLAS Version               : (available)
cuFFT Version                : 11012
cuRAND Version               : 10304
cuSOLVER Version             : (11, 5, 4)
cuSPARSE Version             : (available)
NVRTC Version                : (12, 3)
Thrust Version               : 200200
CUB Build Version            : 200200
Jitify Build Version         : <unknown>
cuDNN Build Version          : (not loaded; try `import cupy.cuda.cudnn` first)
cuDNN Version                : (not loaded; try `import cupy.cuda.cudnn` first)
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 4060
Device 0 Compute Capability  : 89
Device 0 PCI Bus ID          : 0000:01:00.0
```

**Comment by leofang** [comment] 2024-02-02 17:16
@mrakgr It's a lot to unpack. I can reproduce your original issue on Linux + CUDA 12.2.2. It doesn't matter if I use NVCC or NVRTC as the backend, both fail. 

The reason is that CuPy bundles the fp16 headers and they are used, and those headers were from CUDA 12.1, last time I checked: https://github.com/cupy/cupy/pull/7758 (cc: @kmaehashi).  But the `mma.h` header that you used includes `crt/mma.h`, which includes both fp16 and bf16 headers, the latter of which can only be found in a local CTK installation (in your case, `/usr/local/cuda` which is CUDA 12.2). These days, the numerical headers are getting more tightly coupled, so it's a problem of header version mismatch (fp16 from 12.1 vs bf16 from 12.2).

There is no proper solution as the bf16 headers are not yet redistributable and so CuPy can't bundle them (nvbugs 3641496; see also https://github.com/NVIDIA/cub/issues/478). A valid workaround is to rely on the hack introduced by the CUDA math API team, by passing
```
options=('-D__CUDA_NO_HALF_CONVERSIONS__',)
```
to `cp.RawModule`. This will break the coupling between fp16 and bf16. As long as you don't need the conversion constructor, it should be fine.

I haven't had a chance to check out your later `wmma` issue. You might want to make it a separate issue.

**Comment by mrakgr** [comment] 2024-02-02 20:58
> It doesn't matter if I use NVCC or NVRTC as the backend, both fail.

NVRTC has been working for me, so I switched to using it entirely. Why does it not work for you?

**Comment by leofang** [comment] 2024-02-02 21:33
> Why does it not work for you?

I think it's because I am using NVRTC 12.2, and yours is 12.3. Starting 12.3, fp16/bf16 headers are hard-wired into NVRTC:
https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-compilers-new-features
>> Moved cuda_fp16.h and cuda_bf16.h into compiler bitcode.

but this is not done for NVCC (consulted with our compiler team), so NVCC users will still hit this error, with the same root cause (header version mismatch) as I noted above.

Since this is resolved, let me close the issue. (FYI, someone will update in the other ticket that you filed: nvbugs 4475937)

**Closed by leofang** 2024-02-02 21:33 UTC
Labels: issue-checked
