### ISSUE TITLE
[Feature Request] Build cupy wheels for aarch64

### ISSUE THREAD

**Issue by eldaromer** [cupy/cupy#4541] opened 2021-01-12 02:33 UTC
Recently I've been doing a lot of work using the Jetson Nano, specifically with [cuSignal](https://github.com/rapidsai/cusignal).
Part of the process of setting up cuSignal is installing cupy via pip. Since there are no wheels available for this architecture, it can take upwards of half an hour to build the wheels on the device.

If your team could add wheels that support the Jetson family of products (as well as ARM processors in general) to the pypi repository, I'm sure it would be a great help to many people using embedded GPU devices.

Thank you

**Comment by leofang** [comment] 2021-01-12 02:55
Context: https://github.com/rapidsai/cusignal/issues/304

**Comment by emcastillo** [comment] 2021-01-12 04:38
Duplicate of #3196?

**Comment by kmaehashi** [comment] 2021-01-13 08:33
Closing as duplicate of #3196.

**Closed by kmaehashi** 2021-01-13 08:33 UTC
Labels: issue-checked
