### ISSUE TITLE
Very slow product for sparse matrices

### ISSUE THREAD

**Issue by eguidotti** [cupy/cupy#6463] opened 2022-02-14 23:18 UTC
### Description

Matrix product seems very slow for sparse matrices. I'm using 2 sparse matrices with 99.9% and 95% null entries. I compute the product between the matrices as follows:

- sparse matrix product -> 0.04 seconds
- convert to dense and compute the product -> ~0.00008 seconds~ See https://github.com/cupy/cupy/issues/6463#issuecomment-1048656629

As the matrices are highly sparse, I'd expect the sparse product to be faster, and definitely not ~500 times~ slower than the corresponding dense product. I've tried with cupy installed from wheel, and then from source. I've used both `cuSPARSELt` 0.1.0 and 0.2.0. I've timed with both `timeit` and cupy `benchmark` profiler. The results I get are always the same. 

Any hint would be much appreciated! Thanks for your help!

### To Reproduce

```py
import cupy
from sklearn.datasets import fetch_20newsgroups
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction.text import TfidfVectorizer


news = fetch_20newsgroups(subset='train')

x = TfidfVectorizer().fit_transform(news.data)
y = OneHotEncoder().fit_transform(news.target.reshape(-1, 1)).T

x_sparse = cupy.sparse.csr_matrix(x)
y_sparse = cupy.sparse.csr_matrix(y)
    
x_dense = x_sparse.todense()
y_dense = y_sparse.todense()

n_repeat = 10

def prod(x, y):
    y @ x

from cupyx.profiler import benchmark
print(benchmark(prod, (x_sparse, y_sparse), n_repeat=n_repeat))
print(benchmark(prod, (x_dense, y_dense), n_repeat=n_repeat))

from timeit import timeit
print(timeit(lambda: prod(x_sparse, y_sparse), number=n_repeat) / n_repeat)
print(timeit(lambda: prod(x_dense, y_dense), number=n_repeat) / n_repeat)

```

### Installation

Source (`pip install cupy`)

### Environment

```
OS                           : Linux-3.10.0-1160.53.1.el7.x86_64-x86_64-with-glibc2.17
Python Version               : 3.8.12
CuPy Version                 : 10.1.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.21.2
SciPy Version                : 1.6.2
Cython Build Version         : 0.29.27
Cython Runtime Version       : 0.29.27
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc --compiler-bindir gcc
CUDA Build Version           : 11050
CUDA Driver Version          : 11050
CUDA Runtime Version         : 11050
cuBLAS Version               : (available)
cuFFT Version                : 10600
cuRAND Version               : 10207
cuSOLVER Version             : (11, 3, 2)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 5)
Thrust Version               : 101301
CUB Build Version            : 101301
Jitify Build Version         : <unknown>
cuDNN Build Version          : 8302
cuDNN Version                : 8302
NCCL Build Version           : 21104
NCCL Runtime Version         : 21104
cuTENSOR Version             : 10400
cuSPARSELt Build Version     : 100
Device 0 Name                : NVIDIA A100-SXM4-40GB
Device 0 Compute Capability  : 80
Device 0 PCI Bus ID          : 0000:00:04.0
```

**Comment by emcastillo** [comment] 2022-02-15 01:29
What are the sizes of the matrices? If the number of non-null entries is not big enough, you will not see any benefit.

**Comment by anaruse** [comment] 2022-02-23 10:49
Hi @eguidotti 

I ran your reproducer on a V100 GPU and got the following results.

> prod                :    CPU:14013.300 us   +/- 9.235 (min:13997.990 / max:14027.839) us     **GPU-0:40940.442 us**   +/-12.410 (min:40923.138 / max:40967.167) us
prod                :    CPU:   33.642 us   +/- 3.235 (min:   31.219 / max:   42.260) us     **GPU-0:30652.928 us**   +/- 5.538 (min:30643.200 / max:30659.584) us
0.03822545510047348
2.949680056190118e-05

It looks like you compared CPU time, but in this case I think it is better to compare GPU time. In GPU time, it is 409 ms for sparse matrices and 306 ms for dense matrices. It is still slower to prod with sparse matrices, though.

**Comment by eguidotti** [comment] 2022-02-23 15:58
Hi @anaruse, thanks for checking this out!

Mmm... it seems to me that the GPU times are 40.9 and 30.6 ms (not 409 and 306 ms)?

In any case, I still cannot understand why the CPU time is so large for sparse matrices. Maybe the data are being copied across CPU/GPU when they should't? Do you have some hints about the high CPU time? Many thanks!

**Comment by anaruse** [comment] 2022-02-24 00:56
> Mmm... it seems to me that the GPU times are 40.9 and 30.6 ms (not 409 and 306 ms)?

Oh, I made a mistake, yes it's 40.9 and 30.6 ms 😓 

> In any case, I still cannot understand why the CPU time is so large for sparse matrices. Maybe the data are being copied across CPU/GPU when they should't? Do you have some hints about the high CPU time? Many thanks!

The multiplication of sparse matrices and sparse matrices is a tricky one. The results of the calculation will also be a sparse matrix, but where the matrix elements become non-zero and how many non-zero elements there are depends on the sparsity pattern of the two input sparse matrices. So, it requires at least two steps of calculation, first to determine the sparsity pattern of the output matrix from the sparsity pattern of the two input matrices, and then to do the actual multiplication.

The apparent longer CPU time in the case of sparse matrices is due to the fact that there are operations to be performed on the CPU that depend on the results of the 1st step above, so it is "waiting" on CPU for the 1st step on GPU to complete.

In the case of sparse matrix and sparse matrix multiplication, CuPy currently uses cuSPARSE, more specifically [cusparse*csrgemm2()](https://docs.nvidia.com/cuda/cusparse/index.html#csrgemm2). This function is deprecated and it is recommended to use [cusparseSpGEMM()](https://docs.nvidia.com/cuda/cusparse/index.html#cusparse-generic-function-spgemm) instead. Recent performance improvements have not been reflected in the former, so there is a possibility of speedup using the latter.

**Comment by eguidotti** [comment] 2022-02-24 08:54
Thanks @anaruse, this is very instructive! As far as I understand, the product between 2 sparse matrices is slow by design and cannot be fully accelerated in GPU (as step 1 requires CPU in any case). Moreover, I apologize for my mistake, as the 0.00008 seconds I reported for dense matrices are only the CPU time (while I wanted to measure the total execution time)! So the difference between sparse and dense product is much more limited as you write. 

I fixed the issue by converting the smaller matrix to dense and then computing the sparse x dense product. This is very fast! 

```py
import cupy
from sklearn.datasets import fetch_20newsgroups
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction.text import TfidfVectorizer


news = fetch_20newsgroups(subset='train')

x = TfidfVectorizer().fit_transform(news.data)
y = OneHotEncoder().fit_transform(news.target.reshape(-1, 1)).T

x_sparse = cupy.sparse.csr_matrix(x)
y_sparse = cupy.sparse.csr_matrix(y)
    
x_dense = x_sparse.todense()
y_dense = y_sparse.todense()

n_repeat = 10

gpu = cupy.cuda.Device()
def prod(x, y):
    y @ x
    gpu.synchronize()

from cupyx.profiler import benchmark
print(benchmark(prod, (x_sparse, y_sparse), n_repeat=n_repeat))
print(benchmark(prod, (x_dense, y_dense), n_repeat=n_repeat))
print(benchmark(prod, (x_sparse, y_dense), n_repeat=n_repeat))

from timeit import timeit
print(timeit(lambda: prod(x_sparse, y_sparse), number=n_repeat) / n_repeat)
print(timeit(lambda: prod(x_dense, y_dense), number=n_repeat) / n_repeat)
print(timeit(lambda: prod(x_sparse, y_dense), number=n_repeat) / n_repeat)
```

The code gives me:

```
prod                :    CPU:40076.574 us   +/-90.047 (min:40009.927 / max:40275.212) us     GPU-0:40093.287 us   +/-95.057 (min:40027.138 / max:40309.761) us
prod                :    CPU: 9666.914 us   +/- 6.224 (min: 9658.466 / max: 9680.959) us     GPU-0: 9674.138 us   +/- 6.749 (min: 9665.536 / max: 9688.064) us
prod                :    CPU:  836.961 us   +/-13.256 (min:  815.577 / max:  856.658) us     GPU-0:  843.776 us   +/-13.280 (min:  822.272 / max:  864.256) us

0.04023652070000026  # Total time: sparse x sparse
0.009680339499999491 # Total time: dense  x dense
0.000885322599998517 # Total time: sparse x dense
```

**Comment by emcastillo** [comment] 2022-02-25 07:06
Thanks a lot for this nice analysis and insights, I think that everyone can learn a bit from this discussion :).

Let me close it as it seems resolved!

**Closed by emcastillo** 2022-02-25 07:06 UTC
Labels: issue-checked
