### ISSUE TITLE
Exception ignored in: 'cupy_backends.cuda.api.runtime.createTextureObject'

### ISSUE THREAD

**Issue by kalvdans** [cupy/cupy#7533] opened 2023-04-24 12:24 UTC
### Description

Creating a texture fails sometimes, but the cuda error is not converted into a Python exception.

### To Reproduce

```py
import cupy as cp

def create_empty_texture(sz, sy, sx):
    channel_desc = cp.cuda.texture.ChannelFormatDescriptor(
        32, 32, 0, 0, cp.cuda.runtime.cudaChannelFormatKindFloat
    )
    cuda_array_d = cp.cuda.texture.CUDAarray(channel_desc, sx, sy, sz)
    res_desc = cp.cuda.texture.ResourceDescriptor(cp.cuda.runtime.cudaResourceTypeArray, cuArr=cuda_array_d)
    tex_desc = cp.cuda.texture.TextureDescriptor(
        addressModes=(
            cp.cuda.runtime.cudaAddressModeBorder,
            cp.cuda.runtime.cudaAddressModeBorder,
        ),
    )
    tex = cp.cuda.texture.TextureObject(res_desc, tex_desc)
    return tex, cuda_array_d

print("creating texture...")
create_empty_texture(3, 5, 6)
print("done!")
```

Run this a few times until you get the following output:
```
$ OMP_NUM_THREADS=1 python cupy_texture_illegal.py  
creating texture...
Traceback (most recent call last):
  File "cupy_backends/cuda/api/runtime.pyx", line 143, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorInvalidValue: invalid argument
Exception ignored in: 'cupy_backends.cuda.api.runtime.createTextureObject'
Traceback (most recent call last):
  File "cupy_backends/cuda/api/runtime.pyx", line 143, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorInvalidValue: invalid argument
done!
```

Here you can see that we reach the done printout even if there's an error in createTextureObject(). The OMP_NUM_THREADS=1 disables threads to ease debugging.

### Installation

Wheel (`pip install cupy-***`)

### Environment

```
OS                           : Linux-5.19.0-35-generic-x86_64-with-glibc2.35
Python Version               : 3.10.6
CuPy Version                 : 11.6.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.24.2
SciPy Version                : 1.10.1
Cython Build Version         : 0.29.32
Cython Runtime Version       : 0.29.34
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 11080
CUDA Driver Version          : 12010
CUDA Runtime Version         : 11060
cuBLAS Version               : (available)
cuFFT Version                : 10702
cuRAND Version               : 10209
cuSOLVER Version             : (11, 3, 4)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 6)
Thrust Version               : 101501
CUB Build Version            : 101501
Jitify Build Version         : 4a37de0
cuDNN Build Version          : (not loaded; try `import cupy.cuda.cudnn` first)
cuDNN Version                : (not loaded; try `import cupy.cuda.cudnn` first)
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce MX150
Device 0 Compute Capability  : 61
Device 0 PCI Bus ID          : 0000:01:00.0
```

### Additional Information

The issue is only about error propagation from C to Python, there might be an actual error in the parameters for the texture, but that's not the point of this issue.

**Comment by leofang** [comment] 2023-04-24 14:53
Thanks for reporting, I see where the problem is and I will fix it (@kmaehashi plz assign to me so that I don't drop the ball). That said, your script runs fine on my side...

**Comment by kalvdans** [comment] 2023-04-24 14:58
Thanks @leofang! In the meantime, I tried to fix it myself but I only managed to write a test, take it or leave it!
```diff
diff --git a/tests/cupy_tests/core_tests/test_userkernel.py b/tests/cupy_tests/core_tests/test_userkernel.py
index 9ae24342e..61625ab21 100644
--- a/tests/cupy_tests/core_tests/test_userkernel.py
+++ b/tests/cupy_tests/core_tests/test_userkernel.py
@@ -357,3 +357,35 @@ class TestElementwiseKernelTexture(unittest.TestCase):
         out_arr = ker(*args)
         expected = in_arr + self.data
         testing.assert_allclose(out_arr, expected)
+
+    def test_error_propagation(self):
+        width, height, depth = self.dimensions
+        dim = 3 if depth != 0 else 2 if height != 0 else 1
+
+        # generate input data and allocate output buffer
+        shape = (depth, height, width) if dim == 3 else \
+                (height, width) if dim == 2 else \
+                (width,)
+        self.shape = shape
+
+        # prepare input, output, and texture memory
+        # self.data holds the data stored in the texture memory
+        tex_data = cupy.random.random(shape, dtype=cupy.float32)
+        ch = ChannelFormatDescriptor(32, 0, 0, 0,
+                                     runtime.cudaChannelFormatKindFloat)
+        arr = CUDAarray(ch, width, height, depth)
+        arr.copy_from(tex_data)
+        self.data = tex_data
+
+        # create resource descriptor and incorrect texture descriptor
+        res = ResourceDescriptor(runtime.cudaResourceTypeArray, cuArr=arr)
+        address_mode = (-1,
+                        runtime.cudaAddressModeClamp)
+        tex = TextureDescriptor(address_mode, runtime.cudaFilterModePoint,
+                                runtime.cudaReadModeElementType)
+
+        # create a texture object, checking that we get one exception
+        with pytest.raises(runtime.CUDARuntimeError):
+            TextureObject(res, tex)
+ 
+ 
```

**Closed** 2023-05-16 04:29 UTC
Labels: cat:bug, prio:high
