### ISSUE TITLE
Failed to import CuPy.

### ISSUE THREAD

**Issue by Zhihuihuo** [cupy/cupy#8227] opened 2024-03-07 06:19 UTC
### Description

After installing cupy, the following error occurs when loading cupy:

\>>> import cupy
Traceback (most recent call last):
  File "/home/zhhuo/rl_llm_py_product/venv/lib64/python3.9/site-packages/cupy/__init__.py", line 17, in <module>
    from cupy import _core  # NOQA
  File "/home/zhhuo/rl_llm_py_product/venv/lib64/python3.9/site-packages/cupy/_core/__init__.py", line 3, in <module>
    from cupy._core import core  # NOQA
ImportError: libcudart.so.12: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhhuo/rl_llm_py_product/venv/lib64/python3.9/site-packages/cupy/__init__.py", line 19, in <module>
    raise ImportError(f'''
ImportError:

================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: libcudart.so.12: cannot open shared object file: No such file or directory

### Installation

pip install cupy-cuda12x

### Environment
python: 3.9
cuda version: 12.2
pip list:
cupy-cuda12x：                12.1.0
nvidia-cublas-cu12            12.1.3.1
nvidia-cuda-cupti-cu12        12.1.105
nvidia-cuda-nvrtc-cu12        12.1.105
nvidia-cuda-runtime-cu12      12.1.105
nvidia-cudnn-cu12             8.9.2.26
nvidia-cufft-cu12             11.0.2.54
nvidia-curand-cu12            10.3.2.106
nvidia-cusolver-cu12          11.4.5.107
nvidia-cusparse-cu12          12.1.0.106
nvidia-nccl-cu12              2.18.1
nvidia-nvjitlink-cu12         12.4.99
nvidia-nvtx-cu12              12.1.105

Has anyone encountered this problem and how to solve it? Thanks

**Comment by leofang** [comment] 2024-03-07 16:00
CUDA wheels installed from PyPI are not supported yet. This is a duplicate of #8013. In the meanwhile please follow CuPy's installation guide to set up a working environment. Personally I'd suggest installing from conda-forge.

**Closed** 2024-03-27 16:57 UTC
Labels: issue-checked
