### ISSUE TITLE
Certain calls in cupy/cupyx always require a c++ compiler on Windows despite precompiled kernels.

### ISSUE THREAD

**Issue by dtribose** [cupy/cupy#8380] opened 2024-06-13 23:43 UTC
### Description

When using cupy and/or cupyx a subset of the calls will invoke nvcc, which in turn calls cl.exe. After running my program the necessary precompiled kernel code (*.cubin files) are created and placed in the cupy_cache. If one reruns the same program without changing the inputs or code on the same environment, but somehow disable access to the cl.exe (either changing name, or uninstalling the build tools) the program will fail with a cl.exe error. There does not seem to be a way to exercise this code and call these functions in your code, without having a c++ compiler installed.

### To Reproduce

Run program, assuming C++ build tools are installed and cl.exe is in path
```
import os
import cupy as cp
os.environ['NVCC'] = 'nvcc -allow-unsupported-compiler'  # may not be necessary
os.environ["CUPY_CACHE_DIR"] = r"C:\Users\S\dev\cupy_cache"
arr = cp.random.randint(1, 100, [50, 100, 200])
hist_2d, x_edges, y_edges = cp.histogram2d(arr[0, :, :].ravel(), arr[1, :, :].ravel(), bins=20)
print(x_edges, y_edges)
```
Disable cl.exe, or uninstall build tools.
Run program (it fails, even though can access *.cubin files)

### Installation

Source (`pip install cupy`)

### Environment

```
OS                           : Windows-10-10.0.19045-SP0
Python Version               : 3.8.10
CuPy Version                 : 12.3.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.24.4
SciPy Version                : 1.10.1
Cython Build Version         : 0.29.36
Cython Runtime Version       : None
CUDA Root                    : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
nvcc PATH                    : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc.EXE
CUDA Build Version           : 11080
CUDA Driver Version          : 11080
CUDA Runtime Version         : 11080
cuBLAS Version               : (available)
cuFFT Version                : 10900
cuRAND Version               : 10300
cuSOLVER Version             : (11, 4, 1)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 8)
Thrust Version               : 101501
CUB Build Version            : 101501
Jitify Build Version         : 4a37de0
cuDNN Build Version          : (not loaded; try `import cupy.cuda.cudnn` first)
cuDNN Version                : (not loaded; try `import cupy.cuda.cudnn` first)
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA TITAN RTX
Device 0 Compute Capability  : 75
Device 0 PCI Bus ID          : 0000:AF:00.0
```

**Comment by leofang** [comment] 2024-06-14 00:59
Seems to be a duplicate of #8342. Could you please update to CuPy v13.2.0 (just released yesterday) and retry?

xref: https://github.com/cupy/cupy/issues/8342#issuecomment-2144982382

**Comment by dtribose** [comment] 2024-06-14 17:43
I could not find that version listed on your website, and pip install failed when I used this command:
```
(.venv) PS C:\Users\S\dev\MXanalysis\analysis> pip install cupy-cuda11x==13.2.0
ERROR: Could not find a version that satisfies the requirement cupy-cuda11x==13.2.0 (from versions: 11.0.0, 11.1.0, 11.2.0, 11.3.0, 11.4.0, 11.5.0, 11.6.0, 12.0.0, 12.1.0, 12.2.0, 12.3.0)
ERROR: No matching distribution found for cupy-cuda11x==13.2.0
```
I got a similar message when I tried: cupy-cuda12x==13.2.0

I reinstalled 12.3.0 and then tried to upgrade per your website:
pip install -U cupy
After successfully downloading or confirming all the required tools, it was still building a wheel after 35 minutes so I terminated that process. 
How can I obtain that version?
Thanks, D

**Comment by leofang** [comment] 2024-06-14 18:10
I see you're using Python 3.8. It's no longer supported, hence the wheel resolution failed. The minimal supported version is now Python 3.9.

**Comment by dtribose** [comment] 2024-06-17 22:29
Using the new version of cupy, 13.2.0 - and upgrading my code to work with Python 3.10 - seems to fix the cupy issue. Thanks!

I do have one follow on question: Does cupy now distribute an embedded compiler along with it's J.I.T. infrastructure? From what I can tell 13.2.0 no longer depends on the system having an installed version of C++. I uninstalled my C++ compiler and it still regenerated the same number of '.cubin' files and the final execution time was just as fast on my second run (post jitify compilation).  Thx

**Comment by leofang** [comment] 2024-06-17 23:24
Glad to know it's working for you! 

No, CuPy does not (re-)distribute any compiler. What happened is most likely that the majority of the kernels are (finally!) made compilable by NVRTC during the v13.0.0 update (that [included a new copy of CCCL headers](https://docs.cupy.dev/en/stable/upgrade.html#modernized-cccl-support-and-requirement)). NVRTC, when it's working, should be generally more performant than NVCC since it's in-process compilation. It's shipped as part of the CUDA Toolkit.

A good way to ensure you're JIT'ing new kernels instead of reusing those generated before you updated is to remove the on-disk cache, which is default to this path:
https://github.com/cupy/cupy/blob/cd1c7367b6666597fda0b62960781479c6e26b41/cupy/cuda/compiler.py#L449

**Closed by leofang** 2024-06-17 23:24 UTC
Labels: issue-checked
