### ISSUE TITLE
Feature Request: scipy.sparse.linalg.spsolve

### ISSUE THREAD

**Issue by ma-sadeghi** [cupy/cupy#4359] opened 2020-11-29 05:44 UTC
`cupy` seems to lack a performant direct sparse solver.

**Comment by leofang** [comment] 2020-12-01 04:27
Looks like a dup of #2457, which might have an easy solution as @anaruse pointed out in #4000.

**Comment by kmaehashi** [comment] 2020-12-01 07:33
Closing as duplicate of #2457.

**Closed by kmaehashi** 2020-12-01 07:33 UTC
