### ISSUE TITLE
bug in sparse matrix conversion COO->CSR for some matrices

### ISSUE THREAD

**Issue by grlee77** [cupy/cupy#2005] opened 2019-02-06 16:56 UTC
I am finding that conversion of COO->CSR or CSC does not agree with scipy when the underlying matrix is large (nnz > 50k elements or so). The problem does not seem to occur for small matrices such as those used in the test suite.

* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)

CuPy Version          : 6.0.0b2
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10000
CUDA Driver Version   : 10000
CUDA Runtime Version  : 10000

* Code to reproduce

The data for the example below is ~1MB in size and is available via:
https://drive.google.com/open?id=1BRaTNQoAYJPOjfGyio51OwwmCZdh3vdT

```python
import scipy
import numpy as np
import cupy
import cupyx

data = np.load('/tmp/coo_to_csc_example_100k.npz')

sl = slice(None)
A_cpu = scipy.sparse.coo_matrix((data['data'][sl],
                                 (data['row'][sl], data['col'][sl])))

A_gpu = cupyx.scipy.sparse.coo_matrix(A_cpu)

# this comparison is okay
cupy.testing.assert_allclose(A_gpu.data, A_cpu.data)

# conversion on the GPU does not match for large matrices
A_csr_gpu = A_gpu.tocsr()
A_csr_cpu = A_cpu.tocsr()
cupy.testing.assert_allclose(A_csr_gpu.data,
                             A_csr_cpu.data)

# convert via round-trip to CPU works fine
A_csr_gpu2 = cupyx.scipy.sparse.coo_matrix(A_gpu.get().tocsr())
cupy.testing.assert_allclose(A_csr_gpu2.data,
                             A_csr_cpu.data)
```

And oddly, the data array after conversion does match at the beginning and then has huge mismatches in many of the later elements.  I plot this below:

```python

import matplotlib.pyplot as plt
plt.figure()
plt.plot(A_csc_cpu.data - A_csc_gpu.data.get())
```
![figure_12](https://user-images.githubusercontent.com/6528957/52358509-1e6ad900-2a06-11e9-8826-b4e292cee19c.png)

The input data has values in the range [0, 1.0]. In this example the data is dtype np.float32, but the same thing occurs for float64 as well.

**Comment by grlee77** [comment] 2019-02-06 17:01
Many functions such as `__mul__` first convert to CSR, so this is pretty problematic.

The only workaround I found so far is to transfer to the host, convert via scipy's tocsr() and then transfer back to the GPU, but that is obviously not ideal.

**Comment by grlee77** [comment] 2019-02-06 17:51
I suspect the issue here is that this particular sparse matrix has some duplicate row/col indices (<1% of the total), but they are not necessarily adjacent to each other.

It looks like there is a call to `sum_duplicates` and then a call to `coosort` prior to the conversion, but I think the `sum_duplicates` may not be working as expected for the data ordered as in this example.

**Comment by grlee77** [comment] 2019-02-06 17:59
The checks in the example above pass if the `.npz` file is replaced by the dictionary below, so it is more an issue of repeated entries than the overall size, I think.

```python
data = dict(data=np.arange(100000.), row=np.arange(100000, dtype=np.int32), col=np.arange(100000, dtype=np.int32))
```

**Comment by grlee77** [comment] 2019-02-06 18:35
Changing the following line:

https://github.com/cupy/cupy/blob/8f21345941522a89ac2d71d9357f2d0296489d38/cupyx/scipy/sparse/coo.py#L217

to swap the order of the keys passed to `lexsort`
```python
keys = cupy.stack([self.col, self.row])
```
fixes the bug for this matrix. The existing sparse tests all still pass after the change as well.

`lexsort` places higher priority on the **last** entry in the sort keys, so if the original intent was to sort by rows it seems the modified code should do that. Does this seem like the correct fix?

**Comment by grlee77** [comment] 2019-02-06 19:00
Although the key order swap above seems to fix the COO->CSR conversion, it does cause the COO comparison to fail if `sum_duplicates` has been called. This is because the current CuPy code (not the proposed change above) matches the lexsort sort order used by Scipy. 

i.e. running the following with the key order swapped as suggested in the previous comment fails on the COO comparison, but passes on the CSC one. This suggests there is another underlying difference somewhere (perhaps within `coosort`?):
```python
import scipy
import numpy as np
import cupy
import cupyx

data = np.load('/tmp/coo_to_csc_example_100k.npz')

sl = slice(None)

A_cpu = scipy.sparse.coo_matrix((data['data'],
                                 (data['row'], data['col'])))

A_gpu = cupyx.scipy.sparse.coo_matrix(A_cpu)


# manually call sum duplicates prior to the comparison
# this comparison succeeds with the original lexsort key order, but fails
# after the lexsort key order swap
A_cpu.sum_duplicates()
A_gpu.sum_duplicates()
cupy.testing.assert_allclose(A_gpu.data, A_cpu.data)

# However, this comparison now passes after the lexsort key order swap
A_csr_gpu = A_gpu.tocsr()
A_csr_cpu = A_cpu.tocsr()
cupy.testing.assert_allclose(A_csr_gpu.data,
                             A_csr_cpu.data)
```

**Comment by econtal** [comment] 2019-08-16 21:45
It seems the issue is in `coosort` indeed (which is called only by `coo. tocsr()`).

Here is a MVP

```
import numpy
from cupyx.scipy.sparse import coo_matrix

numpy.random.seed(1234)

coo = random(2000,1000,0.01,'coo')
coo_gpu = coo_matrix(coo)

#cusparse.coosort(coo_gpu)  # uncomment this line

coo2 = coo_gpu.get()  # back to CPU

argsort = numpy.lexsort((coo.col, coo.row))
argsort2 = numpy.lexsort((coo2.col, coo2.row))

assert numpy.allclose(coo.data[argsort], coo2.data[argsort2])  # fail if you uncomment coosort
```

**Comment by econtal** [comment] 2019-08-16 22:11
I believe the issue is that `x.data` is used both as input and output of CuSPARSE's `gthr` here: https://github.com/cupy/cupy/blob/d0dd06d5145f73da4c56d8678ddf64cea702106a/cupy/cusparse.py#L583

This can be fixed by creating another buffer. I will submit a PR!

**Closed** 2019-09-24 06:28 UTC
