### ISSUE TITLE
FFT does not use current stream context

### ISSUE THREAD

**Issue by carterbox** [cupy/cupy#7928] opened 2023-10-12 23:06 UTC
### Description

When using `cupy.fft` within a Stream context, the Stream is not respected, and some Host to Device transfers happen on the default Stream.

For example, in code below, two non-default streams (15, 16) are created, and one of these streams is immediately set as the context. However, when looking at the timeline using NVIDIA Nsight, multiple host to device transfers occur outside of these two streams. There should be no activity on Default Stream 7 in this example.

![Screenshot from 2023-10-12 17-47-51](https://github.com/cupy/cupy/assets/9604511/eda29f39-24de-4c1b-a7e6-71d1b622a216)

I believe this issue is related to FFTPlan creation because disabling the plan cache causes additional communications (more than 3) on this Default Stream.

### To Reproduce

```py
import typing

import numpy.typing as npt
import numpy as np
import cupy as cp
import cupyx
from cupyx.profiler import time_range

@time_range()
def test_stream_cupy_fft(dtype=np.double, num_streams=2, w=128, jobs=5):
    rng = np.random.default_rng()
    streams = [cp.cuda.Stream() for _ in range(num_streams)]
    streams[0].use()

    x0 = cupyx.empty_pinned(shape=(num_streams * jobs, 128, w, w), dtype=dtype)
    rng.random(size=x0.shape, out=x0)
    y0 = cp.empty((num_streams, 128, w, w), dtype=x0.dtype)

    for i in range(num_streams * jobs):
        s = i % num_streams
        with streams[s]:
            y0[s].set(x0[i])
            y0[s] = cp.fft.ifft2(cp.fft.fft2(y0[s])).real```

if __name__ == '__main__':
    test_stream_cupy_fft()
```

### Installation

Conda-Forge (`conda install ...`)

### Environment

```
OS                           : Linux-5.14.0-284.18.1.el9_2.x86_64-x86_64-with-glibc2.34
Python Version               : 3.11.6
CuPy Version                 : 12.2.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.26.0
SciPy Version                : 1.11.3
Cython Build Version         : 0.29.36
Cython Runtime Version       : None
CUDA Root                    : /home/beams/DCHING/miniconda3/envs/tike-profile
nvcc PATH                    : None
CUDA Build Version           : 12000
CUDA Driver Version          : 12000
CUDA Runtime Version         : 12000
cuBLAS Version               : (available)
cuFFT Version                : 11000
cuRAND Version               : 10301
cuSOLVER Version             : (11, 4, 2)
cuSPARSE Version             : (available)
NVRTC Version                : (12, 2)
Thrust Version               : 200001
CUB Build Version            : 200001
Jitify Build Version         : 3e2f16d
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 2080 Ti
Device 0 Compute Capability  : 75
Device 0 PCI Bus ID          : 0000:1B:00.0
Device 1 Name                : NVIDIA GeForce RTX 2080 Ti
Device 1 Compute Capability  : 75
Device 1 PCI Bus ID          : 0000:1C:00.0
Device 2 Name                : NVIDIA GeForce RTX 2080 Ti
Device 2 Compute Capability  : 75
Device 2 PCI Bus ID          : 0000:1D:00.0
Device 3 Name                : NVIDIA GeForce RTX 2080 Ti
Device 3 Compute Capability  : 75
Device 3 PCI Bus ID          : 0000:1E:00.0
Device 4 Name                : NVIDIA GeForce RTX 2080 Ti
Device 4 Compute Capability  : 75
Device 4 PCI Bus ID          : 0000:3D:00.0
Device 5 Name                : NVIDIA GeForce RTX 2080 Ti
Device 5 Compute Capability  : 75
Device 5 PCI Bus ID          : 0000:3F:00.0
Device 6 Name                : NVIDIA GeForce RTX 2080 Ti
Device 6 Compute Capability  : 75
Device 6 PCI Bus ID          : 0000:40:00.0
Device 7 Name                : NVIDIA GeForce RTX 2080 Ti
Device 7 Compute Capability  : 75
Device 7 PCI Bus ID          : 0000:41:00.0```
```

**Comment by leofang** [comment] 2023-10-13 01:57
Another puzzle is you used pinned memory, but the H2D copies say "pageable". Something is weird here, though may not be relevant.

**Comment by carterbox** [comment] 2023-10-13 16:01
For clarity, yes, the actual FFT computation is occurring in the correct stream context. This issue is about the host to device transfers occurring on the default stream before the FFT computation. Because these transfers occur in the default stream, they may cause synchronization issues in a more complex program?

![Screenshot from 2023-10-13 10-57-31](https://github.com/cupy/cupy/assets/9604511/63c8d932-3689-4a0d-be33-864c4f024b6e)

**Comment by leofang** [comment] 2023-10-13 20:40
Update: Confirmed via nsys that it's due to `cufftMakePlanMany`.

**Comment by carterbox** [comment] 2023-10-14 17:14
If there's already an idea of how to mitigate this issue, and I can be provided with some guidance. I'd be happy to try developing a PR.

**Comment by kmaehashi** [comment] 2023-10-16 02:47
@leofang Should we call `cufftSetStream` before `cufftMakePlanMany`?
https://github.com/cupy/cupy/blob/8ddb02d9f75f22ba0b17b83545124aed4d11d2ec/cupy/cuda/cufft.pyx#L785-L789

**Comment by leofang** [comment] 2023-10-16 03:38
No. To be clear, when I said it's due to `cufftMakePlanMany`, I was referring to libcufft's internal implementation. 

I did already reach out to the cuFFT team, and without revealing too much my current advice is don't waste your time trying any workarounds, they won't work. 

Let's keep this issue open, and if I have any update I will share.

**Comment by leofang** [comment] 2023-10-16 14:49
(btw, sorry I forgot to say, thank you @carterbox for bringing this to our attention)

**Comment by leofang** [comment] 2024-03-21 22:48
> Let's keep this issue open, and if I have any update I will share.

Tracked in nvbugs 4573129. Since this is not a CuPy bug, let me close this issue.

**Closed by leofang** 2024-03-21 22:48 UTC
Labels: issue-checked
