### ISSUE TITLE
Add CuPy compress

### ISSUE THREAD

**Issue by jakirkham** [cupy/cupy#2224] opened 2019-05-30 15:28 UTC
Would be useful to have an [`compress`]( https://docs.scipy.org/doc/numpy/reference/generated/numpy.compress.html#numpy.compress ) implementation for CuPy arrays.

**Comment by andy6975** [comment] 2019-10-03 21:02
Is this issue still open? I would like to work on this. Thanks!

**Comment by jakirkham** [comment] 2019-10-03 21:13
I think you can just give it a go. Not aware of anyone else working on it. Please let us know if you need anything. 🙂

**Comment by andy6975** [comment] 2019-10-03 21:15
Thank you for the response. If you don't mind, can I ask you for a headstart? I am new to cupy.

**Comment by grlee77** [comment] 2019-10-03 22:23
Implementation can sometimes be tricky because you often need some familiarity with NumPy/C to determine what is going on there and then some familiarity with CUDA/C++ to be able to implement an equivalent function for CuPy.  

In the case of `compress`, you could check whether maybe it can be implemented by adapting an existing function like `_take` as defined in [cupy/core/_routines_indexing.pyx](https://github.com/cupy/cupy/blob/master/cupy/core/_routines_indexing.pyx#L592). (NumPy's compress ultimately calls [PyArray_Compress](https://github.com/numpy/numpy/blob/cacdf265755ffae9d5c07d35fafa3d1366e342b8/numpy/core/src/multiarray/item_selection.c#L1936))

An easier, pure Python route is available in cases where a function can be defined in terms of other functions already implemented in CuPy. In the case of `compress`, it seems like the following the following might work:

```Python
def compress((condition, a, axis=None, out=None):
    # TODO: replace with more efficient kernel-based implementation
    return cupy.take(a, cupy.where(condition)[0], axis, out)
```

This is not computationally optimal as we have to call both `cupy.where` and `cupy.take` instead of just a single underlying CUDA kernel, but it is better than nothing. I think a PR of that sort could potentially be accepted if good tests are added to make sure the functionality matches what is provided in NumPy.

Tests would need to be added to the existing file `tests/cupy_tests/core_tests/test_ndarray_indexing.py`.

**Comment by grlee77** [comment] 2019-10-03 22:39
Hey @rgommers: my prior comment here reminded me of a discussion you started (maybe on numpy-dev?) about what defining certain core functions that are most important within the NumPy API.

It seems like `compress` (and `extract`) is an example of a non-core function that can be implemented purely in terms of other existing NumPy functions (despite having a dedicated C implementation in NumPy itself). I just thought I would ping you in case you are working on tabulating these somewhere.

**Comment by jakirkham** [comment] 2019-10-03 22:41
Is there a good place for us to collect a list of such functions Ralf?

**Comment by grlee77** [comment] 2019-10-04 04:39
>Is there a good place for us to collect a list of such functions Ralf?

I found the prior discussion [here](http://numpy-discussion.10968.n7.nabble.com/defining-a-NumPy-API-standard-td47064.html). Ralf mentioned starting a repo for this at: https://github.com/Quansight-Labs/rnumpy

**Comment by rgommers** [comment] 2019-10-04 14:12
https://github.com/Quansight-Labs/python-api-inspect

> I found the prior discussion [here](http://numpy-discussion.10968.n7.nabble.com/defining-a-NumPy-API-standard-td47064.html). Ralf mentioned starting a repo for this at: https://github.com/Quansight-Labs/rnumpy

Yes, that's the right discussion and repo. I have an 0.0.1 version of `rnumpy` up on [PyPI](https://pypi.org/project/rnumpy/) for easy access, just so people can look at the idea. I haven't had time to push it forward, but hope to have a discussion on this at the NumPy sprint in Berkeley on 22-23 Nov.

The very brief summary here is:
- the NumPy API is way too large and ill-defined, and really needs cleanup/standardization so projects like CuPy can follow that rather than reinvent the wheel or each decide for themselves
- to do so, we need to be able to make informed decisions
- one source of information is actual per-function usage statistics. https://github.com/Quansight-Labs/python-api-inspect helps a lot with this (there's a SQL interface for custom queries on a large set of repos scraped from GitHub, and [numpy-summary.csv](https://github.com/Quansight-Labs/python-api-inspect/blob/master/data/csv/numpy-summary.csv) gives a general overview)
- another source of information would be: what do CuPy, Dask, Xtensor, pydata/sparse, et al. implement? If they all have a function, there seems to be a clear need for it. We don't have the tooling for that yet.

That last question of course only helps if CuPy et al. only implement functions that they and their users have a need for. If they attempt to implement every last random utility function in the main numpy namespace, then that's unhelpful - it just makes cleaning things up harder.



> I just thought I would ping you in case you are working on tabulating these somewhere.

The RNumPy repo would work for now I think. The `rnumpy` namespace contains my personal opinion on things. I also have a spreadsheet somewhere where Travis did the same exercise - that mostly aligned with mine, although of course there were some differences. We need to still do the more structural exercise. Probably will only happen once all/most noses of at least the NumPy maintainers point in the same direction.

**Comment by Harshan01** [comment] 2020-02-20 23:25
I hope the issue is still open. I have made an initial PR for `compress`. #3103 
I would be happy to receive suggestions on improving it.

**Comment by jakirkham** [comment] 2020-02-20 23:34
Yep, it's still open. Thanks for giving this a go Harshan 🙂

**Comment by Harshan01** [comment] 2020-02-25 11:15
The PR is merged. I think this issue can be safely closed.

**Comment by jakirkham** [comment] 2020-02-25 11:18
Thanks @Harshan01! 😀

**Closed** 2020-02-25 11:19 UTC
Labels: cat:feature, contribution-welcome
