### ISSUE TITLE
Normal behaviour or memory leak in fourier_shift?

### ISSUE THREAD

**Issue by MaximilianHoffmann** [cupy/cupy#5199] opened 2021-05-14 15:14 UTC
While using the fourier shift I was observing the following behaviour and I cannot find a way to clear the residual memory.
As far as I see it, I am cleaning everything I have access to, right?
```
import cupy as cp
from cupyx.scipy.ndimage import fourier_shift as fourier_shift_g
mempool = cp.get_default_memory_pool()
for ii in range(2):
    print("Before:", mempool.used_bytes())
    a=cp.random.randn(1000,1000)
    print("After First:", mempool.used_bytes())
    a_ft=cp.fft.fftn(a)
    b=cp.fft.ifftn(fourier_shift_g(a_ft,[1,1]))
    print("After Shift:", mempool.used_bytes())
    del a
    del b
    del a_ft
    mempool.free_all_blocks()
    print("After Delete:", mempool.used_bytes())
print(cp.__version__)
```

```
Before: 0
After First: 8000000
After Shift: 56000000
After Delete: 16000000
Before: 16000000
After First: 24000000
After Shift: 56000000
After Delete: 16000000
9.0.0
```

```
OS                           : Windows-10-10.0.19041-SP0
CuPy Version                 : 9.0.0
NumPy Version                : 1.20.2
SciPy Version                : 1.6.3
Cython Build Version         : 0.29.23
Cython Runtime Version       : None
CUDA Root                    : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2
CUDA Build Version           : 11020
CUDA Driver Version          : 11030
CUDA Runtime Version         : 11020
cuBLAS Version               : 11401
cuFFT Version                : 10401
cuRAND Version               : 10203
cuSOLVER Version             : (11, 1, 0)
cuSPARSE Version             : 11401
NVRTC Version                : (11, 2)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce GTX 1080 Ti
Device 0 Compute Capability  : 61
Device 0 PCI Bus ID          : 0000:65:00.0
```

**Comment by leofang** [comment] 2021-05-14 15:57
Hi @MaximilianHoffmann, this is expected behavior I think. A FFT plan cache was added since CuPy v8. It's meant to help reduce the cost of plan creation by reusing them. So if you do
```python
cache = cp.fft.config.get_plan_cache()
cache.show_info()
```
You will see at least 1 plan is cached with your reproducer, and each plan takes some memory as workspace.

To turn off the cache completely (and to clear the cache), you can simply call
```python
cache.set_size(0)
```
You'll see the memory released.

@kmaehashi Please assign this issue to me since I have meant to write up a [documentation for FFT support](https://github.com/cupy/cupy/issues/4902#issuecomment-813205619)...😅

**Comment by MaximilianHoffmann** [comment] 2021-05-14 18:02
```
cache = cp.fft.config.get_plan_cache()
cache.show_info()
cache.clear()
```
Thanks! Cool, I guess, I'll definitely profit from the cache in the original code, so this "fixes" it for me. I didn't read through the cache part of the fft documentation, it's somewhat my fault. Thank you for the help!

**Closed** 2021-05-28 07:26 UTC
Labels: cat:document, prio:medium
