### ISSUE TITLE
CUBLAS_STATUS_EXECUTION_FAILED when running cupy.outer for the first time.

### ISSUE THREAD

**Issue by we-taper** [cupy/cupy#2166] opened 2019-04-30 07:09 UTC
The `cupy.outer` functions raises `cupy.cuda.cublas.CUBLASError: CUBLAS_STATUS_EXECUTION_FAILED` when called the first time. For example:
```python
import cupy
from cupy.cuda.cublas import CUBLASError
vec = cupy.array([[1.0], [1j]], dtype=complex) / cupy.sqrt(2)
try:
    cupy.outer(vec, vec.conj())
except CUBLASError as e:
    print('Encountered: ' + str(e))
    cupy.outer(vec, vec.conj())
    print('The error is not raised again.')
```
Outputs:
```
Encountered: CUBLAS_STATUS_EXECUTION_FAILED
The error is not raised again.
```
Related information:

* Conditions (the output of `python -c 'import cupy; cupy.show_config()'`)
```
CuPy Version          : 5.1.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 9000
CUDA Driver Version   : 10010
CUDA Runtime Version  : 9000
cuDNN Build Version   : 7301
cuDNN Version         : 7301
NCCL Build Version    : 1000
```

**Comment by kmaehashi** [comment] 2019-05-07 10:45
Thanks for reporting an issue.
However I could not reproduce the error with your code using:
```
CuPy Version          : 5.1.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 9000
CUDA Driver Version   : 10010
CUDA Runtime Version  : 9000
cuDNN Build Version   : 7301
cuDNN Version         : 7301
NCCL Build Version    : 1000
```

Could you try:
* using `cupy-cuda90` wheel instead of `cupy`?
* updating to the latest CuPy v5.4.0?

**Comment by we-taper** [comment] 2019-05-08 15:32
> Could you try:
> 
> * using `cupy-cuda90` wheel instead of `cupy`?
> * updating to the latest CuPy v5.4.0?

I am a bit discouraged in this since my packages are managed by `conda` and,
* I guess `conda` should already automatically selected `cupy-cuda90`?
* the latest in `conda` is still `5.1.0`.

But I will try this once `conda`'s version is updated.

**Comment by aanugraha** [comment] 2019-11-14 01:57
I could reproduce the error with:
```
CuPy Version          : 6.5.0
CUDA Root             : /usr
CUDA Build Version    : 9010
CUDA Driver Version   : 10020
CUDA Runtime Version  : 9010
cuDNN Build Version   : 7102
cuDNN Version         : 7102
NCCL Build Version    : 2115
NCCL Runtime Version  : (unknown)
```
Cupy was installed by `pip install cupy-cuda91`.

**Comment by kmaehashi** [comment] 2020-07-20 13:46
Closing as the issue seems out-dated. Please feel free to reopen if the issue persists in the latest release.

**Closed by kmaehashi** 2020-07-20 13:46 UTC
