### ISSUE TITLE
CURAND_STATUS_INITIALIZATION_FAILED

### ISSUE THREAD

**Issue by pawamoy** [cupy/cupy#6277] opened 2021-12-28 15:31 UTC
### Description

Not sure this is actually a bug. We started having this error after a driver upgrade.

```python
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/pythenv/envs/default/lib64/python3.6/site-packages/spacy/__main__.py", line 4, in <module>
    setup_cli()
  File "/opt/pythenv/envs/default/lib64/python3.6/site-packages/spacy/cli/_util.py", line 71, in setup_cli
    command(prog_name=COMMAND)
  File "/opt/pythenv/envs/default/lib64/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/pythenv/envs/default/lib64/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/pythenv/envs/default/lib64/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/pythenv/envs/default/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/pythenv/envs/default/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/pythenv/envs/default/lib64/python3.6/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/pythenv/envs/default/lib64/python3.6/site-packages/spacy/cli/train.py", line 45, in train_cli
    train(config_path, output_path, use_gpu=use_gpu, overrides=overrides)
  File "/opt/pythenv/envs/default/lib64/python3.6/site-packages/spacy/cli/train.py", line 72, in train
    nlp = init_nlp(config, use_gpu=use_gpu)
  File "/opt/pythenv/envs/default/lib64/python3.6/site-packages/spacy/training/initialize.py", line 35, in init_nlp
    fix_random_seed(config["training"]["seed"])
  File "/opt/pythenv/envs/default/lib64/python3.6/site-packages/thinc/util.py", line 79, in fix_random_seed
    cupy.random.seed(seed)
  File "/opt/pythenv/envs/default/lib64/python3.6/site-packages/cupy/random/_generator.py", line 1184, in seed
    get_random_state().seed(seed)
  File "/opt/pythenv/envs/default/lib64/python3.6/site-packages/cupy/random/_generator.py", line 1216, in get_random_state
    rs = RandomState(seed)
  File "/opt/pythenv/envs/default/lib64/python3.6/site-packages/cupy/random/_generator.py", line 57, in __init__
    self._generator = curand.createGenerator(method)
  File "cupy_backends/cuda/libs/curand.pyx", line 93, in cupy_backends.cuda.libs.curand.createGenerator
  File "cupy_backends/cuda/libs/curand.pyx", line 97, in cupy_backends.cuda.libs.curand.createGenerator
  File "cupy_backends/cuda/libs/curand.pyx", line 86, in cupy_backends.cuda.libs.curand.check_status
cupy_backends.cuda.libs.curand.CURANDError: CURAND_STATUS_INITIALIZATION_FAILED
```

```console
$ nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.156.00   Driver Version: 450.156.00   CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GRID T4-16C         On   | 00000000:02:01.0 Off |                    0 |
| N/A   N/A    P8    N/A /  N/A |   2220MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

```console
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0
```

Do you have any hint on what could throw this CURAND_STATUS_INITIALIZATION_FAILED error? I'll take anything 😅 
Just for reference and better discoverability: https://github.com/explosion/spaCy/discussions/8273 (though not same use-case, we *do* want to use the GPU).

### To Reproduce

```bash
python -m spacy train config.cfg --output ./res-camembert-base --paths.train ./train.spacy --paths.dev ./dev.spacy --gpu-id 0
```

I guess it won't run on another environment, sorry 😕 
I hope the traceback is enough to get at leat some pointers of what might go wrong.

### Installation

Wheel (`pip install cupy-***`) (probably, it was installed as a dependency of spacy).

### Environment

```console
$ python -c 'import cupy; cupy.show_config()'
OS                           : Linux-3.10.0-1160.25.1.el7.x86_64-x86_64-with-redhat-7.9-Maipo
Python Version               : 3.6.12
CuPy Version                 : 9.6.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.19.5
SciPy Version                : 1.5.4
Cython Build Version         : 0.29.22
Cython Runtime Version       : 0.29.21
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 11000
CUDA Driver Version          : 11000
CUDA Runtime Version         : 11000
cuBLAS Version               : (available)
cuFFT Version                : 10201
cuRAND Version               : 10201
cuSOLVER Version             : (10, 6, 0)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 0)
Thrust Version               : 100909
CUB Build Version            : 100909
Jitify Build Version         : 60e9e72
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : GRID T4-16C
Device 0 Compute Capability  : 75
Device 0 PCI Bus ID          : 0000:02:01.0
```

**Comment by kmaehashi** [comment] 2021-12-29 14:32
Could you try setting `CUPY_GPU_MEMORY_LIMIT=90%` environment variable and see if the problem reproduces?  `CURAND_STATUS_INITIALIZATION_FAILED` is often seen when CuPy memory pool occupies all GPU memory and cuRAND fails to create a handle.

https://docs.cupy.dev/en/latest/user_guide/memory.html#limiting-gpu-memory-usage
xref #5894

**Comment by pawamoy** [comment] 2021-12-30 09:34
Hi @kmaehashi, thanks a lot for your help.
Setting the environment variable didn't work, unfortunately 😕

**Comment by kmaehashi** [comment] 2022-01-04 05:27
Hmm, in that case I guess this is likely a environment-specific issue. I'd suggest try running CUDA example that uses cuRAND (e.g., `7_CUDALibraries/MersenneTwisterGP11213/MersenneTwister.cpp` ) to isolate the issue, and also updating CUDA to the latest 11.5.

**Comment by leofang** [comment] 2022-01-04 15:40
> We started having this error after a driver upgrade.

Just curious, what was the driver version before the upgrade?

**Comment by pawamoy** [comment] 2022-01-05 10:36
We had these versions (in yellow) before the upgrade.

![image](https://user-images.githubusercontent.com/3999221/148203558-1efd7aac-3d34-4b44-9eed-cc2cb9cbcde8.png)

**Comment by leofang** [comment] 2023-01-05 22:02
I feel it's a version mismatch between the installed CuPy and your local CUDA env. From the original bug report it's unclear to me how CUDA and CuPy were installed, so not much I can say.

**Comment by sdocio** [comment] 2023-01-12 15:28
> 

Yes, you are right. I tried different combinations and this worked for me.

cupy-cuda116==10.6.0 
spacy==3.4.4 
torch==1.13.1
Cuda compilation tools, release 11.6, V11.6.55
Build cuda_11.6.r11.6/compiler.30794723_0

**Comment by sjg918** [comment] 2024-02-13 10:43
Hello.
This problem still occurs when I initialize the matrix by calling the cp.random.randint() method.
However, this problem was easily solved by initializing it using the np.random.randint() method and sending it to cp using the cp.asarray() mehtod.
I wasted 3 hours trying to solve this problem. I hope that anyone who sees this issue saves their time!

**Comment by leofang** [comment] 2024-02-13 14:03
Guys, please, submit a bug report following the instruction in the issue template. It doesn't help either you or us by just coming and saying "it doesn't work for me either" and not leaving any useful debugging info. In particular,
> However, this problem was easily solved by initializing it using the np.random.randint() method and sending it to cp using the cp.asarray() mehtod.

it makes no sense if things work. We wouldn't advocate any poor workaround without digging into the issue, but to do so we need more information. Something is simply wrong in your environment.

Let me make a judgement call in closing this issue, due to non-response from the OP. Please open a new issue and share your env info with us if you still see this.

**Closed by leofang** 2024-02-13 14:03 UTC
Labels: issue-checked
