### ISSUE TITLE
Remove use of `pkg_resources`

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#7003] opened 2022-08-18 04:19 UTC
Use of `pkg_resources` (part of `setuptools`) is now discouraged.

https://setuptools.pypa.io/en/latest/pkg_resources.html

> Use of pkg_resources is discouraged in favor of [importlib.resources](https://docs.python.org/3/library/importlib.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html), and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). Please consider using those libraries instead of pkg_resources.

**Comment by jakirkham** [comment] 2024-08-05 20:48
This appears to be a duplicate of issue: https://github.com/cupy/cupy/issues/7654

Should we consolidate these somehow?

**Closed** 2024-08-08 09:03 UTC
Labels: cat:enhancement, to-be-backported, prio:medium
