### ISSUE TITLE
Hitting a precision limit in `cupy.sparse.csr_matrix` when using `multiply`.

### ISSUE THREAD

**Issue by christinahedges** [cupy/cupy#5778] opened 2021-09-22 23:19 UTC
I've come across a bug in `cupy.sparse.csr_matrix` which seems to happen only some of the time. I have created a minimally working example below. This example is quite contrived in order to get the error message to happen every time, and the matrix is actually fully sparse. I am coming across the same bug in my research but it doesn't happen consistently, and in those cases I am using a sparse matrix.

In the MWE we create a huge dense matrix, and multiply it by a vector. The `multiply` method is actually turning the `csr_matrix` into a `coo_matrix`. This happens fine for the first iteration, but on a second iteration this breaks with the following error message.

It seems that the `col` array hits the precision limit for an `int32` and then contains values that are extremely large and negative, or extremely large, and this causes the error message. However, the array is not large enough that it should hit that precision limit.

* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
``` 
OS                           : Linux-4.12.14-122.80.1.20210720-nasa-x86_64-with-glibc2.10
Python Version               : 3.8.5
CuPy Version                 : 9.4.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.19.2
SciPy Version                : 1.7.1
Cython Build Version         : 0.29.24
Cython Runtime Version       : None
CUDA Root                    : /home4/jimartin/.conda/envs/gpu_hack
nvcc PATH                    : None
CUDA Build Version           : 11000
CUDA Driver Version          : 11000
CUDA Runtime Version         : 11000
cuBLAS Version               : (available)
cuFFT Version                : 10201
cuRAND Version               : 10201
cuSOLVER Version             : (10, 6, 0)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 0)
Thrust Version               : 100909
CUB Build Version            : 100909
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : Tesla V100-SXM2-32GB
Device 0 Compute Capability  : 70
Device 0 PCI Bus ID         : 0000:16:00.0
```

* Code to reproduce

```python
from cupy import sparse
import cupy as cp

def run():
    A = sparse.csr_matrix(cp.ones((2048**2, 25)))
    return A.multiply(cp.random.normal(size=2048**2)[:, None])
run()
run()
```

* Error messages, stack traces, or logs

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-ec9775ede022> in <module>
----> 1 run()

<ipython-input-1-1d6522e0f920> in run()
      4 def run():
      5     A = sparse.csr_matrix(cp.ones((2048**2, 25)))
----> 6     return A.multiply(cp.random.normal(size=2048**2)[:, None])

~/.conda/envs/gpu_hack/lib/python3.8/site-packages/cupyx/scipy/sparse/csr.py in multiply(self, other)
    321             return multiply_by_scalar(self, other)
    322         elif _util.isdense(other):
--> 323             self.sum_duplicates()
    324             other = cupy.atleast_2d(other)
    325             return multiply_by_dense(self, other)

~/.conda/envs/gpu_hack/lib/python3.8/site-packages/cupyx/scipy/sparse/compressed.py in sum_duplicates(self)
    776         # TODO(leofang): add a kernel for compressed sparse matrices without
    777         # converting to coo
--> 778         coo = self.tocoo()
    779         coo.sum_duplicates()
    780         self.__init__(coo.asformat(self.format))

~/.conda/envs/gpu_hack/lib/python3.8/site-packages/cupyx/scipy/sparse/csr.py in tocoo(self, copy)
    436             indices = self.indices
    437 
--> 438         return cusparse.csr2coo(self, data, indices)
    439 
    440     def tocsc(self, copy=False):

~/.conda/envs/gpu_hack/lib/python3.8/site-packages/cupy/cusparse.py in csr2coo(x, data, indices)
    928         _cusparse.CUSPARSE_INDEX_BASE_ZERO)
    929     # data and indices did not need to be copied already
--> 930     return cupyx.scipy.sparse.coo_matrix(
    931         (data, (row, indices)), shape=x.shape)
    932 

~/.conda/envs/gpu_hack/lib/python3.8/site-packages/cupyx/scipy/sparse/coo.py in __init__(self, arg1, shape, dtype, copy)
    157                 raise ValueError('row index exceeds matrix dimensions')
    158             if col.max() >= shape[1]:
--> 159                 raise ValueError('column index exceeds matrix dimensions')
    160             if row.min() < 0:
    161                 raise ValueError('negative row index found')

ValueError: column index exceeds matrix dimensions
```

**Comment by pentschev** [comment] 2021-09-23 18:52
I believe this is a duplicate of https://github.com/cupy/cupy/issues/3513 . Could you confirm this is the same issue and we don't still have a solution for that @leofang @takagi ?

**Comment by leofang** [comment] 2021-09-23 19:06
No, unfortunately I didn't have the bandwidth to work on a fix. I believe it's still an open issue.

**Comment by pentschev** [comment] 2021-09-23 19:33
Actually I think it's my mistake. It isn't the same issue, I probably mixed things up. However, I executed `run()` in a loop for 10k times and wasn't able to reproduce the issue, from the example in the description it seems like it should fail much more frequently, could you confirm that @christinahedges ?

For reference, this is CuPy's info on my side:

```
$ python -c 'import cupy; cupy.show_config()'
OS                           : Linux-4.15.0-76-generic-x86_64-with-glibc2.10
Python Version               : 3.8.12
CuPy Version                 : 9.4.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.21.2
SciPy Version                : None
Cython Build Version         : 0.29.24
Cython Runtime Version       : 0.29.24
CUDA Root                    : /datasets/pentschev/miniconda3/envs/ucx-111-112-21.10.210921
nvcc PATH                    : None
CUDA Build Version           : 11020
CUDA Driver Version          : 11020
CUDA Runtime Version         : 11020
cuBLAS Version               : (available)
cuFFT Version                : 10400
cuRAND Version               : 10203
cuSOLVER Version             : (11, 0, 2)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 2)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : Tesla V100-SXM2-32GB
Device 0 Compute Capability  : 70
Device 0 PCI Bus ID          : 0000:06:00.0
Device 1 Name                : Tesla V100-SXM2-32GB
Device 1 Compute Capability  : 70
Device 1 PCI Bus ID          : 0000:07:00.0
Device 2 Name                : Tesla V100-SXM2-32GB
Device 2 Compute Capability  : 70
Device 2 PCI Bus ID          : 0000:0A:00.0
Device 3 Name                : Tesla V100-SXM2-32GB
Device 3 Compute Capability  : 70
Device 3 PCI Bus ID          : 0000:0B:00.0
Device 4 Name                : Tesla V100-SXM2-32GB
Device 4 Compute Capability  : 70
Device 4 PCI Bus ID          : 0000:85:00.0
Device 5 Name                : Tesla V100-SXM2-32GB
Device 5 Compute Capability  : 70
Device 5 PCI Bus ID          : 0000:86:00.0
Device 6 Name                : Tesla V100-SXM2-32GB
Device 6 Compute Capability  : 70
Device 6 PCI Bus ID          : 0000:89:00.0
Device 7 Name                : Tesla V100-SXM2-32GB
Device 7 Compute Capability  : 70
Device 7 PCI Bus ID          : 0000:8A:00.0
```

It's possible this is a bug that was fixed sometime after CUDA 11.0, since I'm running 11.2. If you believe this is an issue that should be reproducible in fewer than 10k iterations, would it be possible for you to try and match the versions I'm running above to see if the issue is resolved?

**Comment by takagi** [comment] 2021-11-26 08:24
I've confirmed that `cupy-cuda110==9.4.0` and `cupy-cuda111==9.4.0` reproduce the error, while `cupy-cuda112==9.4.0` doesn't.

**Comment by pentschev** [comment] 2021-11-29 15:02
That's interesting, so it may have been a CUDA bug prior to 11.2. Would you be able to test somewhere with CUDA 11.2 @christinahedges ?

**Comment by christinahedges** [comment] 2021-11-29 17:49
Hi all thanks for getting back to me about this. It will take me a while to get this tested on 11.2 (I run CUDA on a remote computer and need to check my permissions to update CUDA and get the right version). @dmargala was our mentor on our CUDA project. @dmargala, are you able to run this check on CUDA 11.2?

**Comment by dmargala** [comment] 2021-12-10 22:23
@christinahedges I tested the example code on the Perlmutter system at NERSC using the cudatoolkit modules available on that system. I can confirm this fails in 11.0 and seems to work starting in 11.2 (there does not seem to be a cudatoolkit module compatible with 11.1).

|cudatoolkit module | cupy package | result|
|-|-|-|
|cudatoolkit/21.3_11.0| cupy-cuda110==9.4.0 | fail|
|cudatoolkit/21.3_11.2| cupy-cuda112==9.4.0 | pass|
|cudatoolkit/21.9_11.0| cupy-cuda110==9.4.0 | fail|
|cudatoolkit/21.9_11.4| cupy-cuda112==9.4.0 | pass|
|cudatoolkit/21.9_11.4| cupy-cuda113==9.4.0 | pass|
|cudatoolkit/21.9_11.4| cupy-cuda114==9.4.0 | pass|

**Comment by christinahedges** [comment] 2021-12-13 17:57
Thanks @dmargala that looks fantastic!

**Comment by takagi** [comment] 2022-03-10 03:49
Let me close this issue as it seems to work on newer CTK. Feel free to reopen if anything happens again.

**Closed by takagi** 2022-03-10 03:49 UTC
Labels: cat:bug, st:awaiting-author, prio:high
