### ISSUE TITLE
`AssertFunctionIsCalled` fails to unpatch target

### ISSUE THREAD

**Issue by toslunar** [cupy/cupy#4232] opened 2020-11-06 07:22 UTC
`AssertFunctionIsCalled` does not exit `mock.patch` if the assertion fails:
https://github.com/cupy/cupy/blob/c0c99108b78f4480b17cdf22ba3e903eb65f3646/cupy/testing/helper.py#L1441-L1444

As a consequence, CI reports weird failures.

Example: https://jenkins.preferred.jp/job/chainer/job/daily_master_cupy-shuffled/378/ID=20,label=mn1-p100/consoleFull

- The first failure is `TestCubReduction_param_5_{backend='device', order='F', shape=(10, 20)}.test_cub_max` on `assert self.handle.call_count == int(self.times_called)` in `AssertFunctionIsCalled.__exit__`.
- The second failure is `TestCubReduction_param_5_{backend='device', order='F', shape=(10, 20)}.test_cub_min` on `assert cupy_r.shape == numpy_r.shape`, where `cupy_r.shape == ()`, `numpy_r.shape == (20,)`.

**Comment by leofang** [comment] 2020-11-07 05:06
This is very weird. I can't reproduce this locally. We should also investigate the failures, as the assert check is important to ensure whether the target code path is indeed executed or not.

**Comment by takagi** [comment] 2020-11-10 05:57
Looks `cupy.core._routines_statistics.cub.device_segmented_reduce` is not called in the failing shuffled test configuration?

**Comment by toslunar** [comment] 2020-11-10 06:08
For record, the shuffle configuration (`ID=20`) in `daily_master_cupy-shuffled/378` is
```
11:22:17 + ./run_cupy_combination_test.py --id 20
11:22:17 --- Shuffle Parameters ---
11:22:17 cuda_libs: ('cuda90', 'cudnn73-cuda9', 'nccl2.4-cuda9', 'none')
11:22:17 scipy: None
11:22:17 base: ubuntu16_py35
11:22:17 numpy: 1.18
11:22:17 --- Configuration ---
11:22:17 nccl: nccl2.4-cuda9
11:22:17 cutensor: none
11:22:17 cudnn: cudnn73-cuda9
11:22:17 base: ubuntu16_py35
11:22:17 cuda: cuda90
11:22:17 requires: ['numpy<1.19']
11:23:55 sha256:28646ab8950d2c4793c87a7631006aa0a7c063fd6ba98cfeef674f1c0dff3798
```

**Comment by leofang** [comment] 2020-11-10 07:45
> * `cupy.core._routines_statistics.cub.device_segmented_reduce` is not called for some reasons
> * AssertFunctionIsCalled does not exit mock.patch if the assertion fails, followed by weird test results
> 
> The first is why @leofang can't reproduce it locally, right?

Yeah all tests just passed fine locally. Without the first issue, `AssertFunctionIsCalled` wouldn't observe this assertion problem.

**Comment by takagi** [comment] 2020-11-10 11:19
Okay. Then I'll merge #4233 with closing this issue, and post another that addresses the first issue.

**Closed** 2020-11-10 11:21 UTC
Labels: pr-ongoing
