### ISSUE TITLE
Unexpected NaN in TestBSpline::test_bspline_derivative_jumps

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#7665] opened 2023-06-26 07:24 UTC
`TestBSpline::test_bspline_derivative_jumps` has unexpected Nan for some input. Found in #7638.

https://ci.preferred.jp/cupy.win.cuda120/134985/

```
FAILED cupyx_tests\scipy_tests\interpolate_tests\test_bspline.py::TestBSpline::test_bspline_derivative_jumps[_param_0_{c=[-1, 2, 0, -1], extrapolate=True}] - AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

x and y nan location mismatch:
 x: array([-1.206633,  0.363639, -0.413208,       nan])
 y: array([-1.206633,  0.363639, -0.413208,  0.      ])
```

**Comment by takagi** [comment] 2023-06-27 03:55
This failure didn't appear in the full test after merge.
https://ci.preferred.jp/cupy.win.cuda120/135273/

**Comment by kmaehashi** [comment] 2023-10-19 04:48
Closing as duplicate of #7240

**Closed by kmaehashi** 2023-10-19 04:48 UTC
Labels: cat:bug, prio:high
