### ISSUE TITLE
'cupy' is not declared

### ISSUE THREAD

**Issue by lightning20** [cupy/cupy#886] opened 2018-01-16 10:15 UTC
when try to install rllab on ubuntu(python2.7, anaconda2), it give error as below.

    creating /tmp/tmpfdi0u88v/tmp
    creating /tmp/tmpfdi0u88v/tmp/tmpfdi0u88v
    gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I /usr/local/cuda-8.0/targets/x86_64-linux/include -fPIC -I/usr/local/cuda-8.0/include -c /tmp/tmpfdi0u88v/a.cpp -o /tmp/tmpfdi0u88v/tmp/tmpfdi0u88v/a.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    g++ -pthread /tmp/tmpfdi0u88v/tmp/tmpfdi0u88v/a.o -o /tmp/tmpfdi0u88v/a
    error: Command '/home/d/anaconda2/envs/rllab3/bin/python' failed:
    
      command: /home/d/anaconda2/envs/rllab3/bin/python /home/d/anaconda2/envs/rllab3/lib/python3.5/site-packages/cython.py --fast-fail --verbose --cplus --directive linetrace=False --directive profile=False cupy/core/core.pyx
      return code: 1
      output:
    
    b"Compiling /tmp/pip-build-rkyappka/chainer/cupy/core/core.pyx\n\nError compiling Cython file:\n------------------------------------------------------------\n...\n    void* data\n    int size\n    int shape_and_strides[MAX_NDIM * 2]\n\n\ncdef class CArray(cupy.cuda.function.CPointer):\n    ^\n------------------------------------------------------------\n\ncupy/core/carray.pxi:14:5: 'cupy' is not declared\n"
    cython path:/home/d/anaconda2/envs/rllab3/lib/python3.5/site-packages

chainer and cupy are both installed. 

Any suggestion, thanks.

**Comment by niboshi** [comment] 2018-01-16 10:27
It seems rllab fixes the chainer dependency to very old version (1.18.0)... (https://github.com/rll/rllab/blob/master/environment.yml#L57)

Unfortunately we no longer support this version.
One suggestion I can think of is to uninstall Chainer and CuPy from environment first and try installing rllab.

**Comment by lightning20** [comment] 2018-01-16 13:08
Really appreciate it.  But after uninstall latest chainer and install chainer 1.18.0, it gives a same error as in the rllab installation. 

Any suggestion, thanks.

d@m:~/Downloads$ tar zxf chainer-1.18.0.tar.gz
d@m:~/Downloads$ cd chainer-1.18.0
d@m:~/Downloads/chainer-1.18.0$ python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to chainer.egg-info/requires.txt
writing chainer.egg-info/PKG-INFO
writing top-level names to chainer.egg-info/top_level.txt
writing dependency_links to chainer.egg-info/dependency_links.txt
Executing cythonize
Options: {'profile': False, 'annotate': False, 'linetrace': False, 'no_cuda': False}
Include directories: ['/usr/local/cuda-8.0/include']
Library directories: ['/usr/local/cuda-8.0/lib64']
creating /tmp/tmpFCJrIs/tmp
creating /tmp/tmpFCJrIs/tmp/tmpFCJrIs
gcc -pthread -B /home/d/anaconda2/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I /usr/local/cuda-8.0/targets/x86_64-linux/include -fPIC -I/usr/local/cuda-8.0/include -c /tmp/tmpFCJrIs/a.cpp -o /tmp/tmpFCJrIs/tmp/tmpFCJrIs/a.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
g++ -pthread -shared -B /home/d/anaconda2/compiler_compat -L/home/d/anaconda2/lib -Wl,-rpath=/home/d/anaconda2/lib -Wl,--no-as-needed -Wl,--sysroot=/ -L /usr/local/cuda-8.0/targets/x86_64-linux/lib -I /usr/local/cuda-8.0/targets/x86_64-linux/include /tmp/tmpFCJrIs/tmp/tmpFCJrIs/a.o -o /tmp/tmpFCJrIs/liba.so
creating /tmp/tmpHAjfSB/tmp
creating /tmp/tmpHAjfSB/tmp/tmpHAjfSB
gcc -pthread -B /home/d/anaconda2/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I /usr/local/cuda-8.0/targets/x86_64-linux/include -fPIC -c /tmp/tmpHAjfSB/a.cpp -o /tmp/tmpHAjfSB/tmp/tmpHAjfSB/a.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
g++ -pthread -shared -B /home/d/anaconda2/compiler_compat -L/home/d/anaconda2/lib -Wl,-rpath=/home/d/anaconda2/lib -Wl,--no-as-needed -Wl,--sysroot=/ -L /usr/local/cuda-8.0/targets/x86_64-linux/lib -I /usr/local/cuda-8.0/targets/x86_64-linux/include /tmp/tmpHAjfSB/tmp/tmpHAjfSB/a.o -L/usr/local/cuda-8.0/lib64 -lcublas -lcuda -lcudart -lcurand -lnvToolsExt -o /tmp/tmpHAjfSB/liba.so
creating /tmp/tmpLe4_1p/tmp
creating /tmp/tmpLe4_1p/tmp/tmpLe4_1p
gcc -pthread -B /home/d/anaconda2/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I /usr/local/cuda-8.0/targets/x86_64-linux/include -fPIC -I/usr/local/cuda-8.0/include -c /tmp/tmpLe4_1p/a.cpp -o /tmp/tmpLe4_1p/tmp/tmpLe4_1p/a.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
g++ -pthread -B /home/d/anaconda2/compiler_compat -Wl,--sysroot=/ /tmp/tmpLe4_1p/tmp/tmpLe4_1p/a.o -o /tmp/tmpLe4_1p/a
Include directories: ['/usr/local/cuda-8.0/include']
Library directories: ['/usr/local/cuda-8.0/lib64']
creating /tmp/tmp0jXI61/tmp
creating /tmp/tmp0jXI61/tmp/tmp0jXI61
gcc -pthread -B /home/d/anaconda2/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I /usr/local/cuda-8.0/targets/x86_64-linux/include -fPIC -I/usr/local/cuda-8.0/include -c /tmp/tmp0jXI61/a.cpp -o /tmp/tmp0jXI61/tmp/tmp0jXI61/a.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
g++ -pthread -shared -B /home/d/anaconda2/compiler_compat -L/home/d/anaconda2/lib -Wl,-rpath=/home/d/anaconda2/lib -Wl,--no-as-needed -Wl,--sysroot=/ -L /usr/local/cuda-8.0/targets/x86_64-linux/lib -I /usr/local/cuda-8.0/targets/x86_64-linux/include /tmp/tmp0jXI61/tmp/tmp0jXI61/a.o -o /tmp/tmp0jXI61/liba.so
creating /tmp/tmptDBJAT/tmp
creating /tmp/tmptDBJAT/tmp/tmptDBJAT
gcc -pthread -B /home/d/anaconda2/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I /usr/local/cuda-8.0/targets/x86_64-linux/include -fPIC -c /tmp/tmptDBJAT/a.cpp -o /tmp/tmptDBJAT/tmp/tmptDBJAT/a.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
g++ -pthread -shared -B /home/d/anaconda2/compiler_compat -L/home/d/anaconda2/lib -Wl,-rpath=/home/d/anaconda2/lib -Wl,--no-as-needed -Wl,--sysroot=/ -L /usr/local/cuda-8.0/targets/x86_64-linux/lib -I /usr/local/cuda-8.0/targets/x86_64-linux/include /tmp/tmptDBJAT/tmp/tmptDBJAT/a.o -L/usr/local/cuda-8.0/lib64 -lcudnn -o /tmp/tmptDBJAT/liba.so
creating /tmp/tmpzaiW4X/tmp
creating /tmp/tmpzaiW4X/tmp/tmpzaiW4X
gcc -pthread -B /home/d/anaconda2/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I /usr/local/cuda-8.0/targets/x86_64-linux/include -fPIC -I/usr/local/cuda-8.0/include -c /tmp/tmpzaiW4X/a.cpp -o /tmp/tmpzaiW4X/tmp/tmpzaiW4X/a.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
g++ -pthread -B /home/d/anaconda2/compiler_compat -Wl,--sysroot=/ /tmp/tmpzaiW4X/tmp/tmpzaiW4X/a.o -o /tmp/tmpzaiW4X/a
cython path:/home/d/anaconda2/lib/python2.7/site-packages
error: Command '/home/d/anaconda2/bin/python' failed:

  command: /home/d/anaconda2/bin/python /home/d/anaconda2/lib/python2.7/site-packages/cython.py --fast-fail --verbose --cplus --directive profile=False --directive linetrace=False cupy/core/core.pyx
  return code: 1
  output:

Compiling /home/d/Downloads/chainer-1.18.0/cupy/core/core.pyx

Error compiling Cython file:
------------------------------------------------------------
...
    void* data
    int size
    int shape_and_strides[MAX_NDIM * 2]


cdef class CArray(cupy.cuda.function.CPointer):
    ^
------------------------------------------------------------

cupy/core/carray.pxi:14:5: 'cupy' is not declared

**Comment by niboshi** [comment] 2018-01-16 14:08
Did you uninstall CuPy as well?

**Comment by lightning20** [comment] 2018-01-16 14:20
Sorry, just tried uninstalled Cupy as below.

  /usr/local/lib/python2.7/dist-packages/cupy/testing/parameterized.py
  /usr/local/lib/python2.7/dist-packages/cupy/testing/parameterized.pyc
  /usr/local/lib/python2.7/dist-packages/cupy/testing/random.py
  /usr/local/lib/python2.7/dist-packages/cupy/testing/random.pyc
  /usr/local/lib/python2.7/dist-packages/cupy/util.so
Proceed (y/n)? y
  Successfully uninstalled cupy-2.2.0
The directory '/home/d/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
d@m:~/rllab-master/scripts$ sudo pip uninstall cupy
The directory '/home/d/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Uninstalling cupy-4.0.0b2:
  /usr/local/lib/python2.7/dist-packages/cupy-4.0.0b2-py2.7-linux-x86_64.egg
Proceed (y/n)? y
  Successfully uninstalled cupy-4.0.0b2
The directory '/home/d/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
d@m:~/rllab-master/scripts$ sudo pip uninstall cupy
The directory '/home/d/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Cannot uninstall requirement cupy, not installed
The directory '/home/d/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.





But after that, install chainer still got a similar error.

creating /tmp/tmp8Clzi4/tmp
creating /tmp/tmp8Clzi4/tmp/tmp8Clzi4
gcc -pthread -B /home/d/anaconda2/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I /usr/local/cuda-8.0/targets/x86_64-linux/include -fPIC -I/usr/local/cuda-8.0/include -c /tmp/tmp8Clzi4/a.cpp -o /tmp/tmp8Clzi4/tmp/tmp8Clzi4/a.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
g++ -pthread -B /home/d/anaconda2/compiler_compat -Wl,--sysroot=/ /tmp/tmp8Clzi4/tmp/tmp8Clzi4/a.o -o /tmp/tmp8Clzi4/a
cython path:/home/d/anaconda2/lib/python2.7/site-packages
error: Command '/home/d/anaconda2/bin/python' failed:

  command: /home/d/anaconda2/bin/python /home/d/anaconda2/lib/python2.7/site-packages/cython.py --fast-fail --verbose --cplus --directive profile=False --directive linetrace=False cupy/core/core.pyx
  return code: 1
  output:

Compiling /home/d/Downloads/chainer-1.18.0/cupy/core/core.pyx

Error compiling Cython file:
------------------------------------------------------------
...
    void* data
    int size
    int shape_and_strides[MAX_NDIM * 2]


cdef class CArray(cupy.cuda.function.CPointer):
    ^
------------------------------------------------------------

cupy/core/carray.pxi:14:5: 'cupy' is not declared

**Comment by lightning20** [comment] 2018-01-16 15:15
Tried  to find and remove  all the cupy items, but still the same error in chainer install.

creating /tmp/tmp1qtTaN/tmp
creating /tmp/tmp1qtTaN/tmp/tmp1qtTaN
gcc -pthread -B /home/d/anaconda2/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I /usr/local/cuda-8.0/targets/x86_64-linux/include -fPIC -I/usr/local/cuda-8.0/include -c /tmp/tmp1qtTaN/a.cpp -o /tmp/tmp1qtTaN/tmp/tmp1qtTaN/a.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
g++ -pthread -B /home/d/anaconda2/compiler_compat -Wl,--sysroot=/ /tmp/tmp1qtTaN/tmp/tmp1qtTaN/a.o -o /tmp/tmp1qtTaN/a
cython path:/home/d/anaconda2/lib/python2.7/site-packages
error: Command '/home/d/anaconda2/bin/python' failed:

  command: /home/d/anaconda2/bin/python /home/d/anaconda2/lib/python2.7/site-packages/cython.py --fast-fail --verbose --cplus --directive profile=False --directive linetrace=False cupy/core/core.pyx
  return code: 1
  output:

Compiling /home/d/Downloads/chainer-1.18.0/cupy/core/core.pyx

Error compiling Cython file:
------------------------------------------------------------
...
    void* data
    int size
    int shape_and_strides[MAX_NDIM * 2]


cdef class CArray(cupy.cuda.function.CPointer):
    ^
------------------------------------------------------------

cupy/core/carray.pxi:14:5: 'cupy' is not declared

**Comment by niboshi** [comment] 2018-01-17 07:25
I'd suggest asking in Chainer's Slack community (http://bit.ly/join-chainer-slack).
There are much more people and likely to get valuable help.

(By the way, if the issue is related to the actual code, https://stackoverflow.com/ (with `chainer` tag) is also a good place to get support. We're watching there, too.)

I'm closing the issue for now, as the version is very old and this place is not meant for user support anyway.
I hope you can get help there, but please feel free to post here if you have any comments!

**Closed by niboshi** 2018-01-17 07:25 UTC
Labels: other

**Comment by lightning20** [comment] 2018-01-17 16:01
Really thankful for your suggestion. It has been posted on Slack and stackoverflow(https://stackoverflow.com/questions/48305177/chainer-install-error-cupy-not-declare). If there is any solution, I will update here. Thanks again.
