### ISSUE TITLE
Issues with consecutive 2D FFT runs on the same plan

### ISSUE THREAD

**Issue by michaelmarty** [cupy/cupy#5022] opened 2021-04-02 19:41 UTC
I have noticed a problem when CuPy 2D FFTs with the same plan are run consecutively. With certain shapes, they give different and incorrect results the second time. This seems to only happen when the longer dimension of the shape is odd, but I have not done an exhaustive scan. NumPy and SciPy FFT functions show the expected result, and the first run of CuPy always agrees with these. The second run is the problem. For now, I was able to work around by making sure the longer dimension was even, but I wanted to post this in case others were having the same issues. 

* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
  - CuPy version: 8.6.0
  - OS/Platform: Windows 10
  - CUDA version: 11.2
* Code to reproduce

import numpy as np
import cupy as cp

shape = (151, 2229)
a = np.random.randn(*shape)

A1 = np.fft.rfft2(a)
A2 = np.fft.rfft2(a)

b = cp.asarray(a)
B1 = cp.fft.rfft2(b)
B2 = cp.fft.rfft2(b)
if cp.any(B1 != B2):
    print(A1[0,0], A2[0,0], B1[0,0], B2[0,0], shape)

* Error messages, stack traces, or logs

Output from the code above: (-84.42714344719724-2.5579538487363607e-13j) (-84.42714344719724-2.5579538487363607e-13j) (-84.42714344719798+0j) (17.20028862520553-3.1086244689504383e-15j) (151, 2229)

**Comment by michaelmarty** [comment] 2021-04-02 19:44
A quick note: Inserting cp.fft.config.get_plan_cache().clear() between B1 and B2 will fix the issue, but it takes a hit in speed.

**Comment by leofang** [comment] 2021-04-02 19:46
I cannot reproduce this on Linux with exactly the same setup (CuPy v8.6.0 + CUDA 11.2). Could you let us know 1. how is you CuPy installed, and 2. the output of `cupy.show_config()`?

**Comment by leofang** [comment] 2021-04-02 19:49
> A quick note: Inserting cp.fft.config.get_plan_cache().clear() between B1 and B2 will fix the issue, but it takes a hit in speed.

Given that it cannot be reproduced on Linux and that a fresh plan works correctly, I feel something messed up in the internal plan data of cuFFT. Could you also post the output of `print(cp.fft.config.get_plan_cache())` right after your reproducer?

**Comment by michaelmarty** [comment] 2021-04-02 19:59
Yeah, this is a strange bug. I installed it with pip install cupy. We've seen it on multiple computers but all Windows. Here's the printouts.

OS                           : Windows-10-10.0.19041-SP0
CuPy Version                 : 8.6.0
NumPy Version                : 1.19.1
SciPy Version                : 1.5.2
Cython Build Version         : 0.29.22
CUDA Root                    : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1
CUDA Build Version           : 11010
CUDA Driver Version          : 11020
CUDA Runtime Version         : 11010
cuBLAS Version               : 11300
cuFFT Version                : 10300
cuRAND Version               : 10202
cuSOLVER Version             : (11, 0, 1)
cuSPARSE Version             : 11300
NVRTC Version                : (11, 1)
Thrust Version               : 100910
CUB Build Version            : 100910
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
Device 0 Name                : GeForce GTX 1650 Ti
Device 0 Compute Capability  : 75

------------------- cuFFT plan cache (device 0) -------------------
cache enabled? True
current / max size   : 1 / 16 (counts)
current / max memsize: 44975616 / (unlimited) (bytes)
hits / misses: 1 / 1 (counts)

cached plans (most recently used first):
key: ((151, 2229), (151, 2229), 1, 1, (151, 1115), 1, 1, 106, 1, 'C', 1, 1115), plan type: PlanNd, memory usage: 44975616

**Comment by leofang** [comment] 2021-04-02 20:05
Thanks, @michaelmarty. An alternative workaround for you is to disable the cuFFT plan cache right after import so that you don't reuse already-used plans. But like you said, there's an overhead because of repetitive plan generation (which was why we cache them).
```python
import cupy as cp
cache = cp.fft.config.get_plan_cache()
cache.set_size(0)
```

**Comment by leofang** [comment] 2021-04-02 20:13
Hi @mnicely Sorry to bug you. We got a report that seems to imply a bug in cuFFT on Windows (see above). When a D2Z ND plan is used the second time to launch the transform, the outcome messed up. The first run is correct. 

The arguments that are passed to create a ND plan
https://github.com/cupy/cupy/blob/cc6b3e583071d668ed1f3fc6e3f305526f2c54dd/cupy/cuda/cufft.pyx#L732-L735
are `(shape=(151, 2229), inembed=(151, 2229), istride=1, idist=1, onembed=(151, 1115), ostride=1, odist=1, fft_type=106, batch=1, order='C', last_axis=1, last_size=1115)`. I hope it's enough for you and your colleagues to take over and investigate? 🙏 Many thanks!

I can try and write a C reproducer for you if absolutely needed, but I can't confirm if it really reproduces as I don't have access to Windows to test, and I don't have time to do it this week unfortunately.

**Comment by leofang** [comment] 2021-04-02 20:22
@michaelmarty Just curious, what if you run it a few more times (with the cached plan)? Do you see B1 != B2 = B3 = B4 = ...?
```python 
B1 = cp.fft.rfft2(b)
B2 = cp.fft.rfft2(b)
B3 = cp.fft.rfft2(b)
B4 = cp.fft.rfft2(b)
...
```
I am curious if the bug is deterministic.

**Comment by michaelmarty** [comment] 2021-04-02 20:56
It gives the same response for B2, B3, and B4:

(-174.93917882602588-1.0658141036401503e-13j) (-6.01654092402711-2.6645352591003757e-15j) (-6.01654092402711-2.6645352591003757e-15j) (-6.01654092402711-2.6645352591003757e-15j)

Another note to add, we get the same problems with the fft2 as the rfft2. The even number work around seems to fix it well enough, but I wanted to post it to see if we can get to the bottom of it. Thanks!

**Comment by leofang** [comment] 2021-04-03 06:44
@michaelmarty For `fft2`, what are the failing array shapes? Note that cuFFT have special cases for 2^a * 3^b * 5^c * 7^d, so could you try a few cases in which the shapes are odd numbers but consist of these primes only?

**Comment by mnicely** [comment] 2021-04-03 12:01
@leofang thanks for the ping. I’ll file a bug. 

@michaelmarty can you create a small reproducer?

**Comment by mnicely** [comment] 2021-04-06 12:52
I'm unable to reproduce the error on the following configuration

```bash
OS                           : Windows-10-10.0.21343-SP0                                                       CuPy Version                 : 8.6.0                                                                           NumPy Version                : 1.20.2                                                                          SciPy Version                : None                                                                            Cython Build Version         : 0.29.22                                                                         CUDA Root                    : None                                                                            CUDA Build Version           : 11020                                                                           CUDA Driver Version          : 11030                                                                           CUDA Runtime Version         : 11020                                                                           cuBLAS Version               : 11401                                                                           cuFFT Version                : 10401                                                                           cuRAND Version               : 10203                                                                           cuSOLVER Version             : (11, 1, 0)                                                                      cuSPARSE Version             : 11401                                                                           NVRTC Version                : (11, 2)                                                                         Thrust Version               : 101000                                                                          CUB Build Version            : 101000                                                                          cuDNN Build Version          : 8100                                                                            cuDNN Version                : 8100                                                                            NCCL Build Version           : None                                                                            NCCL Runtime Version         : None                                                                            cuTENSOR Version             : 10202                                                                           Device 0 Name                : Quadro M1200                                                                    Device 0 Compute Capability  : 50 
```

**Comment by leofang** [comment] 2021-04-06 12:55
@mnicely Thanks, very strange. How did you install CuPy on this machine, pip or conda?

**Comment by mnicely** [comment] 2021-04-06 12:56
Installed miniconda3, then `conda install cupy -y`

**Comment by mnicely** [comment] 2021-04-06 12:58
Confirmed the issue is not with `numpy == 1.19.1`

Let me see if I can install CTK 11.1 with the older version of cuFFT

**Comment by leofang** [comment] 2021-04-06 13:00
`conda install -c conda-forge cupy cudatoolkit=11.1` should do the job (op is on 11.1)

**Comment by mnicely** [comment] 2021-04-06 13:06
Okay, I see the issue!
Looks like it's been fixed in cuFFT 10.4.01.

@michaelmarty please install CTK 11.2

**Comment by leofang** [comment] 2021-04-06 13:46
Great, thanks for checking for us @mnicely! May I ask the impact scope of this bug? Is it Windows only? Is it specific to CUDA 11.1? If the scope is known we can advice users to avoid it and/or add warnings/tests for it.

**Comment by mnicely** [comment] 2021-04-06 14:09
It is CTK 11.1 specific -- https://docs.nvidia.com/cuda/archive/11.2.0/cuda-toolkit-release-notes/index.html#cufft-resolved-issues

"Plans with primes larger than 127 in FFT size decomposition or FFT size being a prime number bigger than 4093 do not perform calculations on second and subsequent cufftExecute* calls. Regression was introduced in cuFFT 11.1"

**Comment by leofang** [comment] 2021-04-06 14:34
Interesting...We didn't see this regression on Linux, did we?

**Comment by mnicely** [comment] 2021-04-06 14:46
I just verified it exists on Linux w/ CTK 11.1

**Comment by leofang** [comment] 2021-04-06 15:11
Ah OK, I was thinking 11.2 (https://github.com/cupy/cupy/issues/5022#issuecomment-812683600) as it was mentioned in the original post. I will send a patch to disable plan cache on CUDA 11.1.

@michaelmarty Could you confirm when you filed this issue, you were on CUDA 11.1, not 11.2?

**Comment by mnicely** [comment] 2021-04-06 15:12
> Ah OK, I was thinking 11.2 ([#5022 (comment)](https://github.com/cupy/cupy/issues/5022#issuecomment-812683600)) as it was mentioned in the original post. I will send a patch to disable plan cache on CUDA 11.1.
> 
> @michaelmarty Could you confirm when you filed this issue, you were on CUDA 11.1, not 11.2?

According to https://github.com/cupy/cupy/issues/5022#issuecomment-812687873, it's 11.1 and cuFFT 10.3

**Comment by leofang** [comment] 2021-04-06 15:14
Yes but in https://github.com/cupy/cupy/issues/5022#issue-849424119 it says 11.2 so I was testing this version.

**Comment by mnicely** [comment] 2021-04-06 15:19
Because it's not the "actual" output from `cupy.show_config()`, I'm betting that's the CUDA Driver Version. 
It's common to get that confused with build version, because 'nvidia-smi' displays the driver version.

Let's see what @michaelmarty replies.

**Comment by leofang** [comment] 2021-04-06 15:24
Yeah I think that's possible...Thanks Matt!

**Comment by michaelmarty** [comment] 2021-04-06 15:30
Correct, the original issue was CUDA 11.1. Upgrading to 11.2 fixed it. Thanks for tracking this down! Hopefully the fix should help others avoid going down this rabbit hole.

**Comment by emcastillo** [comment] 2021-04-09 01:28
Let us close this :)

**Closed by emcastillo** 2021-04-09 01:28 UTC
Labels: issue-checked
