### ISSUE TITLE
Defining __device__ kernels using cupy

### ISSUE THREAD

**Issue by HyeongminLEE** [cupy/cupy#1776] opened 2018-11-05 11:39 UTC
Hi, I'm writing cupy version codes of Examples in book 'cuda by example an introduction to general-purpose gpu programming source code'. I want to make cupy version of the following code:

```
struct cuComplex {
    float   r;
    float   i;
    cuComplex( float a, float b ) : r(a), i(b)  {}
    __device__ float magnitude2( void ) {
        return r * r + i * i;
    }
    __device__ cuComplex operator*(const cuComplex& a) {
        return cuComplex(r*a.r - i*a.i, i*a.r + r*a.i);
    }
    __device__ cuComplex operator+(const cuComplex& a) {
        return cuComplex(r+a.r, i+a.i);
    }
};

__device__ int julia( int x, int y ) {
    const float scale = 1.5;
    float jx = scale * (float)(DIM/2 - x)/(DIM/2);
    float jy = scale * (float)(DIM/2 - y)/(DIM/2);

    cuComplex c(-0.8, 0.156);
    cuComplex a(jx, jy);

    int i = 0;
    for (i=0; i<200; i++) {
        a = a * a + c;
        if (a.magnitude2() > 1000)
            return 0;
    }

    return 1;
}

__global__ void kernel( unsigned char *ptr ) {
    // map from blockIdx to pixel position
    int x = blockIdx.x;
    int y = blockIdx.y;
    int offset = x + y * gridDim.x;

    // now calculate the value at that position
    int juliaValue = julia( x, y );
    ptr[offset*4 + 0] = 255 * juliaValue;
    ptr[offset*4 + 1] = 0;
    ptr[offset*4 + 2] = 0;
    ptr[offset*4 + 3] = 255;
}
```

I could write `__global__ void kernel( unsigned char *ptr )` with `cupy.RawKernel` method. But I could not find any way to wrtie `__device__ int julia( int x, int y )` or `struct cuComplex`. Is there any way to wrtie definition of structures or functions like `__device__` kernels?

Thank you.

**Comment by kmaehashi** [comment] 2018-11-05 11:52
Could you paste the code you tried and error message you got?
Note that the kernel function should be in C linkage (`extern "C" __global__ void mykernel (...) {...}`)

**Comment by HyeongminLEE** [comment] 2018-11-05 12:44
This is my code:
```
import scipy.misc
import numpy as np
import cupy as cp

dim = 1000
scale = 1.5

kernel = cp.RawKernel(r'''
struct cuComplex {
    float   r;
    float   i;
    cuComplex( float a, float b ) : r(a), i(b)  {}
    __device__ float magnitude2( void ) {
        return r * r + i * i;
    }
    __device__ cuComplex operator*(const cuComplex& a) {
        return cuComplex(r*a.r - i*a.i, i*a.r + r*a.i);
    }
    __device__ cuComplex operator+(const cuComplex& a) {
        return cuComplex(r+a.r, i+a.i);
    }
};

__device__ int julia( int x, int y ) {
    int DIM = 1000;
    const float scale = 1.5;
    float jx = scale * (float)(DIM/2 - x)/(DIM/2);
    float jy = scale * (float)(DIM/2 - y)/(DIM/2);

    cuComplex c(-0.8, 0.156);
    cuComplex a(jx, jy);

    int i = 0;
    for (i=0; i<200; i++) {
        a = a * a + c;
        if (a.magnitude2() > 1000)
            return 0;
    }

    return 1;
}

extern "C" __global__ void kernel( unsigned char *ptr ) {
    // map from blockIdx to pixel position
    int x = blockIdx.x;
    int y = blockIdx.y;
    int offset = x + y * gridDim.x;

    // now calculate the value at that position
    int juliaValue = julia( x, y );
    ptr[offset*4 + 0] = 255 * juliaValue;
    ptr[offset*4 + 1] = 0;
    ptr[offset*4 + 2] = 0;
    ptr[offset*4 + 3] = 255;
}
''', 'kernel')

image = np.zeros((dim, dim, 3), dtype=np.uint8).reshape(dim * dim * 3)
image_gpu = cp.asarray(image)
kernel((dim, dim), (1,), image_gpu)
image_result = image_gpu.get().reshape(dim, dim, 3)
# image_result = np.concatenate((image_gpu[:, :, 0:1].get(), image_gpu[:, :, 1:2].get(), image_gpu[:, :, 2:3].get()), axis=2)

scipy.misc.imsave('julia.png', image_result)

```

And the error message:
```
ssh://hyeongmin@165.132.121.206:42202/home/hyeongmin/.conda/envs/py36-torch04/bin/python -u /home/hyeongmin/projects/cuda_tutorial/cuda_cupy/002_2.julia_gpu.py
Traceback (most recent call last):
  File "/home/hyeongmin/.conda/envs/py36-torch04/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 241, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy/cuda/nvrtc.pyx", line 98, in cupy.cuda.nvrtc.compileProgram
  File "cupy/cuda/nvrtc.pyx", line 108, in cupy.cuda.nvrtc.compileProgram
  File "cupy/cuda/nvrtc.pyx", line 53, in cupy.cuda.nvrtc.check_status
cupy.cuda.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hyeongmin/projects/cuda_tutorial/cuda_cupy/002_2.julia_gpu.py", line 60, in <module>
    kernel((dim, dim), (1,), image_gpu)
  File "cupy/core/raw.pyx", line 45, in cupy.core.raw.RawKernel.__call__
  File "cupy/util.pyx", line 48, in cupy.util.memoize.decorator.ret
  File "cupy/core/raw.pyx", line 51, in cupy.core.raw._get_raw_kernel
  File "cupy/core/carray.pxi", line 125, in cupy.core.core.compile_with_cache
  File "cupy/core/carray.pxi", line 148, in cupy.core.core.compile_with_cache
  File "/home/hyeongmin/.conda/envs/py36-torch04/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 164, in compile_with_cache
    ptx = compile_using_nvrtc(source, options, arch)
  File "/home/hyeongmin/.conda/envs/py36-torch04/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 82, in compile_using_nvrtc
    ptx = prog.compile(options)
  File "/home/hyeongmin/.conda/envs/py36-torch04/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 245, in compile
    raise CompileException(log, self.src, self.name, options)
cupy.cuda.compiler.CompileException: /tmp/tmpma9ch8dd/kern.cu(5): error: A function without execution space annotations (__host__/__device__/__global__) is considered a host function, and host functions are not allowed in JIT mode. Consider using -default-device flag to process unannotated functions as __device__ functions in JIT mode

1 error detected in the compilation of "/tmp/tmpma9ch8dd/kern.cu".


Process finished with exit code 1

```

I think writing `struct cuComplex` and `__device__ int julia( int x, int y )` definitions in the same RawKernel with `__global__` function was the problem. However, I want to define the `struct cuComplex` and `__device__ int julia( int x, int y )` because it is possible in CUDA. How can I do that?

**Comment by kmaehashi** [comment] 2018-11-06 06:48
How about this?

```
-    cuComplex( float a, float b ) : r(a), i(b)  {}
+    __device__ cuComplex( float a, float b ) : r(a), i(b)  {}
```

Tip: If you are working with RawKernel, setting environment variable `export CUPY_DUMP_CUDA_SOURCE_ON_ERROR=1` will help diagnosing the problem as the error message contains the line number (`5`).

> cupy.cuda.compiler.CompileException: /tmp/tmpma9ch8dd/kern.cu(5)
https://docs-cupy.chainer.org/en/stable/reference/environment.html

**Comment by HyeongminLEE** [comment] 2018-11-07 02:28
Oh, I will try that. Thank you!!

**Comment by kmaehashi** [comment] 2018-11-15 04:15
As this is not a bug, I'll close this issue. Please use forum https://groups.google.com/forum/#!forum/cupy if you need further assistance.

**Closed by kmaehashi** 2018-11-15 04:15 UTC
Labels: st:awaiting-response

**Comment by rdevans0** [comment] 2021-07-13 05:59
For anyone else running into a similar issue. I found that using some includes can cause this issue. 
for instance:

`#include "stdint.h"`

**Comment by leofang** [comment] 2021-07-13 06:10
Yes this is expected. NVRTC is notoriously bad at interacting with std headers. If it's really unavoidable, try setting `jitify=True` or `backend='nvcc'` in RawModule, either way should work.
