### ISSUE TITLE
PooledMemory bugs?

### ISSUE THREAD

**Issue by hiro4bbh** [cupy/cupy#317] opened 2017-07-24 08:33 UTC
Using cupy (commit: `5062f61065caecb8b3910c452f51b1307f5d8121` on Windows 10) in my program, I got the following many error messages:
```
Traceback (most recent call last):
  File "cupy\cuda\memory.pyx", line 358, in cupy.cuda.memory.PooledMemory.free
TypeError: 'NoneType' object is not callable
Exception ignored in: 'cupy.cuda.memory.PooledMemory.__dealloc__'
Traceback (most recent call last):
  File "cupy\cuda\memory.pyx", line 358, in cupy.cuda.memory.PooledMemory.free
TypeError: 'NoneType' object is not callable
...
Traceback (most recent call last):
  File "cupy\cuda\runtime.pyx", line 222, in cupy.cuda.runtime.free
  File "cupy\cuda\runtime.pyx", line 130, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorInvalidDevicePointer: invalid device pointer
Exception ignored in: 'cupy.cuda.memory.Memory.__dealloc__'
...
Traceback (most recent call last):
  File "xxx\__init__.py", line xxx, in xxx
    return float(xpy.sum((y - z)**2, dtype=xpy.float64))
  File "cupy\core\core.pyx", line 1475, in cupy.core.core.ndarray.__float__
  File "cupy\core\core.pyx", line 1531, in cupy.core.core.ndarray.get
  File "cupy\cuda\memory.pyx", line 254, in cupy.cuda.memory.MemoryPointer.copy_to_host
  File "cupy\cuda\runtime.pyx", line 241, in cupy.cuda.runtime.memcpy
  File "cupy\cuda\runtime.pyx", line 130, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorIllegalAddress: an illegal memory access was encountered
Traceback (most recent call last):
  File "cupy\cuda\memory.pyx", line 360, in cupy.cuda.memory.PooledMemory.free
AttributeError: 'weakref' object has no attribute 'cline_in_traceback'
Exception ignored in: 'cupy.cuda.memory.PooledMemory.__dealloc__'
Traceback (most recent call last):
  File "cupy\cuda\memory.pyx", line 360, in cupy.cuda.memory.PooledMemory.free
AttributeError: 'weakref' object has no attribute 'cline_in_traceback'
Traceback (most recent call last):
  File "cupy\cuda\runtime.pyx", line 222, in cupy.cuda.runtime.free
AttributeError: 'weakref' object has no attribute 'cline_in_traceback'
Exception ignored in: 'cupy.cuda.memory.Memory.__dealloc__'
Traceback (most recent call last):
  File "cupy\cuda\runtime.pyx", line 222, in cupy.cuda.runtime.free
AttributeError: 'weakref' object has no attribute 'cline_in_traceback'
```
These errors only happen when I enable memory pool as the following code:
```python
cupy.cuda.set_allocator(cupy.cuda.MemoryPool().malloc)
```

I think the failure point (cupy.sum) is irreverent to the cause of these errors.
I have no details about these errors.
Is there any way to debug these errors more deeply?

**Comment by sonots** [comment] 2017-07-24 08:48
I will look about this later.

**Comment by sonots** [comment] 2017-07-24 08:51
Can you paste codes to reproduce?

**Comment by hiro4bbh** [comment] 2017-07-24 09:01
Sorry, my code causing the problem is for my research, so I can't paste it.
I have no idea which part causes this problem.
So, if there is any way to debug this, please tell me and I will try to solve this.

**Comment by sonots** [comment] 2017-07-24 10:01
On cython, `import pdb; pdb.set_trace()` is not available, so just do `print` debug. You can build cupy like

```
pip uninstall cupy  # just to assure another cupy is not installed
python setup.py install
```

and run your program.

**Comment by sonots** [comment] 2017-07-24 10:22
Hmm, I can not reproduce.

```python
import cupy

cupy.cuda.set_allocator(cupy.cuda.MemoryPool().malloc)
x = cupy.array([1,2,3,4], dtype=cupy.float64)
```

```python
import cupy

cupy.cuda.set_allocator(cupy.cuda.MemoryPool().malloc)
x = cupy.array([1,2,3,4], dtype=cupy.float64)
y = cupy.array([1,2,3,4], dtype=cupy.float64)
z = float(cupy.sum((x - y)**2, dtype=cupy.float64))
```

**Comment by sonots** [comment] 2017-07-24 10:41
`cupy.cuda.runtime.free` should be invoked only when `free_all_blocks` is invoked https://github.com/cupy/cupy/blob/5062f61065caecb8b3910c452f51b1307f5d8121/cupy/cuda/memory.pyx#L471 (free_all_blocks removes references from _free list, then Memory.__dealloc__ is called)

**Comment by hiro4bbh** [comment] 2017-07-24 12:09
Thank you for your rapid replies.

I will try to create PoC code from my framework and do `print` debug tomorrow on PC in our lab (please wait ...).

I realized that:
* Normal forwarding steps in training seem not to affect.
* Permutating the rows of a design matrix (calculating permutation index array with `numpy.random.permutation` and indexing on cupy array) seems to affect (causing `cudaErrorIllegalAddress`?).
* Adam updates in backwarding steps seem to affect (not causing `cudaErrorIllegalAddress`).

**Comment by sonots** [comment] 2017-07-24 15:40
The traceback line

```
  File "cupy\cuda\memory.pyx", line 358, in cupy.cuda.memory.PooledMemory.free
TypeError: 'NoneType' object is not callable
```

tells the `pool` object which is a weakref.ref of a SingleDeviceMemoryPool was `None`.

https://github.com/cupy/cupy/blob/5062f61065caecb8b3910c452f51b1307f5d8121/cupy/cuda/memory.pyx#L358

```python
332 cdef class PooledMemory(Memory):
333
334     """Memory allocation for a memory pool.
335
336     The instance of this class is created by memory pool allocator, so user
337     should not instantiate it by hand.
338
339     """
340
341     def __init__(self, Chunk chunk, pool):
342         self.device = chunk.device
343         self.ptr = chunk.ptr
344         self.size = chunk.size
345         self.pool = pool
346
347     def __dealloc__(self):
348         if self.ptr != 0:
349             self.free()
350
351     cpdef free(self):
352         """Frees the memory buffer and returns it to the memory pool.
353
354         This function actually does not free the buffer. It just returns the
355         buffer to the memory pool for reuse.
356
357         """
358         pool = self.pool()
359         if pool and self.ptr != 0:
360             pool.free(self.ptr, self.size)
361         self.ptr = 0
362         self.size = 0
363         self.device = None
```

Referring http://cython.readthedocs.io/en/latest/src/userguide/special_methods.html#finalization-method-dealloc, 

> You need to be careful what you do in a `__dealloc__()` method. By the time your `__dealloc__()` method is called, **the object may already have been partially destroyed** and may not be in a valid state as far as Python is concerned, so you should avoid invoking any Python operations which might touch the object. In particular, don’t call any other methods of the object or do anything which might cause the object to be resurrected. It’s best if you stick to just deallocating C data.

it looks the `pool` object potentially can be None in `__dealloc__()`. 

This would be a potential bug in cupy 1.0.0, too.

**Comment by sonots** [comment] 2017-07-24 15:44
Now, I am wondering how to fix this problem because cython's cdef classes do not have `__del__()`.

**Comment by sonots** [comment] 2017-07-24 17:27
@hiro4bbh I wrote an experimental patch https://github.com/sonots/cupy/commit/8a03bce56cc0967fe65aa827b9cc3ccacefb462a. This patch wraps `cdef class` by a usual `class` to use `__del__()` instead of `__dealloc__()` to release an object. Could you try this?

Build as:

```
git remote add sonots https://github.com/sonots/cupy
git checkout -b fix_317 sonots/fix_317
git clean -fdx
python setup.py install
```

**Comment by hiro4bbh** [comment] 2017-07-25 02:59
Thank you for your patch.

I applied the patch as you tell, then I got the following error message many times:

```
Traceback (most recent call last):
  File "cupy\cuda\memory.pyx", line 349, in cupy.cuda.memory.PooledMemory.__del__
  File "cupy\cuda\memory.pyx", line 360, in cupy.cuda.memory.PooledMemory.free
  File "cupy\cuda\memory.pyx", line 485, in cupy.cuda.memory.SingleDeviceMemoryPool.free
  File "cupy\cuda\memory.pyx", line 501, in cupy.cuda.memory.SingleDeviceMemoryPool.free
ValueError: list.remove(x): x not in list
Exception ignored in: <bound method PooledMemory.__del__ of <cupy.cuda.memory.PooledMemory object at 0x0000020C17A87A20>>
```

The number of times that this error happens changes at each run... Are some free lists destroyed in some chunk operations? I think there is no multithreaded operations...

If `cupy.cuda.set_allocator` is called, some calculations would fail randomly (NaN happens or losses didn't decrease). `cupy.cuda.set_pinned_memory_allocator` accelerates calculations, and some error messages won't happen. Does pinned memory allocator affect this problem?

I will inspect the details as preparing PoC code.

**Comment by sonots** [comment] 2017-07-25 03:10
Thank you for trying. Hmm, I will investigate.

`cupy.cuda.set_pinned_memory_allocator` is used to cache a pinned host (CPU) memory, not GPU memory. `cupy.cuda.memory` is not a module for pinned memory, so pinned memory allocator is probably not related with this problem.

**Comment by sonots** [comment] 2017-07-25 03:28
It looks `__del__()` is working anyway although `__dealloc__()` was not working well. It is a progress although we still have another strange thing.

**Comment by hiro4bbh** [comment] 2017-07-25 05:41
When I implement Adam with `cupy.ElementwiseKernel`, then some error messages didn't happen, but rarely happen... Furthermore, when I extract the code from my framework, then any error won't happen...

Maybe, this error is based on free list manipulation operated at memory allocations/deallocations, so it would be difficult to write stable PoC code succinctly (some parts in my framework may affect).

I couldn't create PoC code, but i will continue to create PoC code and inspect the implementation.

**Comment by hiro4bbh** [comment] 2017-07-25 09:06
As trying to create stable PoC code, I realized that `cudaErrorIllegalAddress` won't happen anymore. I think that cupy should use Python `__dealloc__` for pure-C data structures, so @sonots's patch is helpful. Thank you.

In some cases, when `cupy.ElementwiseKernel` is used, any error doesn't happen, so I suspect that some small allocations destroys free list maybe (`x * y` causes one allocation for the result, etc.).

**Comment by sonots** [comment] 2017-07-25 09:10
Let me make sure. Do you mean you still get `ValueError: list.remove(x): x not in list` although you do no get `cudaErrorInvalidDevicePointer`?

**Comment by hiro4bbh** [comment] 2017-07-25 09:12
Yes. I got `ValueError: list.remove(x): x not in list` sometimes (I can't figure out the pattern...). However, I didn't get `cudaErrorInvalidDevicePointer` anymore.

**Comment by sonots** [comment] 2017-07-25 09:13
Okay, thanks.

**Comment by sonots** [comment] 2017-07-25 15:49
@hiro4bbh could you do me a favor?

I added debug print > https://github.com/sonots/cupy/commit/6a6732a2263f0aebd017eaab4700cde1bf751e0d (this commit is pushed in `sonots/fix_317` branch)

Could you run your program with this and paste the result? Please note that the result would become so huge.

**Comment by hiro4bbh** [comment] 2017-07-26 09:49
Thanks for your patch.
I will try your patch next week, because I can't use CUDA PC untill then.
Sorry for my late reply...

**Comment by hiro4bbh** [comment] 2017-07-31 02:27
I tried @sonots patch on a CUDA machine.

I got the exceptions ([fix_317_failed_stdout.txt](https://gist.github.com/hiro4bbh/e652c0b4a3bb031954077342075b8690#file-fix_317_failed_stdout-txt)) and `fix_317` logs  (about 1MB, [fix_317_failed_malloc_free.txt](https://gist.github.com/hiro4bbh/e652c0b4a3bb031954077342075b8690#file-fix_317_failed_malloc_free-txt)). The links are at my gist.

I think that we can ignore `RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>`. Thus the problem is only `ValueError: list.remove(x): x not in list`.

**Comment by sonots** [comment] 2017-07-31 02:42
Thanks! It seems the last line of fix_317_failed_malloc_free.txt is broken like:

```
fix_317 free(ptr=81726034432, si
```

Was you able to paste entire logs until laster line where an error occurred?
Hmm, Gist may not be a good place to paste.
Can you send logs via email? My email address is available from here https://github.com/sonots.

**Comment by sonots** [comment] 2017-07-31 02:53
One more thing. I changed the log line of malloc as:

```
fix_317 malloc(size=512) ptr=38930 PooledMemory=<cupy.cuda.memory.PooledMemory object at 0x7f88482002e8>
```

Could you pull `fix_317` branch again? Thank you for your cooperation.

**Comment by sonots** [comment] 2017-07-31 04:54
Thank you for your email!!

**Comment by sonots** [comment] 2017-07-31 05:40
With logs you've sent via email, I could not see `ValueError: list.remove(x): x not in list`

```
C:\Program Files\Python36\lib\importlib\_bootstrap.py:205: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
Exception ignored in: <bound method PooledMemory.__del__ of <cupy.cuda.memory.PooledMemory object at 0x00000204360EF2E8>>
Traceback (most recent call last):
  File "cupy\cuda\memory.pyx", line 349, in cupy.cuda.memory.PooledMemory.__del__
  File "cupy\cuda\memory.pyx", line 360, in cupy.cuda.memory.PooledMemory.free
  File "cupy\cuda\memory.pyx", line 491, in cupy.cuda.memory.SingleDeviceMemoryPool.free
  File "cupy\cuda\memory.pyx", line 492, in cupy.cuda.memory.SingleDeviceMemoryPool.free
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>
Exception ignored in: <bound method PooledMemory.__del__ of <cupy.cuda.memory.PooledMemory object at 0x0000020436696F28>>
Traceback (most recent call last):
  File "cupy\cuda\memory.pyx", line 349, in cupy.cuda.memory.PooledMemory.__del__
  File "cupy\cuda\memory.pyx", line 360, in cupy.cuda.memory.PooledMemory.free
  File "cupy\cuda\memory.pyx", line 491, in cupy.cuda.memory.SingleDeviceMemoryPool.free
  File "cupy\cuda\memory.pyx", line 500, in cupy.cuda.memory.SingleDeviceMemoryPool.free
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>
```

Did you get the `ValueError` actually?

**Comment by sonots** [comment] 2017-07-31 05:41
This is just my progress. I tried to reproduce by generating python codes like below from logs:

```
import cupy
pool = cupy.cuda.MemoryPool()
m81719721984 = pool.malloc(512)
m81719722496 = pool.malloc(512)
m81719723008 = pool.malloc(512)
m81719723520 = pool.malloc(512)
m81719724032 = pool.malloc(512)
m81721819136 = pool.malloc(12288)
m81719724544 = pool.malloc(512)
m81721831424 = pool.malloc(12288)
m81723916288 = pool.malloc(24064)
m81719725056 = pool.malloc(512)
del m81723916288
m81723916288 = pool.malloc(512)
del m81719725056
m81719725056 = pool.malloc(512)
m81723916800 = pool.malloc(512)
[omitted]
```

But, I still can not reproduce yet.

**Comment by hiro4bbh** [comment] 2017-07-31 05:44
Sorry, I think that I extracted the log of not-problematic part. I will extract the log of the problematic one.

Please wait a moment...

**Comment by sonots** [comment] 2017-07-31 07:32
Thank you for new logs.

**Comment by sonots** [comment] 2017-07-31 07:34
Hmm, unfortunately, I could not reproduce from replay. I will investigate more.

**Comment by sonots** [comment] 2017-08-02 13:44
@hiro4bbh could you tell me python version and cython version you used?

**Comment by sonots** [comment] 2017-08-02 13:47
```
$ grep -C 2 -n '81721835008' ~/fix_317_failed_all.txt

1349:fix_317   [pop best-fit free_list] ptr=81721835008 size=512 chunk=<cupy.cuda.memory.Chunk object at 0x00000240B0A7BC10>
1350:fix_317   [split size=512] ptr=81721835008 size=512 chunk=<cupy.cuda.memory.Chunk object at 0x00000240B0A7BC10>
1351:fix_317   [push in_use] ptr=81721835008 size=512 chunk=<cupy.cuda.memory.Chunk object at 0x00000240B0A7BC10>
1352-fix_317 malloc(size=512) ptr=81721835008 PooledMemory=<cupy.cuda.memory.PooledMemory object at 0x00000240B0A44A20>
--
2121-fix_317 free(ptr=81721834496, size=512)
2122-fix_317   [pop in_use] ptr=81721834496 size=512 chunk=<cupy.cuda.memory.Chunk object at 0x00000240B0A7B3F0>
2123:fix_317   [remove next free_list] ptr=81721835008 size=512 chunk=<cupy.cuda.memory.Chunk object at 0x00000240B0A7BC10>
```

This tells `81721835008` is in_use, but ` free(ptr=81721834496, size=512)` tried to remove `81721835008` from free_list, and error occurred.

**Comment by sonots** [comment] 2017-08-02 13:48
@hiro4bbh could you tell me python version and cython version you used?

**Comment by sonots** [comment] 2017-08-02 17:02
Do you run in multiple threads by any chances? I found wierd logs as below:

```
  1684 fix_317 malloc(size=512) ptr=81723928576 PooledMemory=<cupy.cuda.memory.PooledMemory object at 0x00000240B0A44D68>
  1685 fix_317   [pop best-fit free_list] ptr=81723929088 size=11264 chunk=<cupy.cuda.memory.Chunk object at 0x00000240B0C31798>
  1686 fix_317   [split size=512] ptr=81723929088 size=11264 chunk=<cupy.cuda.memory.Chunk object at 0x00000240B0C31798>fix_317 free(ptr=81721839616, size=512)
  1687 fix_317   [pop in_use] ptr=81721839616 size=512 chunk=<cupy.cuda.memory.Chunk object at 0x00000240B0A7A4C0>
  1688 fix_317   [remove prev free_list] ptr=81721835520 size=4096 chunk=<cupy.cuda.memory.Chunk object at 0x00000240B0C31A08>
  1689 fix_317   [merged] ptr=81721835520 size=4608 chunk=<cupy.cuda.memory.Chunk object at 0x00000240B0C31CE0>
  1690 fix_317   [push free_list] ptr=81721835520 size=4608 chunk=<cupy.cuda.memory.Chunk object at 0x00000240B0C31CE0>
  1691 fix_317 free(ptr=81721840128, size=512)
  1692 fix_317   [pop in_use] ptr=81721840128 size=512 chunk=<cupy.cuda.memory.Chunk object at 0x00000240B0A7A938>
  1693 fix_317   [remove prev free_list] ptr=81721835520 size=4608 chunk=<cupy.cuda.memory.Chunk object at 0x00000240B0C31CE0>
  1694 fix_317   [merged] ptr=81721835520 size=5120 chunk=<cupy.cuda.memory.Chunk object at 0x00000240B0C31D48>
  1695 fix_317   [push free_list] ptr=81721835520 size=5120 chunk=<cupy.cuda.memory.Chunk object at 0x00000240B0C31D48>
  1696 fix_317 free(ptr=81721840640, size=512)
  1697 fix_317   [pop in_use] ptr=81721840640 size=512 chunk=<cupy.cuda.memory.Chunk object at 0x00000240B0C31118>
  1698 fix_317   [remove prev free_list] ptr=81721835520 size=5120 chunk=<cupy.cuda.memory.Chunk object at 0x00000240B0C31D48>
  1699 fix_317   [merged] ptr=81721835520 size=5632 chunk=<cupy.cuda.memory.Chunk object at 0x00000240B0C31DB0>
  1700 fix_317   [push free_list] ptr=81721835520 size=5632 chunk=<cupy.cuda.memory.Chunk object at 0x00000240B0C31DB0>
  1701
  1702 fix_317   [push remaining free_list] ptr=81723929600 size=10752 chunk=<cupy.cuda.memory.Chunk object at 0x00000240B0A7AEE8>
  1703 fix_317   [push in_use] ptr=81723929088 size=512 chunk=<cupy.cuda.memory.Chunk object at 0x00000240B0A7AD48>
  1704 fix_317 malloc(size=512) ptr=81723929088 PooledMemory=<cupy.cuda.memory.PooledMemory object at 0x00000240AE7B56A0>
```

where

```
  1685 fix_317   [pop best-fit free_list] ptr=81723929088 size=11264 chunk=<cupy.cuda.memory.Chunk object at 0x00000240B0C31798>
  1686 fix_317   [split size=512] ptr=81723929088 size=11264 chunk=<cupy.cuda.memory.Chunk object at 0x00000240B0C31798>fix_317 free(ptr=81721839616, size=512)
  1702 fix_317   [push remaining free_list] ptr=81723929600 size=10752 chunk=<cupy.cuda.memory.Chunk object at 0x00000240B0A7AEE8>
  1703 fix_317   [push in_use] ptr=81723929088 size=512 chunk=<cupy.cuda.memory.Chunk object at 0x00000240B0A7AD48>
  1704 fix_317 malloc(size=512) ptr=81723929088 PooledMemory=<cupy.cuda.memory.PooledMemory object at 0x00000240AE7B56A0>
```

are consecutive logs.

**Comment by sonots** [comment] 2017-08-02 18:59
Added codes to print thread_ids on the fix_317 branch.

**Comment by sonots** [comment] 2017-08-03 05:38
> hiro4bbh says...
>
> Python on Windows 10 x64 is version 3.6.2, and Cython is version 0.26.

**Comment by sonots** [comment] 2017-08-03 05:51
I tried with same python and cython version, but I could not reproduce. I now doubt windows environment, but I do not have a windows environment ...

**Comment by sonots** [comment] 2017-08-03 10:05
I am not sure whether this helps, but I made thread-safe implementation as https://github.com/cupy/cupy/compare/master...sonots:fix_317. Can you try this?

**Comment by hiro4bbh** [comment] 2017-08-04 04:10
I tried several cases for reproducing the bug in your previous patch, but I couldn't reproduce.

I will try your latest patch. If there is no problem, I will use that version. I will report how your latest patch works.

Thank you for your patch!

**Comment by hiro4bbh** [comment] 2017-08-07 03:16
I confimed that your latest patch didn't fail. I couldn't reproduce the bug.

Thank you!

**Comment by sonots** [comment] 2017-09-04 15:23
Fixed via https://github.com/cupy/cupy/pull/381 and https://github.com/cupy/cupy/pull/382.

**Closed by sonots** 2017-09-04 15:23 UTC
Labels: bug
