### ISSUE TITLE
Finding the cuda folder by searching for the nvrtc dll

### ISSUE THREAD

**Issue by martinResearch** [cupy/cupy#8384] opened 2024-06-19 16:23 UTC
### Description

CuPy has a mechanism implemented [here](https://github.com/cupy/cupy/blob/0fef5f6b3751da044895dea47a84da2a7e1c165a/cupy/_environment.py#L114C5-L114C19) to find the folder that contain the CUDA binaries when CUDA_PATH is not set by searching for the `nvcc` executable. 
In practice it seems possible to use CuPy without the `nvcc` executable by using the `nvrtc` dll as backend instead (see [here](https://github.com/cupy/cupy/blob/0fef5f6b3751da044895dea47a84da2a7e1c165a/cupy/cuda/compiler.py#L277)). While doing so one currently still needs to either set CUDA_PATH  or have the `nvcc` executable installed in their environement for CuPy to be able to find the cuda path.
We could relax this constraint by searching for the folder containing the nvrtc dll too using ctypes.

**Comment by kmaehashi** [comment] 2024-06-20 04:41
Thanks for the feedback and PR @martinResearch! Could you elaborate more on the motivation behind this?

**Comment by martinResearch** [comment] 2024-06-20 13:40
I am using a conda environment in which the `nvrtc` dlls is installed trough a conda package but not `nvcc`. I cannot set the CUDA_PATH variable in advance in the conda `environment.yml` file because I do not know in advance where this environment is going to be created by the contributors to my project. I would prefer not to ask the contributeurs to my project to have to manually add a CUDA_PATH variable in the conda environment or at the system level because that is error-prone. Without the change in this PR CuPy is not able the find the cuda folder. With the changes in this PR, CuPy finds the nvrtc dll and its path is used to define the cuda path and I do not need to manually define the CUDA_PATH variable.

**Comment by leofang** [comment] 2024-06-20 22:35
If you also install CuPy from conda-forge, library loading should already be taken care for you. conda knows where to find shared libraries. I would like to know better what is missing for your use case. Can you share with us, e.g. what is the error that you see without your PR?

**Comment by martinResearch** [comment] 2024-06-21 15:41
Although I use a conda environment, I install my dependencies from pypi.org using pip because I use pip-tools to pin my dependencies versions.
The error I am getting is `nvrtc: error: failed to open nvrtc-builtins64_118.dll.`

**Comment by leofang** [comment] 2024-06-25 02:29
> Although I use a conda environment, I install my dependencies from pypi.org using pip ...

This is the kind of information that would have helped us understand the issue sooner if you had filled out the issue template as requested 🙂 

IIUC you're saying: You want to install CUDA and CuPy wheels via `pip` and you expect them to work. Is it correct? If so, this issue is a duplicate of #8013, and your PR #8387 would not make it work either because of CUDA wheels' awkward layout. 

I am busy putting together a plan to fix this from CUDA Python perspective (https://github.com/NVIDIA/cuda-python/issues/62), but it would not be someone happening over night unfortunately.

**Comment by martinResearch** [comment] 2024-06-29 11:10
Sorry I did not provide detailed information in the issue description; it did not seem to me relevant to the problem back then. 
I want to install only CUDA 11.8 using Conda (because the CUDA packages on pypi.org do not provide all the dlls, at least on windows), and all the other dependencies (including CuPy) using pip. The changes in this PR make it work on my machine despite "CUDA wheels' awkward layout".

**Comment by kmaehashi** [comment] 2024-08-08 08:22
https://github.com/cupy/cupy/pull/8387#issuecomment-2275235804

**Closed by kmaehashi** 2024-08-08 08:22 UTC
Labels: issue-checked
