### ISSUE TITLE
Incompatibility with matplotlib backend Gtk3Agg - floating constant is out of range

### ISSUE THREAD

**Issue by Leberwurscht** [cupy/cupy#2558] opened 2019-10-21 10:05 UTC
Hi,

with the following test script:

    #!/usr/bin/env python3

    import numpy as np
    import cupy as cp

    import matplotlib.pyplot as plt

    data1 = np.random.random(4096)
    data2 = np.random.random(4096)
    cpdata1 = cp.asarray(data1)
    cpdata2 = cp.asarray(data2)
    cpdata3 = cp.add(cpdata1, cpdata2)
    result = cp.asnumpy(cpdata3)

    plt.figure()
    plt.plot(result)
    plt.show()

I got the following error message appended below ("floating constant is out of range").
I narrowed down the problem to matplotlib - if I remove the plot commands and `import matplotlib.pyplot as plt`, the error disappears.

If I do

    import matplotlib
    print(matplotlib.get_backend())

I get `Gtk3Agg`.
After a `sudo apt  install python3-pyqt5`, the problem disappered (new default backend is Qt5Agg).
Strangely, now even if I add

    import matplotlib
    matplotlib.use('Gtk3Agg')

before `import matplotlib.pyplot as plt`, the problem does not show up anymore.

Here is the full error message:

```
Traceback (most recent call last):
  File "/home/maxi/.local/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 242, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy/cuda/nvrtc.pyx", line 98, in cupy.cuda.nvrtc.compileProgram
  File "cupy/cuda/nvrtc.pyx", line 108, in cupy.cuda.nvrtc.compileProgram
  File "cupy/cuda/nvrtc.pyx", line 53, in cupy.cuda.nvrtc.check_status
cupy.cuda.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testbug.py", line 14, in <module>
    cpdata3 = cp.add(cpdata1, cpdata2)
  File "cupy/core/_kernel.pyx", line 851, in cupy.core._kernel.ufunc.__call__
  File "cupy/core/_kernel.pyx", line 863, in cupy.core._kernel.ufunc._get_ufunc_kernel
  File "cupy/core/_kernel.pyx", line 625, in cupy.core._kernel._get_ufunc_kernel
  File "cupy/core/_kernel.pyx", line 60, in cupy.core._kernel._get_simple_elementwise_kernel
  File "cupy/core/carray.pxi", line 166, in cupy.core.core.compile_with_cache
  File "/home/maxi/.local/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 165, in compile_with_cache
    ptx = compile_using_nvrtc(source, options, arch, name + '.cu')
  File "/home/maxi/.local/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 81, in compile_using_nvrtc
    ptx = prog.compile(options)
  File "/home/maxi/.local/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 246, in compile
    raise CompileException(log, self.src, self.name, options)
cupy.cuda.compiler.CompileException: /home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/arithmetic.h(284): error: floating constant is out of range

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/arithmetic.h(285): error: floating constant is out of range

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/arithmetic.h(286): error: floating constant is out of range

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/cexpf.h(61): error: floating constant is out of range

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/clogf.h(101): error: floating constant is out of range

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/clogf.h(115): error: floating constant is out of range

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/clogf.h(115): error: floating constant is out of range

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/ctanhf.h(86): error: floating constant is out of range

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/csqrtf.h(109): error: floating constant is out of range

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/csqrtf.h(110): error: floating constant is out of range

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/catrig.h(61): warning: floating-point value does not fit in required floating-point type

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/catrigf.h(99): warning: integral value does not fit in required floating-point type

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/catrigf.h(100): error: floating constant is out of range

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/catrigf.h(110): warning: integral value does not fit in required floating-point type

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/catrigf.h(138): warning: integral value does not fit in required floating-point type

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/catrigf.h(145): warning: integral value does not fit in required floating-point type

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/catrigf.h(146): warning: integral value does not fit in required floating-point type

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/catrigf.h(158): error: floating constant is out of range

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/catrigf.h(183): error: floating constant is out of range

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/catrigf.h(184): warning: integral value does not fit in required floating-point type

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/catrigf.h(184): warning: integral value does not fit in required floating-point type

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/catrigf.h(207): error: floating constant is out of range

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/catrigf.h(208): error: floating constant is out of range

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/catrigf.h(237): error: floating constant is out of range

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/catrigf.h(238): warning: integral value does not fit in required floating-point type

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/catrigf.h(238): warning: integral value does not fit in required floating-point type

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/catrigf.h(354): warning: floating-point value does not fit in required floating-point type

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/catrigf.h(378): warning: floating-point value does not fit in required floating-point type

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/catrigf.h(384): error: floating constant is out of range

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/catrigf.h(388): warning: integral value does not fit in required floating-point type

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/complex/catrigf.h(388): warning: integral value does not fit in required floating-point type

/home/maxi/.local/lib/python3.6/site-packages/cupy/core/include/cupy/carray.cuh(281): warning: statement is unreachable
          detected during instantiation of "void CIndexer<_ndim>::set(ptrdiff_t) [with _ndim=1]" 
/tmp/tmpeg6wny2s/3d8083c4ae49f3d776a835308a8838e4_2.cubin.cu(12): here

17 errors detected in the compilation of "/tmp/tmpeg6wny2s/3d8083c4ae49f3d776a835308a8838e4_2.cubin.cu".
```

from `python3 -c 'import cupy; cupy.show_config()'`, I get

```
CuPy Version          : 6.4.0
CUDA Root             : /usr
CUDA Build Version    : 8000
CUDA Driver Version   : 10020
CUDA Runtime Version  : 8000
cuDNN Build Version   : 7102
cuDNN Version         : 7102
NCCL Build Version    : 2213
NCCL Runtime Version  : (unknown)

```

**Comment by kmaehashi** [comment] 2021-11-22 15:07
I couldn't reproduce this. Let me close this as this is outdated. Feel free to leave a comment if anyone has this error so that we can reopen this issue.

**Closed by kmaehashi** 2021-11-22 15:07 UTC
Labels: issue-checked
