### ISSUE TITLE
Unable to convert Numpy Object to Cupy Array

### ISSUE THREAD

**Issue by Weigaa** [cupy/cupy#7151] opened 2022-10-28 14:19 UTC
### Description

I tried to convert python dictionary type to cupy, but it failed. I then tried to use numpy as an intermediary, but it still failed.
Is there a way to support dict to cupy conversion?

### To Reproduce

```py
# Write the code here
#convert with numpy
>>> import cupy
>>> import torch
>>> a = {1: 'a', 2: 'b'}
>>> import numpy
>>> b = numpy.array(a)
>>> c = cupy.array(b)
#convert directly
>>> a = {1: 'a', 2: 'b'}
>>> b = cupy.array(a)
```

### Installation

Conda-Forge (`conda install ...`)

### Environment

```
# Paste the output here
OS                           : Linux-5.4.0-89-generic-x86_64-with-glibc2.27
Python Version               : 3.9.13
CuPy Version                 : 11.2.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.23.1
SciPy Version                : 1.8.1
Cython Build Version         : 0.29.32
Cython Runtime Version       : None
CUDA Root                    : /home/lthpc/.conda/envs/wjpytorch
nvcc PATH                    : None
CUDA Build Version           : 11020
CUDA Driver Version          : 11070
CUDA Runtime Version         : 11060
cuBLAS Version               : (available)
cuFFT Version                : 10600
cuRAND Version               : 10209
cuSOLVER Version             : (11, 3, 2)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 6)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : 343be31
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA A100 80GB PCIe
Device 0 Compute Capability  : 80
Device 0 PCI Bus ID          : 0000:18:00.0
Device 1 Name                : NVIDIA A100 80GB PCIe
Device 1 Compute Capability  : 80
Device 1 PCI Bus ID          : 0000:3B:00.0
Device 2 Name                : NVIDIA A100 80GB PCIe
Device 2 Compute Capability  : 80
Device 2 PCI Bus ID          : 0000:86:00.0
Device 3 Name                : NVIDIA A100 80GB PCIe
Device 3 Compute Capability  : 80
Device 3 PCI Bus ID          : 0000:AF:00.0
```

**Comment by leofang** [comment] 2022-10-29 00:16
This is not a bug, nor is it feasible for GPU computing. CuPy already does not support structured arrays (= an array of C structs, see https://github.com/cupy/cupy/issues/2031), and this is an array of arbitrary Python objects (`dict` in this case):
```python
>>> import numpy as np
>>> a = {1: 'a', 2: 'b'}
>>> b = np.array(a)
>>> b
array({1: 'a', 2: 'b'}, dtype=object)
```
which is not possible to support.

**Comment by kmaehashi** [comment] 2022-11-07 09:10
Closing as `object` dtypes will not be supported in CuPy. Feel free to reopen if you need any further discussion.

**Closed by kmaehashi** 2022-11-07 09:10 UTC
Labels: issue-checked
