### ISSUE TITLE
type object 'cupy.core.core.broadcast' has no attribute '__reduce_cython__'

### ISSUE THREAD

**Issue by eebssk1** [cupy/cupy#1910] opened 2018-12-24 14:59 UTC
After a normal chainer and cupy(cupy-cuda100) installation with fresh python 3.7.2,i got following error when running waifu2x-chainer..

`D:\waifu2x-chainer-master>python waifu2x.py
Traceback (most recent call last):
  File "waifu2x.py", line 5, in <module>
    import chainer
  File "C:\Program Files\Python37\lib\site-packages\chainer\__init__.py", line 21, in <module>
    from chainer import training  # NOQA
  File "C:\Program Files\Python37\lib\site-packages\chainer\training\__init__.py", line 3, in <module>
    from chainer.training import updaters  # NOQA
  File "C:\Program Files\Python37\lib\site-packages\chainer\training\updaters\__init__.py", line 1, in <module>
    from chainer.training.updaters.multiprocess_parallel_updater import MultiprocessParallelUpdater  # NOQA
  File "C:\Program Files\Python37\lib\site-packages\chainer\training\updaters\multiprocess_parallel_updater.py", line 13, in <module>
    from cupy.cuda import nccl
  File "C:\Program Files\Python37\lib\site-packages\cupy\__init__.py", line 11, in <module>
    from cupy import core  # NOQA
  File "C:\Program Files\Python37\lib\site-packages\cupy\core\__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
  File "cupy\core\core.pyx", line 2602, in init cupy.core.core
AttributeError: type object 'cupy.core.core.broadcast' has no attribute '__reduce_cython__'`
All packages are automatically installed by wheel.
Install cython 0.29.2 does not solve this...
Windows 10 1809

**Comment by apiszcz** [comment] 2019-01-04 07:58
seeing similar on import, Python 3.5

```
>>> import cupy as cp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\x\lib\cupy\__init__.py", line 11, in <module>
    from cupy import core  # NOQA
  File "C:\x\lib\cupy\core\__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
  File "core\core.pyx", line 2602, in init cupy.core.core
AttributeError: type object 'cupy.core.core.broadcast' has no attribute '__reduce_cython__'
```

**Comment by hisashi-tanaka** [comment] 2019-01-16 09:35
The same error, only when i import chainer w/ Python 3.6.7, chainer 5.1.0, CUDA 10.0, cupy 5.1.0
 Traceback (most recent call last):
  File "test.txt", line 1, in <module>
    import chainer
  File "C:\Users\Owner\Anaconda3\lib\site-packages\chainer\__init__.py", line 21, in <module>
    from chainer import training  # NOQA
  File "C:\Users\Owner\Anaconda3\lib\site-packages\chainer\training\__init__.py", line 3, in <module>
    from chainer.training import updaters  # NOQA
  File "C:\Users\Owner\Anaconda3\lib\site-packages\chainer\training\updaters\__init__.py", line 1, in <module>
    from chainer.training.updaters.multiprocess_parallel_updater import MultiprocessParallelUpdater  # NOQA
  File "C:\Users\Owner\Anaconda3\lib\site-packages\chainer\training\updaters\multiprocess_parallel_updater.py", line 13, in <module>
    from cupy.cuda import nccl
  File "C:\Users\Owner\Anaconda3\lib\site-packages\cupy\__init__.py", line 11, in <module>
    from cupy import core  # NOQA
  File "C:\Users\Owner\Anaconda3\lib\site-packages\cupy\core\__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
  File "cupy/core/core.pyx", line 2602, in init cupy.core.core
AttributeError: type object 'cupy.core.core.broadcast' has no attribute '__reduce_cython__'

**Comment by kmaehashi** [comment] 2019-01-21 03:44
Thanks for repots, however I couldn't reproduce the issue so far.

* Could you share the results of `pip freeze | grep cupy` and `cupy.show_config()`?
* Could you try uninstalling all CuPy packages and then reinstall `cupy-cuda100`?

**Comment by eebssk1** [comment] 2019-01-22 10:43
> 
> 
> Thanks for repots, however I couldn't reproduce the issue so far.
> 
>     * Could you share the results of `pip freeze | grep cupy` and `cupy.show_config()`?
> 
>     * Could you try uninstalling all CuPy packages and then reinstall `cupy-cuda100`?

In my case,the problem only happen on windows..

pip freeze:
F:\Downloads>pip freeze
cupy-cuda100==5.1.0
fastrlock==0.4
numpy==1.16.0
six==1.12.0

cupy.show_config():
>>> import cupy
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\cupy\__init__.py", line 11, in <module>
    from cupy import core  # NOQA
  File "C:\Program Files\Python37\lib\site-packages\cupy\core\__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
  File "cupy\core\core.pyx", line 1, in init cupy.core.core
  File "C:\Program Files\Python37\lib\site-packages\cupy\cuda\__init__.py", line 4, in <module>
    from cupy.cuda import compiler  # NOQA
  File "C:\Program Files\Python37\lib\site-packages\cupy\cuda\compiler.py", line 11, in <module>
    from cupy.cuda import device
  File "cupy\cuda\runtime.pxd", line 5, in init cupy.cuda.device
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python37\lib\site-packages\cupy\__init__.py", line 32, in <module>
    six.reraise(ImportError, ImportError(msg), exc_info[2])
  File "C:\Program Files\Python37\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "C:\Program Files\Python37\lib\site-packages\cupy\__init__.py", line 11, in <module>
    from cupy import core  # NOQA
  File "C:\Program Files\Python37\lib\site-packages\cupy\core\__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
  File "cupy\core\core.pyx", line 1, in init cupy.core.core
  File "C:\Program Files\Python37\lib\site-packages\cupy\cuda\__init__.py", line 4, in <module>
    from cupy.cuda import compiler  # NOQA
  File "C:\Program Files\Python37\lib\site-packages\cupy\cuda\compiler.py", line 11, in <module>
    from cupy.cuda import device
  File "cupy\cuda\runtime.pxd", line 5, in init cupy.cuda.device
ImportError: CuPy is not correctly installed.

If you are using wheel distribution (cupy-cudaXX), make sure that the version of CuPy you installed matches with the version of CUDA on your host.
Also, confirm that only one CuPy package is installed:
  $ pip freeze

If you are building CuPy from source, please check your environment, uninstall CuPy and reinstall it with:
  $ pip install cupy --no-cache-dir -vvvv

Check the Installation Guide for details:
  https://docs-cupy.chainer.org/en/latest/install.html

original error: DLL load failed: 找不到指定的模块。

But i can find cuda in nvidia control panel
NVCUDA.dll   24.21.14.1170  NVIDIA CUDA 10.0.150 driver

**Comment by eebssk1** [comment] 2019-01-25 10:12
> 
> 
> OK, I could reproduce the error. The root cause seems that you don't have CUDA DLL directory (e.g., `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin` in PATH environment variable. Could you check it?

i have installed cupy-cuda100,and nvcuda.dll is available in system32,which is already in PATH.

**Comment by kmaehashi** [comment] 2019-01-25 11:07
@hisashi-tanaka Could you try rebooting after changing PATH?
@eebssk1 In addition to `nvcuda.dll`, CuPy requires several DLLs like `cudart64_100.dll`, which are installed under `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin` by default.

**Comment by kmaehashi** [comment] 2019-01-28 07:50
In the next release, Chainer will become importable even if CuPy is installed *and* CUDA DLLs are unavailable. https://github.com/chainer/chainer/pull/6085

**Comment by kmaehashi** [comment] 2019-01-30 06:20
Closing as the root cause of this error is the misconfiguration of CUDA installation.

**Closed by kmaehashi** 2019-01-30 06:20 UTC

**Comment by soerendip** [comment] 2019-07-27 19:04
So, what is the correct way of installing it? I get the same error when using conda. And the cuda toolkit is already installed.

**Comment by eduamf** [comment] 2019-11-19 02:42
The computer doesn`t have CUDA!  I`m using Ubuntu 16.04.
I tried spacy 2.0, 2.1 and 2.2, without success. I tried with conda (removing previous versions), idem. 

```
...
  File "/opt/anaconda3/envs/pytorch1/lib/python3.6/site-packages/spacy/cli/download.py", line 10, in <module>
    from .link import link
  File "/opt/anaconda3/envs/pytorch1/lib/python3.6/site-packages/spacy/cli/link.py", line 7, in <module>
    from ..compat import symlink_to, path2str
  File "/opt/anaconda3/envs/pytorch1/lib/python3.6/site-packages/spacy/compat.py", line 11, in <module>
    from thinc.neural.util import copy_array
  File "/opt/anaconda3/envs/pytorch1/lib/python3.6/site-packages/thinc/neural/__init__.py", line 1, in <module>
    from ._classes.model import Model
  File "/opt/anaconda3/envs/pytorch1/lib/python3.6/site-packages/thinc/neural/_classes/model.py", line 12, in <module>
    from ..train import Trainer
  File "/opt/anaconda3/envs/pytorch1/lib/python3.6/site-packages/thinc/neural/train.py", line 3, in <module>
    from .optimizers import Adam, SGD, linear_decay
  File "optimizers.pyx", line 13, in init thinc.neural.optimizers
  File "ops.pyx", line 44, in init thinc.neural.ops
  File "/opt/anaconda3/envs/pytorch1/lib/python3.6/site-packages/cupy/__init__.py", line 11, in <module>
    from cupy import core  # NOQA
  File "/opt/anaconda3/envs/pytorch1/lib/python3.6/site-packages/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
  File "cupy/core/carray.pxi", line 50, in init cupy.core.core
AttributeError: type object 'cupy.core.core.Indexer' has no attribute '__reduce_cython__'
```
I can`t use spacy without CUDA?

**Comment by eduamf** [comment] 2019-11-19 02:54
But CuPy is "an implementation of NumPy-compatible multi-dimensional array on CUDA. CuPy consists of the core multi-dimensional array class, cupy.ndarray, and many functions on it. It supports a subset of numpy.ndarray interface". I didn`t find a CPU cudy version. Maybe the fix solution is to use NumPy instead CuPy.

**Comment by shartoo** [comment] 2021-02-08 07:38
Please check your package version matches the cuda version.For example,there maybe a cupy-cuda90(python package) with cuda9.0(cuda driver),and a cupy-cuda100 and cuda10.0.
