### ISSUE TITLE
Jitify cache paths on Windows in Cupy13

### ISSUE THREAD

**Issue by montardon** [cupy/cupy#8218] opened 2024-02-29 08:48 UTC
### Description

When I run Cupy on Windows, I get the following error :

```
File "C:\Users\localuser\miniconda3\envs\myenv\Lib\site-packages\cupy\cuda\compiler.py", line 233, in _jitify_prep
  jitify._init_module()
File "cupy\cuda\jitify.pyx", line 212, in cupy.cuda.jitify._init_module
File "cupy\cuda\jitify.pyx", line 233, in cupy.cuda.jitify._init_module
File "cupy\cuda\jitify.pyx", line 209, in cupy.cuda.jitify._init_cupy_headers
File "cupy\cuda\jitify.pyx", line 198, in cupy.cuda.jitify._init_cupy_headers_from_scratch
File "cupy\cuda\jitify.pyx", line 128, in cupy.cuda.jitify.dump_cache
File "cupy\cuda\jitify.pyx", line 128, in cupy.cuda.jitify.dump_cache
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\localuser\\.cupy\\jitify_cache\\tmpa_w7ra_4' -> 'C:\\Users\\localuser/.cupy/jitify_cache/jitify_<unknown>_200200_12030_2_ad21c064b825bdd2bfab49f9b20d4083d4afa782.json'
```

Cache paths are not correctly formatted for Windows.

### To Reproduce

```py
import cupy as cp
import numpy as np
from cupyx.scipy.signal import decimate

if __name__ == "__main__":
    a = np.array((1000,1000))
    b = decimate(a,3)
    print(b)
```

### Installation

Source (`pip install cupy`)

### Environment

```
Python 3.12.2 | packaged by Anaconda, Inc. | (main, Feb 27 2024, 17:28:07) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cupy
>>> cupy.show_config()
OS                           : Windows-10-10.0.19045-SP0
Python Version               : 3.12.2
CuPy Version                 : 13.0.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.26.4
SciPy Version                : 1.12.0
Cython Build Version         : 0.29.37
Cython Runtime Version       : None
CUDA Root                    : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3
nvcc PATH                    : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\bin\nvcc.EXE
CUDA Build Version           : 12030
CUDA Driver Version          : 12030
CUDA Runtime Version         : 12030 (linked to CuPy) / 12030 (locally installed)
cuBLAS Version               : (available)
cuFFT Version                : 11012
cuRAND Version               : 10304
cuSOLVER Version             : (11, 5, 4)
cuSPARSE Version             : (available)
NVRTC Version                : (12, 3)
Thrust Version               : 200200
CUB Build Version            : 200200
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 2080 Super
Device 0 Compute Capability  : 75
Device 0 PCI Bus ID          : 0000:01:00.0
>>>
```

### Additional Information

The same code works fine on Ubuntu 22.04.

**Comment by leofang** [comment] 2024-02-29 11:51
This is a duplicate of #8147, and fixed in #8154 which will land in v13.1.0. In the meanwhile, please install CuPy wheels (cupy-cuda11x or cupy-cuda12x) instead of from source, which is known to be issue-free (#8153). We do not encourage building from source, anyway.

**Comment by montardon** [comment] 2024-02-29 13:16
Thank you for your quick answer. I'll install Cupy wheels, waiting for the fix.

**Comment by kmaehashi** [comment] 2024-03-01 05:38
Let me close this as duplicate, thanks for reporting!

**Closed by kmaehashi** 2024-03-01 05:38 UTC
Labels: issue-checked
