### ISSUE TITLE
cudaErrorInvalidResourceHandle when using cupy's thread

### ISSUE THREAD

**Issue by mfoglio** [cupy/cupy#4618] opened 2021-02-04 00:40 UTC
I have a Python application that also uses tensorRT and therefore has its own context that get pushed and pop from the gpu (cud's `context.pop()` and `context.push()`).

Among the rest of the code, I have the following class:

```
class Example:

    def __init__(self, number_of_streams: int):
        self.cupy_streams = [cp.cuda.stream.Stream(non_blocking=True) for _ in range(number_of_streams)]

    def pre_process(self, cp_arrays: List[cp.array], thread_number: int):
        """ cp_arrays is a list of cupy arrays shape (720, 1280, 3) and dtype uint8"""
        self.cupy_streams[thread_number].use()
        ... some stuff ...
        cp_arrays = cp.array(cp_arrays, dtype=cp.uint8) # this line crashes
        ... some stuff ...
        self.cupy_streams[thread_number].synchronize()
        return imgs_batch

```

The line that produces a crash reports:

```
--- Logging error ---
Traceback (most recent call last):
  File "/myfile.py", line 37, in __init__
    self.cupy_frame = cp.array(self.numpy_frame, dtype=cp.uint8)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/cupy/_creation/from_data.py", line 41, in array
    return core.array(obj, dtype, copy, order, subok, ndmin)
  File "cupy/core/core.pyx", line 1984, in cupy.core.core.array
  File "cupy/core/core.pyx", line 2063, in cupy.core.core.array
  File "cupy/core/core.pyx", line 2150, in cupy.core.core._send_object_to_gpu
  File "cupy/cuda/stream.pyx", line 242, in cupy.cuda.stream.BaseStream.record
  File "cupy_backends/cuda/api/runtime.pyx", line 854, in cupy_backends.cuda.api.runtime.eventRecord
  File "cupy_backends/cuda/api/runtime.pyx", line 247, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorInvalidResourceHandle: invalid resource handle

```

Do I need to create a new Stream each time? Would that be a good idea considering this function is called quite open (real time, probably 50-200 calls per seconds in a real time application)?

What the code does, beside creating the array from a list of arrays, are simple math (sum and multiplication), one call to ndimage.zoom, and a transpose operation.

My goal is of course to improve performance and concurrency. The input and the output of the function are cupy's arrays. 
I have 50 threads that can call this function and of course I'd like to improve concurrency. There are other parts of the code using the GPU concurrently to the code posted above (tensorRT).

Thanks!

```
>>> import cupy; cupy.show_config()
OS                           : Linux-5.4.0-1037-aws-x86_64-with-Ubuntu-18.04-bionic
CuPy Version                 : 8.2.0
NumPy Version                : 1.19.4
SciPy Version                : 1.5.4
Cython Build Version         : 0.29.21
CUDA Root                    : /usr/local/cuda-11.1
CUDA Build Version           : 11010
CUDA Driver Version          : 11020
CUDA Runtime Version         : 11010
cuBLAS Version               : 11300
cuFFT Version                : 10300
cuRAND Version               : 10202
cuSOLVER Version             : (11, 0, 1)
cuSPARSE Version             : 11300
NVRTC Version                : (11, 1)
Thrust Version               : 100910
CUB Build Version            : 100910
cuDNN Build Version          : 8005
cuDNN Version                : 8005
NCCL Build Version           : 2708
NCCL Runtime Version         : 2708
cuTENSOR Version             : None
Device 0 Name                : Tesla T4
Device 0 Compute Capability  : 75
```

**Comment by leofang** [comment] 2021-02-04 17:23
@mfoglio CuPy uses CUDA Runtime API's Primary Context, which is [unique per device per process](https://docs.nvidia.com/cuda/cuda-runtime-api/driver-vs-runtime-api.html#driver-vs-runtime-api). My guess is some of your threads do not have the context properly initialized.

Is it possible to pick up the current context in tensorRT, instead of pushing and popping yourselves? If so, one workaround could be to let CuPy initialize the context first (by making any calls involving the Runtime API, like `cupy.cuda.Device().mem_info`), and then make other libraries pick up the current context (under the hood it'd be calling `cuCtxGetCurrent`).

Another way for libraries like PyCUDA that conventionally asks users to manage a custom CUDA context (I guess tensorRT is also one of them?) is to properly create the context *for each participating threads* (because `cuCtxCreate` is done per thread, not per process), make the context current, and then invoke Runtime APIs. This way the Runtime API will pick up the current context correctly.

**Comment by mfoglio** [comment] 2021-02-04 23:23
Interesting, thank you.

So right now when initializing my tensorRT model I am creating a context `self.cfx = cuda.Device(0).make_context(flags=cuda.ctx_flags.BLOCKING_SYNC)`, then removing it instantly `cfx.pop()`, and then doing `cfx.push()` and `cfx.pop()` at the beginning and end of each inference with the model.

If I remove those command, and I add `cupy.cuda.Device().mem_info` to the beginning of the file, I get the error:
```
stream = cuda.Stream()
pycuda._driver.LogicError: explicit_context_dependent failed: invalid device context - no currently active context?
```

I suspect that, as you mention, I need to perform a `cuCtxGetCurrent`. Do you where I can find this command in `pycuda`? Would I still need to do push and pop operations?

**Comment by leofang** [comment] 2021-02-05 04:13
Hi @mfoglio Could you give a short reproducer for the errors you saw? I tried to follow your description but I don't see anything wrong:
```python
from pycuda import driver
import cupy as cp


driver.init()
dev = driver.Device(0)
ctx = dev.make_context()
s = cp.cuda.Stream()

# check cupy is picking up the same context:
# the pointer addresses should be identical
print(cp.cuda.driver.ctxGetCurrent())
print(ctx.handle)

ctx.pop()
```

> Do you where I can find this command in `pycuda`? Would I still need to do push and pop operations?

Sorry I wasn't being clear. `cuCtxGetCurrent` is a [CUDA Driver API](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__CTX.html#group__CUDA__CTX_1g8f13165846b73750693640fb3e8380d0). Looks like CuPy has a wrapper for it (see the above snippet), but PyCUDA does not.
 
> UPDATE: I also tried to add `cuda.Device(0).retain_primary_context()` before the `stream = cuda.Stream()` but I still have the same error (` invalid device context - no currently active context?`)

Looks like this alternative workaround would not work with PyCUDA unfortunately. I think for this to work you need to let the Runtime API initialize first (i.e. call any Runtime API), retrieve the context, and then set it current (which `retain_primary_context()` does not do). But the last step requires calling `cuCtxSetCurrent()`, for which, again, PyCUDA does not provide a wrapper but CuPy does. Frankly IMHO PyCUDA was never designed to work well with Runtime API, which is annoying. 

In general, if you let the Runtime API to manage the (Primary) Context for you, there's no need to pop/push yourselves. In particular, such actions are best done at the beginning and end of the *process*, and I don't see why you need to do it at each inference stage. Is there any need that I overlooked?

Finally, as a past PyCUDA user and a current CuPy developer, I'd love to learn more about what's there in PyCUDA that you absolutely need but CuPy does not provide. IMHO we've made CuPy quite competent in v7 (and now we're on v8 and moving toward v9). We'll be more than happy to help you transition to CuPy as best as we can. 🙂 I just checked TensorRT's Python doc, and it doesn't make PyCUDA a core dependency.

**Comment by leofang** [comment] 2021-02-05 04:52
> > UPDATE: I also tried to add `cuda.Device(0).retain_primary_context()` before the `stream = cuda.Stream()` but I still have the same error (` invalid device context - no currently active context?`)
> 
> Looks like this alternative workaround would not work with PyCUDA unfortunately. I think for this to work you need to let the Runtime API initialize first (i.e. call any Runtime API), retrieve the context, and then set it current (which `retain_primary_context()` does not do). But the last step requires calling `cuCtxSetCurrent()`, for which, again, PyCUDA does not provide a wrapper but CuPy does. Frankly IMHO PyCUDA was never designed to work well with Runtime API (or any libraries based on Runtime API), which is annoying.

Sorry, I take this part back. I wasn't thinking clearly: If you already have the Primary Context made current (by the Runtime API), you don't have to push/pop it. It should just work:
```python
from pycuda import driver
import cupy as cp


s = cp.cuda.Stream()
dev = driver.Device(0)
ctx = dev.retain_primary_context()

# check cupy is picking up the same context:
# the pointer addresses should be identical
print(cp.cuda.driver.ctxGetCurrent())
print(ctx.handle)
```
Note that in the end you don't do `ctx.pop()` to clean up -- as I mentioned the Runtime API does it for you.

**Comment by leofang** [comment] 2021-02-16 18:02
It's in `Stream.ptr`, so you can either provide the handle to the stream that you created
```python
import cupy as cp

s = cp.cuda.Stream()
handle = s.ptr
```
or use CuPy's current stream
```python
import cupy as cp

s = cp.cuda.get_current_stream()
handle = s.ptr
```

**Comment by yuvalg1987** [comment] 2021-10-03 11:55
Hi, I'm facing a similar issue, I working with a live stereo camera which has its own context, I would like to process the incoming images using CuPy. Currently I'm getting the INVALID_RESOURCE_HANDLE error but not sure how to resolve it. Any ideas?

**Comment by yuvalg1987** [comment] 2021-10-04 13:24
Just to update on my solution for this issue. The ZED runs its own context internally and therefore processing images using CuPy should be handled in a different thread. My best solution relied on the ZED-TensorFlow example which worked pretty good.

**Comment by kmaehashi** [comment] 2024-09-17 15:44
Closing as inactive for a while. Please feel free to open another issue if you still have a problem.

**Closed by kmaehashi** 2024-09-17 15:44 UTC
Labels: issue-checked
