### ISSUE TITLE
Cupy not waiting for TensorRT execution

### ISSUE THREAD

**Issue by mfoglio** [cupy/cupy#6104] opened 2021-11-16 15:53 UTC
### Description

I am working with TensorRT 7.2.1.6 and `cupy-111`. I'd like to use cuda streams to optimize the application.
It seems that cupy is not waiting for the TensorRT execution since the following code returns random results when the cupy stream is created with `stream = cp.cuda.Stream(non_blocking=True)` while the code works perfectly when using `non_blocking=False`.
Note that I am also reusing the same stream after one execution completes.

### To Reproduce

```
# Select stream
stream.use()
# Copy cupy array to the buffer
input_images = cp.array(batch_input_image)
cp.copyto(cuda_inputs[0], input_images)
# Run inference.
context.execute_async(bindings=bindings, stream_handle=stream.ptr, batch_size=len(batch_input_image))
# Copy results from the buffer
output_images = cuda_outputs[0].copy()
# Split results into batch
list_output = cp.split(output_images, indices_or_sections=len(batch_input_image), axis=0)
# Squeeze output arrays to remove axis of length one
list_output = [cp.squeeze(array) for array in list_output]
# Synchronize the stream
stream.synchronize()
```

### Installation

Wheel (`pip install cupy-***`)

### Environment

```
OS                           : Linux-5.9.0-yoctodev-standard-x86_64-with-Ubuntu-18.04-bionic
CuPy Version                 : 8.2.0
NumPy Version                : 1.19.5
SciPy Version                : 1.5.4
Cython Build Version         : 0.29.21
CUDA Root                    : /usr/local/cuda
CUDA Build Version           : 11010
CUDA Driver Version          : 11010
CUDA Runtime Version         : 11010
cuBLAS Version               : 11201
cuFFT Version                : 10300
cuRAND Version               : 10202
cuSOLVER Version             : (11, 0, 0)
cuSPARSE Version             : 11200
NVRTC Version                : (11, 1)
Thrust Version               : 100910
CUB Build Version            : 100910
cuDNN Build Version          : 8005
cuDNN Version                : 8004
NCCL Build Version           : 2708
NCCL Runtime Version         : 2708
cuTENSOR Version             : None
Device 0 Name                : GeForce RTX 2060
Device 0 Compute Capability  : 75
```

**Comment by leofang** [comment] 2021-11-16 17:17
@mfoglio @pranavm-nvidia If a CuPy stream is set in use (via `.use()`), all of the subsequent operations are enqueued on that stream instead of the default stream 0. What does `context.execute_async()` do? Does it fork/spawn?

**Comment by pranavm-nvidia** [comment] 2021-11-16 17:23
`context.execute_async()` enqueues operations on the provided stream; it does not create any additional processes

**Comment by mfoglio** [comment] 2021-11-16 17:34
Is there a way to list the enqueued operations?

**Comment by pranavm-nvidia** [comment] 2021-11-16 17:39
A profiler like [NSight Systems](https://developer.nvidia.com/nsight-systems) might help. That should show you what's happening on each stream. 

I'm also curious as to whether inserting a `stream.synchronize()` just after `context.execute_async()` changes anything? That would indicate that TensorRT is running on the provided stream.

**Comment by mfoglio** [comment] 2021-11-16 18:53
It seems that you both agree on the fact that the code above should work. Let me double check everything in my code to make sure I haven't missed anything somewhere else. Thank you!

**Comment by mfoglio** [comment] 2021-11-16 18:57
I have different part of the code that performs the preprocessing of the arrays that are fed to the AI model. The preprocessing is done with cupy streams but it seems that the code above is really the critical part:
```
        with cp.cuda.Stream(non_blocking=False) as stream:  # if I set non_blocking=True I have sync issue
            # Copy cupy array to the buffer
            input_images = cp.array(batch_input_image)
            cp.copyto(cuda_inputs[0], input_images)
            # Run inference.
            context.execute_async(bindings=bindings, stream_handle=stream.ptr, batch_size=len(batch_input_image))
            # Copy results from the buffer
            output_images = cuda_outputs[0].copy()
            # Split results into batch
            list_output = cp.split(output_images, indices_or_sections=len(batch_input_image), axis=0)
            # Squeeze output arrays to remove axis of length one
            list_output = [cp.squeeze(array) for array in list_output]
            # Synchronize the stream
            stream.synchronize()
```
Is this sufficient to be 100% sure that the issue is actually in this block of code?

**Comment by mfoglio** [comment] 2021-11-16 19:05
@pranavm-nvidia @leofang also adding `stream.synchronize()` after the `execute_async` doesn't seem to help

**Comment by pranavm-nvidia** [comment] 2021-11-16 19:07
What's the reason for the initial `copyto` in your code? I had assumed it was a host->device copy, but since you're preprocessing on GPU, it doesn't seem like that should be the case. Just a guess, but maybe the issue is that you're running preprocessing on the null stream without a barrier before the code block above? That might explain why `non_blocking=False` works (because presumably it would wait for the work on the null stream to finish)

**Comment by mfoglio** [comment] 2021-11-16 19:11
So following the TensorRT tutorials I used to allocate some buffers on the GPU with are passed as bindings to TensorRT. What I am doing is copying the cupy array that I have into those buffers (so no exactly a host->device copy).
If what you are saying is true, wouldn't `cp.cuda.Device(0).synchronize()` before `with cp.cuda.Stream(non_blocking=True) as stream)` fix the issue? I tried to add it but it doesn't change the result.

**Comment by pranavm-nvidia** [comment] 2021-11-16 19:20
Assuming that's calling `cudaDeviceSynchronize`, that should be enough to conclude that the error is there. But just to be 100% sure, can you try checking the preprocessed inputs just before that code block to make sure they look ok?

Also, is it possible for you to share more of the code? Ideally including the preprocessing and how `cuda_inputs`/`cuda_outputs` and `bindings` are set up.

**Comment by mfoglio** [comment] 2021-11-16 19:28
Ok, so I saved the preprocessed input into a binary file:
```
        with cp.cuda.Stream(non_blocking=False) as stream:
            # Copy cupy array to the buffer
            # input_images = cp.array(batch_input_image)
            input_images = cp.load("preprocessed_input.npy")
            cp.copyto(cuda_inputs[0], input_images)
            # Run inference.
            context.execute_async(bindings=bindings, stream_handle=stream.ptr, batch_size=len(batch_input_image))
            # Copy results from the buffer
            output_images = cuda_outputs[0].copy()
            # Split results into batch
            list_output = cp.split(output_images, indices_or_sections=len(batch_input_image), axis=0)
            # Squeeze output arrays to remove axis of length one
            list_output = [cp.squeeze(array) for array in list_output]
            # Synchronize the stream
            stream.synchronize()
```
As for the initialization, it is the following:
```
        # Deserialize the engine from file
        with open(self.engine_path, "rb") as f:
            engine = runtime.deserialize_cuda_engine(f.read())
        context = engine.create_execution_context()

        cuda_inputs = []
        cuda_outputs = []
        bindings = []

        for binding in engine:
            shape = [engine.max_batch_size, *engine.get_binding_shape(binding)]
            dtype = trt.nptype(engine.get_binding_dtype(binding))
            # Allocate host and device buffers
            cuda_mem = cp.zeros(shape=shape, dtype=dtype)  # cuda.mem_alloc(host_mem.nbytes)
            # Append the device buffer to device bindings.
            bindings.append(cuda_mem.data.ptr)
            # Append to the appropriate list.
            if engine.binding_is_input(binding):
                cuda_inputs.append(cuda_mem)
            else:
                cuda_outputs.append(cuda_mem)
```

**Comment by pranavm-nvidia** [comment] 2021-11-16 19:34
That seems right to me. Could you try out [NSight](https://developer.nvidia.com/nsight-systems) to see what's running on each stream? That would let us figure out if it's a bug in cupy or TensorRT.

**Comment by mfoglio** [comment] 2021-11-16 19:45
@pranavm-nvidia let me know if you manage to open the nsys report here https://file.io/21POsa8xNHi8

**Comment by pranavm-nvidia** [comment] 2021-11-16 20:17
@mfoglio It looks like there's a custom plugin called `CalDetection` using the default stream. That's most likely the source of the issue. Could you double check your implementation?

![streams](https://user-images.githubusercontent.com/49246958/142059070-d46fe80b-4d23-49b8-90ff-57c43e8927bf.png)

**Comment by mfoglio** [comment] 2021-11-16 20:22
@pranavm-nvidia are you referring to the TensorRT model implementation or cupy / something else?

**Comment by pranavm-nvidia** [comment] 2021-11-16 20:31
@mfoglio It's either a bug in the `CalDetection`/`YoloLayerPlugin` implementation or within TensorRT. Could you see if you're able to reproduce this with a newer version of TensorRT (like 8.2)?

Also, I think it's safe to rule out cupy, so maybe we should move the discussion to a TensorRT issue?

**Comment by kmaehashi** [comment] 2021-11-17 03:10
Closing as discussed above. We are happy to help if there's anything we can do in CuPy 😄

**Closed by kmaehashi** 2021-11-17 03:10 UTC
Labels: cat:bug
