### ISSUE TITLE
Is there a plan to implement a GPU version of opencv.remap?

### ISSUE THREAD

**Issue by bsugerman** [cupy/cupy#2844] opened 2019-12-20 15:00 UTC
I'm very excited to be using cupy and have thusfar found it incredibly simple to use and very complete in terms of the functions I've needed. However, it is missing the cv2.remap() function which I'd argue is a critical part of image processing. Is there a plan in the works to code that up, or do you know if someone has made their own version using cupy?

**Comment by niboshi** [comment] 2019-12-24 07:21
I'm sorry but currently OpenCV is out of scope of CuPy.

**Closed by niboshi** 2019-12-24 07:21 UTC

**Comment by leofang** [comment] 2019-12-24 07:40
I think the question was whether there’d be a CuPy-equivalent of [remap](https://docs.opencv.org/2.4/modules/imgproc/doc/geometric_transformations.html?highlight=remap). I suppose `cupyx.scipy.ndimages` provides similar functionalities (or building blocks) for that?

**Comment by bsugerman** [comment] 2019-12-24 14:44
Yes that is the question. You can use map_coordinates as a hack, but it runs many times slower than opencv’s remap. But you also lose a lot of compute time sending data between the cpu and gpu, so having a gpu version of this kind of module is very useful.

**Comment by leofang** [comment] 2019-12-24 15:01
It is a known issue that several functions in the `cupyx.scipy.ndimage` module, including `map_coordinates`, are not very performant, see #2607. But I am not sure about the data transfer part.

@niboshi perhaps it's worth reopening this issue?

**Comment by niboshi** [comment] 2019-12-24 15:30
Basically we won't implement anything that are not in NumPy nor SciPy, but once the topic of the issue is made more relevant (performance of `map_coordinate`?), please feel to reopen it.

**Comment by bsugerman** [comment] 2019-12-24 15:30
For completeness, I did a little timing exercise on my machine using a 400x600 array. I can run cv2.remap on it in 625 µs on the cpu.  Using scipy's map_coordinates, it takes 10 ms on the cpu, or 3.3 ms using cupy's version on the gpu. There's an extra penalty of 23 µs to convert back/forth from gpu to cpu if I'm going to insert the opencv version of remap into a longer algorithm stream. I'm trying to do realtime processing so I really need that 625 µs to be cut down, and I'd like to not have to pay the extra 23 µs either. 

I am currently compiling opencv with CUDA support on my machine and am going to try cv2.cuda.remap, although I'm not sure whether (a) it will work because compiling on windows is awful, and (b) whether cupy and cv2.cuda will communicate nicely. But I'll update that here, again for completeness.

**Comment by leofang** [comment] 2019-12-26 16:02
> Basically we won't implement anything that are not in NumPy nor SciPy

Doesn't CuPy supports a (very limited) subset of OpenCV functionalities in `cupyx.scipy.ndimage`? https://docs-cupy.chainer.org/en/latest/reference/ndimage.html#opencv-mode

**Comment by bsugerman** [comment] 2019-12-26 16:09
Yes but not anything like `remap`

**Comment by iperov** [comment] 2021-08-29 14:51
my warpAffine implementation in CuPy, which also includes remap

```
if xp == np:
    img = cv2.warpAffine(img, mat, (out_width, out_height), flags=_cv_inter[interpolation] )
else:
    # AffineMat inverse
    xp_mat = xp.get_array_module(mat)
    mat = xp_mat.linalg.inv(xp_mat.concatenate( ( mat, xp_mat.array([[0,0,1]], xp_mat.float32)), 0) )[0:2,:]
    mx, my = xp.meshgrid( xp.arange(0, out_width, dtype=xp.float32), xp.arange(0, out_height, dtype=xp.float32) )
    coords = xp.concatenate( (mx[None,...], my[None,...], xp.ones( (1, out_height,out_width), dtype=xp.float32)), 0 )
    mat_coords = xp.matmul (xp.asarray(mat), coords.reshape( (3,-1) ) ).reshape( (2,out_height,out_width))
    # remap
    img = xp.concatenate([sp.ndimage.map_coordinates( img[...,c], mat_coords[::-1,...], order=_scipy_order[interpolation], mode='opencv' )[...,None] for c in range(N*C) ], -1)
```
